In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import numpy as np

Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing

In [3]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype="float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y = np.array([0, 0, 0, 1], dtype="int32")
y

array([0, 0, 0, 1])

## 케라스 모델 초기화

In [5]:
model = Sequential()

## 케라스 레이어 추가(인풋 2, 아웃풋 1인 레이어)

In [6]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
model.layers[0].get_weights()

[array([[ 1.0057157],
        [-0.8295508]], dtype=float32), array([0.], dtype=float32)]

In [8]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss = 'binary_crossentropy', optimizer=Adam(lr=0.1), metrics=['acc'])

In [10]:
model.fit(X, y, epochs=500)

Instructions for updating:
Use tf.cast instead.
Epoch 1/500
4/4 [==============================] - 0s 92ms/step - loss: 0.7454 - acc: 0.7500
Epoch 2/500
4/4 [==============================] - 0s 748us/step - loss: 0.7182 - acc: 0.7500
Epoch 3/500
4/4 [==============================] - 0s 748us/step - loss: 0.6893 - acc: 0.7500
Epoch 4/500
4/4 [==============================] - 0s 748us/step - loss: 0.6615 - acc: 0.5000
Epoch 5/500
4/4 [==============================] - 0s 498us/step - loss: 0.6359 - acc: 0.5000
Epoch 6/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6130 - acc: 0.5000
Epoch 7/500
4/4 [==============================] - 0s 748us/step - loss: 0.5924 - acc: 0.7500
Epoch 8/500
4/4 [==============================] - 0s 499us/step - loss: 0.5737 - acc: 0.7500
Epoch 9/500
4/4 [==============================] - 0s 748us/step - loss: 0.5560 - acc: 0.7500
Epoch 10/500
4/4 [==============================] - 0s 748us/step - loss: 0.5389 - acc: 0.7500
Epoch 11/500
4

Epoch 85/500
4/4 [==============================] - 0s 3ms/step - loss: 0.1185 - acc: 1.0000
Epoch 86/500
4/4 [==============================] - 0s 748us/step - loss: 0.1170 - acc: 1.0000
Epoch 87/500
4/4 [==============================] - 0s 249us/step - loss: 0.1156 - acc: 1.0000
Epoch 88/500
4/4 [==============================] - 0s 748us/step - loss: 0.1142 - acc: 1.0000
Epoch 89/500
4/4 [==============================] - 0s 748us/step - loss: 0.1129 - acc: 1.0000
Epoch 90/500
4/4 [==============================] - 0s 748us/step - loss: 0.1116 - acc: 1.0000
Epoch 91/500
4/4 [==============================] - 0s 748us/step - loss: 0.1103 - acc: 1.0000
Epoch 92/500
4/4 [==============================] - 0s 499us/step - loss: 0.1090 - acc: 1.0000
Epoch 93/500
4/4 [==============================] - 0s 499us/step - loss: 0.1077 - acc: 1.0000
Epoch 94/500
4/4 [==============================] - 0s 249us/step - loss: 0.1065 - acc: 1.0000
Epoch 95/500
4/4 [==============================] - 

Epoch 171/500
4/4 [==============================] - 0s 250us/step - loss: 0.0524 - acc: 1.0000
Epoch 172/500
4/4 [==============================] - 0s 748us/step - loss: 0.0520 - acc: 1.0000
Epoch 173/500
4/4 [==============================] - 0s 748us/step - loss: 0.0516 - acc: 1.0000
Epoch 174/500
4/4 [==============================] - 0s 499us/step - loss: 0.0512 - acc: 1.0000
Epoch 175/500
4/4 [==============================] - 0s 499us/step - loss: 0.0509 - acc: 1.0000
Epoch 176/500
4/4 [==============================] - 0s 499us/step - loss: 0.0505 - acc: 1.0000
Epoch 177/500
4/4 [==============================] - 0s 499us/step - loss: 0.0501 - acc: 1.0000
Epoch 178/500
4/4 [==============================] - 0s 499us/step - loss: 0.0497 - acc: 1.0000
Epoch 179/500
4/4 [==============================] - 0s 499us/step - loss: 0.0494 - acc: 1.0000
Epoch 180/500
4/4 [==============================] - 0s 499us/step - loss: 0.0490 - acc: 1.0000
Epoch 181/500
4/4 [=====================

Epoch 257/500
4/4 [==============================] - 0s 499us/step - loss: 0.0303 - acc: 1.0000
Epoch 258/500
4/4 [==============================] - 0s 498us/step - loss: 0.0301 - acc: 1.0000
Epoch 259/500
4/4 [==============================] - 0s 250us/step - loss: 0.0300 - acc: 1.0000
Epoch 260/500
4/4 [==============================] - 0s 748us/step - loss: 0.0298 - acc: 1.0000
Epoch 261/500
4/4 [==============================] - 0s 499us/step - loss: 0.0297 - acc: 1.0000
Epoch 262/500
4/4 [==============================] - 0s 250us/step - loss: 0.0295 - acc: 1.0000
Epoch 263/500
4/4 [==============================] - 0s 997us/step - loss: 0.0293 - acc: 1.0000
Epoch 264/500
4/4 [==============================] - 0s 997us/step - loss: 0.0292 - acc: 1.0000
Epoch 265/500
4/4 [==============================] - 0s 498us/step - loss: 0.0290 - acc: 1.0000
Epoch 266/500
4/4 [==============================] - 0s 748us/step - loss: 0.0289 - acc: 1.0000
Epoch 267/500
4/4 [=====================

Epoch 343/500
4/4 [==============================] - 0s 748us/step - loss: 0.0201 - acc: 1.0000
Epoch 344/500
4/4 [==============================] - 0s 499us/step - loss: 0.0200 - acc: 1.0000
Epoch 345/500
4/4 [==============================] - 0s 250us/step - loss: 0.0199 - acc: 1.0000
Epoch 346/500
4/4 [==============================] - 0s 748us/step - loss: 0.0198 - acc: 1.0000
Epoch 347/500
4/4 [==============================] - 0s 249us/step - loss: 0.0197 - acc: 1.0000
Epoch 348/500
4/4 [==============================] - 0s 249us/step - loss: 0.0197 - acc: 1.0000
Epoch 349/500
4/4 [==============================] - 0s 249us/step - loss: 0.0196 - acc: 1.0000
Epoch 350/500
4/4 [==============================] - 0s 498us/step - loss: 0.0195 - acc: 1.0000
Epoch 351/500
4/4 [==============================] - 0s 499us/step - loss: 0.0194 - acc: 1.0000
Epoch 352/500
4/4 [==============================] - 0s 250us/step - loss: 0.0193 - acc: 1.0000
Epoch 353/500
4/4 [=====================

Epoch 429/500
4/4 [==============================] - 0s 499us/step - loss: 0.0144 - acc: 1.0000
Epoch 430/500
4/4 [==============================] - 0s 249us/step - loss: 0.0144 - acc: 1.0000
Epoch 431/500
4/4 [==============================] - 0s 499us/step - loss: 0.0143 - acc: 1.0000
Epoch 432/500
4/4 [==============================] - 0s 498us/step - loss: 0.0143 - acc: 1.0000
Epoch 433/500
4/4 [==============================] - 0s 498us/step - loss: 0.0142 - acc: 1.0000
Epoch 434/500
4/4 [==============================] - 0s 998us/step - loss: 0.0142 - acc: 1.0000
Epoch 435/500
4/4 [==============================] - 0s 495us/step - loss: 0.0141 - acc: 1.0000
Epoch 436/500
4/4 [==============================] - 0s 250us/step - loss: 0.0141 - acc: 1.0000
Epoch 437/500
4/4 [==============================] - 0s 250us/step - loss: 0.0140 - acc: 1.0000
Epoch 438/500
4/4 [==============================] - 0s 748us/step - loss: 0.0140 - acc: 1.0000
Epoch 439/500
4/4 [=====================

In [12]:
pred = model.predict(X)
pred

array([[3.5973010e-06],
       [1.4146900e-02],
       [1.4721351e-02],
       [9.8349887e-01]], dtype=float32)

In [14]:
predict01 = np.where(pred>0.5, 1, 0)
predict01

array([[0],
       [0],
       [0],
       [1]])

In [15]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [17]:
predict03 = (predict02 == y)
predict03

array([ True,  True,  True,  True])

In [18]:
acc = np.sum(predict03)/4
acc

1.0