In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

c:\library\python\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, defaultdict
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synon

In [2]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X = data.data
X = np.array(X, dtype="float32")
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = data["target"]
y = np.array(y, dtype="float32")
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## 숫자 값 0~n까지인 값을 M*N 의 행렬로 바꿔준다
## M은 데이터의 크기

In [6]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [7]:
y_train_onehot = enc.transform(y_train).toarray()
y_train_onehot = np.array(y_train_onehot, dtype="float32")
y_train_onehot

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train = scaler.transform(X_train)
X_train

array([[ 4.78778929e-01, -3.52269679e-01,  3.24554622e-01,
         1.45326123e-01],
       [-7.20670342e-01,  9.96849298e-01, -1.24226058e+00,
        -1.27564394e+00],
       [ 3.58834118e-01, -1.02682972e+00,  1.05200434e+00,
         2.74505258e-01],
       [ 7.18669116e-01,  3.22289824e-01,  4.36469883e-01,
         4.03684378e-01],
       [-1.08050478e+00, -1.27416700e-01, -1.29821825e+00,
        -1.27564394e+00],
       [-1.20945707e-01, -1.02682972e+00, -1.23106912e-01,
        -2.42211118e-01],
       [-1.68022943e+00,  3.22289824e-01, -1.35417593e+00,
        -1.27564394e+00],
       [ 1.18944481e-01, -1.27416700e-01,  2.68596739e-01,
         4.03684378e-01],
       [-1.44033980e+00,  3.22289824e-01, -1.29821825e+00,
        -1.27564394e+00],
       [ 3.58834118e-01, -1.27416700e-01,  6.60300672e-01,
         7.91221619e-01],
       [-1.20044959e+00, -1.27416700e-01, -1.29821825e+00,
        -1.40482306e+00],
       [-1.20044959e+00,  9.74362940e-02, -1.18630278e+00,
      

In [10]:
initializer = tf.contrib.layers.xavier_initializer()

w0 = tf.Variable(initializer([4, 16]))
w0


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



<tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[-0.3662327 , -0.45429263, -0.41040814, -0.09292522, -0.00907153,
        -0.04091614,  0.08846319,  0.10985076, -0.14018631,  0.12326115,
         0.19905776,  0.49585032,  0.31554776, -0.5386052 , -0.4242782 ,
        -0.5007749 ],
       [-0.21238604, -0.11177444,  0.27591282, -0.36575422,  0.38676155,
        -0.5299665 ,  0.06196296,  0.27245528, -0.37738365,  0.4821391 ,
        -0.1195986 ,  0.09631956, -0.07164028,  0.45029354,  0.40812415,
        -0.03217477],
       [-0.30776513,  0.23881483,  0.5274787 ,  0.06357116,  0.1642102 ,
         0.08247054, -0.14403015, -0.06752026, -0.14245918, -0.16151446,
         0.15997761, -0.46035632, -0.45467746, -0.21557996,  0.13209265,
         0.4575591 ],
       [ 0.54003453, -0.1657741 , -0.1101822 ,  0.24372214, -0.0425145 ,
        -0.07681349, -0.23531532, -0.06307375, -0.5172264 , -0.39203033,
         0.3350358 , -0.3822047 ,  0.00186205, -0.25556627, -0.382368

In [11]:
b0 = tf.Variable(initializer([16]))
b0

<tf.Variable 'Variable:0' shape=(16,) dtype=float32, numpy=
array([ 0.22394344, -0.06055328, -0.18736672,  0.35407868,  0.36210015,
        0.1366156 , -0.38991475, -0.11517808,  0.22367188,  0.02182353,
       -0.3304779 ,  0.28974226, -0.00696188, -0.23978472,  0.03856134,
       -0.35746676], dtype=float32)>

In [12]:
hypothesis0 = tf.sigmoid((tf.matmul(X_train, w0) + b0))
hypothesis0

Instructions for updating:
Colocations handled automatically by placer.


<tf.Tensor: id=36, shape=(120, 16), dtype=float32, numpy=
array([[0.52548057, 0.45381525, 0.4192449 , ..., 0.31791067, 0.42042214,
        0.3763851 ],
       [0.49239865, 0.5175473 , 0.4672303 , ..., 0.7669315 , 0.74551576,
        0.49892816],
       [0.5337195 , 0.5242142 , 0.4766953 , ..., 0.23283449, 0.37783253,
        0.4624889 ],
       ...,
       [0.6575045 , 0.56380135, 0.42116362, ..., 0.3362659 , 0.4123988 ,
        0.4669642 ],
       [0.6014291 , 0.40852085, 0.5508338 , ..., 0.26420298, 0.38415942,
        0.2933889 ],
       [0.6443365 , 0.64681673, 0.47335315, ..., 0.77307653, 0.732694  ,
        0.613299  ]], dtype=float32)>

In [13]:
w1 = tf.Variable(initializer([16, 3]))
w1

<tf.Variable 'Variable:0' shape=(16, 3) dtype=float32, numpy=
array([[-0.04185474,  0.20794636, -0.34811562],
       [-0.5600708 ,  0.47719127, -0.21609285],
       [ 0.16222382,  0.56105334, -0.07433581],
       [-0.20685819,  0.19006222, -0.33057138],
       [ 0.37814784, -0.31504193, -0.4713824 ],
       [ 0.43900675,  0.15807414, -0.4251148 ],
       [-0.52148706,  0.05162197,  0.47616023],
       [ 0.03973758,  0.16853452,  0.31600595],
       [-0.40592515,  0.27956426,  0.21270972],
       [-0.2199831 , -0.28711575,  0.40673625],
       [-0.22993362,  0.461253  , -0.09069741],
       [ 0.42528105,  0.52131194, -0.47767287],
       [ 0.29374236,  0.4998204 , -0.38646796],
       [-0.03850108,  0.2704535 , -0.00377136],
       [ 0.0490095 , -0.19507882, -0.21777028],
       [ 0.5075168 ,  0.19338238, -0.14769009]], dtype=float32)>

In [14]:
b1 = tf.Variable(initializer([3]))
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.518245  , -0.59863377, -0.13884902], dtype=float32)>

In [15]:
hypothesis1 = tf.nn.softmax((tf.matmul(hypothesis0, w1) + b1))
hypothesis1

<tf.Tensor: id=72, shape=(120, 3), dtype=float32, numpy=
array([[0.3915185 , 0.5456829 , 0.06279858],
       [0.3794137 , 0.5476736 , 0.07291271],
       [0.3746634 , 0.56795734, 0.05737931],
       [0.4190197 , 0.51222014, 0.06876019],
       [0.34368432, 0.5953344 , 0.06098131],
       [0.35317436, 0.59061134, 0.05621432],
       [0.34118828, 0.5965514 , 0.0622603 ],
       [0.39037025, 0.5467372 , 0.06289257],
       [0.34660533, 0.5901584 , 0.06323624],
       [0.4007129 , 0.5362035 , 0.06308361],
       [0.34113672, 0.5982518 , 0.06061144],
       [0.3474022 , 0.59029657, 0.06230116],
       [0.38297787, 0.5590859 , 0.05793626],
       [0.42757934, 0.50371134, 0.06870937],
       [0.3418699 , 0.59686893, 0.06126116],
       [0.34933254, 0.58754647, 0.06312104],
       [0.41227466, 0.50339615, 0.08432911],
       [0.41426373, 0.5211285 , 0.06460781],
       [0.41699538, 0.51759994, 0.06540465],
       [0.34123462, 0.59854746, 0.06021785],
       [0.42618358, 0.51058537, 0.06323105]

In [16]:
pred = tf.argmax(hypothesis1, 1)
pred

<tf.Tensor: id=75, shape=(120,), dtype=int64, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)>

In [17]:
optimizer = tf.train.AdamOptimizer(0.01)

In [18]:
hypothesis0 = tf.sigmoid((tf.matmul(X_train, w0) + b0))
hypothesis1 = tf.nn.softmax((tf.matmul(hypothesis0, w1) + b1))

## tensor로부터 shape 가져오는 방법

In [19]:
hypothesis1.get_shape().as_list()[0]

120

In [20]:
len(hypothesis1)

120

In [21]:
for epoch in range(1001):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid((tf.matmul(X_train, w0) + b0))
        hypothesis1 = tf.nn.softmax((tf.matmul(hypothesis0, w1) + b1))
        
        cost = -tf.reduce_sum(y_train_onehot * tf.log(hypothesis1)) /  hypothesis1.get_shape().as_list()[0]
        
        grads = tape.gradient(cost, [w0, w1, b0, b1])
        
        optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))
        
        if epoch % 100 == 0:
            print("=" * 50)
            print(f"epoch : {epoch}, cost : {cost.numpy()}")

epoch : 0, cost : 1.4794293642044067
epoch : 100, cost : 0.2640448808670044
epoch : 200, cost : 0.14154182374477386
epoch : 300, cost : 0.08798494935035706
epoch : 400, cost : 0.06918991357088089
epoch : 500, cost : 0.0604599304497242
epoch : 600, cost : 0.05572155863046646
epoch : 700, cost : 0.052924059331417084
epoch : 800, cost : 0.05112423747777939
epoch : 900, cost : 0.0498068667948246
epoch : 1000, cost : 0.048700880259275436


## 학습을 시킬 때 데이터 표준화를 했으면 테스트할 때도 해야한다

In [22]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.47877893,  0.7719963 ,  0.94008905,  1.4371171 ],
       [-0.12094571, -0.5771232 ,  0.21263911,  0.14532612],
       [ 0.95855874, -0.1274167 ,  0.38051227,  0.27450526],
       [ 1.0785035 ,  0.09743629,  0.38051227,  0.27450526],
       [ 0.35883412, -0.1274167 ,  0.49242753,  0.27450526],
       [ 1.0785035 ,  0.09743629,  0.54838514,  0.40368438],
       [-0.84061515,  0.9968493 , -1.2982183 , -1.1464648 ],
       [ 0.5987243 , -0.8019762 ,  0.6603007 ,  0.7912216 ],
       [-1.4403398 ,  0.7719963 , -1.2982183 , -1.1464648 ],
       [-0.48078015,  1.4465559 , -1.2422606 , -1.275644  ],
       [-0.96055996, -0.1274167 , -1.1863028 , -1.275644  ],
       [ 0.5987243 ,  0.5471428 ,  0.54838514,  0.5328635 ],
       [-0.24089052, -1.2516828 ,  0.10072386, -0.11303199],
       [-0.96055996, -1.7013892 , -0.2350223 , -0.24221112],
       [-1.0805048 ,  0.09743629, -1.2422606 , -1.4048231 ],
       [ 0.23888929,  0.7719963 ,  0.43646988,  0.5328635 ],
       [ 0.5987243 , -1.

In [23]:
hypothesis0 = tf.sigmoid((tf.matmul(X_test, w0) + b0))
hypothesis1 = tf.nn.softmax((tf.matmul(hypothesis0, w1) + b1))
hypothesis1

<tf.Tensor: id=84280, shape=(30, 3), dtype=float32, numpy=
array([[6.76876425e-07, 3.45045235e-03, 9.96548951e-01],
       [7.17504707e-04, 9.99118030e-01, 1.64447294e-04],
       [2.07575722e-04, 9.99553263e-01, 2.39115136e-04],
       [3.07603856e-04, 9.99583066e-01, 1.09375884e-04],
       [4.02039004e-04, 9.97990847e-01, 1.60712027e-03],
       [1.65446196e-04, 9.97886837e-01, 1.94764603e-03],
       [9.99426007e-01, 5.74060774e-04, 2.35565040e-12],
       [4.69250017e-06, 9.46527347e-02, 9.05342519e-01],
       [9.99464691e-01, 5.35367057e-04, 2.21901208e-12],
       [9.99480903e-01, 5.19155932e-04, 2.02800277e-12],
       [9.98711467e-01, 1.28853833e-03, 6.83906404e-12],
       [8.73978424e-04, 9.95962560e-01, 3.16355820e-03],
       [3.33911419e-04, 9.99592006e-01, 7.41390540e-05],
       [1.29511510e-03, 9.98688519e-01, 1.63923487e-05],
       [9.99200523e-01, 7.99470872e-04, 3.60391079e-12],
       [6.09828671e-03, 9.93261039e-01, 6.40753424e-04],
       [3.88234985e-05, 9.975

In [24]:
pred = tf.argmax(hypothesis1, 1)
pred

<tf.Tensor: id=84283, shape=(30,), dtype=int64, numpy=
array([2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 1,
       2, 0, 2, 2, 1, 1, 2, 2], dtype=int64)>

In [25]:
tf.reduce_sum(tf.cast(tf.equal(y_test.reshape(-1), pred), dtype="float32"))/len(y_test)

<tf.Tensor: id=84291, shape=(), dtype=float32, numpy=1.0>