In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


c:\library\python\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, defaultdict
Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type

In [2]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X = data.data
X = np.array(X, dtype="float32")
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = data["target"]
y = np.array(y, dtype="float32")
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [5]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y)

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [6]:
y = enc.transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.5011264 , -1.2766423 ,  0.61923707,  0.35722736],
       [ 0.5011264 ,  0.80925256,  1.0181321 ,  1.5479844 ],
       [-0.09545187, -0.81311005,  0.04938684, -0.03969155],
       [ 0.9783886 , -0.11781196,  0.79019195,  1.4156779 ],
       [-1.2886084 , -0.11781196, -1.3752389 , -1.4950612 ],
       [-0.09545187, -0.58134425,  0.733207  ,  1.5479844 ],
       [-1.6465557 , -1.7401747 , -1.4322238 , -1.2304485 ],
       [-0.33408353, -0.11781196,  0.39129692,  0.35722736],
       [ 2.1715453 ,  1.7363166 ,  1.6449673 ,  1.2833717 ],
       [ 0.5011264 ,  0.57748616,  0.50526685,  0.48953372],
       [-0.93066186,  1.5045507 , -1.3182538 , -1.0981423 ],
       [-0.09545187, -0.81311005,  0.733207  ,  0.8864526 ],
       [-0.09545187,  2.199849  , -1.4892088 , -1.3627548 ],
       [ 0.14317922, -1.9719405 ,  0.10637181, -0.30430427],
       [ 0.620442  ,  0.1139539 ,  0.9611471 ,  0.7541463 ],
       [ 0.14317922, -0.11781196,  0.5622521 ,  0.7541463 ],
       [ 2.1715453 , -0.

In [10]:
model = Sequential()

In [11]:
model.add(Dense(16, input_dim=4, activation="sigmoid"))

Instructions for updating:
Colocations handled automatically by placer.


In [12]:
model.add(Dense(3, input_dim=16, activation="softmax"))

In [13]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [14]:
optimizers = Adam(0.001)
model.compile(loss="categorical_crossentropy", optimizer=optimizers, metrics=["acc"])

In [15]:
model.fit(X_train, y_train, epochs=1000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
120/120 [==============================] - 0s 2ms/step - loss: 1.1496 - acc: 0.5917
Epoch 2/1000
120/120 [==============================] - 0s 67us/step - loss: 1.1368 - acc: 0.5417
Epoch 3/1000
120/120 [==============================] - 0s 66us/step - loss: 1.1243 - acc: 0.5500
Epoch 4/1000
120/120 [==============================] - 0s 91us/step - loss: 1.1130 - acc: 0.5333
Epoch 5/1000
120/120 [==============================] - 0s 58us/step - loss: 1.0988 - acc: 0.5167
Epoch 6/1000
120/120 [==============================] - 0s 108us/step - loss: 1.0881 - acc: 0.4750
Epoch 7/1000
120/120 [==============================] - 0s 91us/step - loss: 1.0754 - acc: 0.4750
Epoch 8/1000
120/120 [==============================] - 0s 75us/step - loss: 1.0656 - acc: 0.4583
Epoch 9/1000
120/120 [==============================] - 0s 66us/step - loss: 1.0554 - acc: 0.4583
Epoch 10/1000
120/120 [==============================] - 0s 100us/step

120/120 [==============================] - 0s 58us/step - loss: 0.5617 - acc: 0.8417
Epoch 82/1000
120/120 [==============================] - 0s 100us/step - loss: 0.5576 - acc: 0.8417
Epoch 83/1000
120/120 [==============================] - 0s 75us/step - loss: 0.5535 - acc: 0.8333
Epoch 84/1000
120/120 [==============================] - 0s 108us/step - loss: 0.5497 - acc: 0.8333
Epoch 85/1000
120/120 [==============================] - 0s 83us/step - loss: 0.5456 - acc: 0.8500
Epoch 86/1000
120/120 [==============================] - 0s 75us/step - loss: 0.5417 - acc: 0.8500
Epoch 87/1000
120/120 [==============================] - 0s 83us/step - loss: 0.5380 - acc: 0.8500
Epoch 88/1000
120/120 [==============================] - 0s 67us/step - loss: 0.5342 - acc: 0.8500
Epoch 89/1000
120/120 [==============================] - 0s 58us/step - loss: 0.5306 - acc: 0.8500
Epoch 90/1000
120/120 [==============================] - 0s 83us/step - loss: 0.5269 - acc: 0.8500
Epoch 91/1000
120/120 

120/120 [==============================] - 0s 58us/step - loss: 0.3674 - acc: 0.8833
Epoch 163/1000
120/120 [==============================] - 0s 83us/step - loss: 0.3659 - acc: 0.8833
Epoch 164/1000
120/120 [==============================] - 0s 58us/step - loss: 0.3646 - acc: 0.8833
Epoch 165/1000
120/120 [==============================] - 0s 91us/step - loss: 0.3631 - acc: 0.8833
Epoch 166/1000
120/120 [==============================] - 0s 83us/step - loss: 0.3619 - acc: 0.8917
Epoch 167/1000
120/120 [==============================] - 0s 58us/step - loss: 0.3603 - acc: 0.8917
Epoch 168/1000
120/120 [==============================] - 0s 83us/step - loss: 0.3588 - acc: 0.9000
Epoch 169/1000
120/120 [==============================] - 0s 58us/step - loss: 0.3575 - acc: 0.9000
Epoch 170/1000
120/120 [==============================] - 0s 83us/step - loss: 0.3561 - acc: 0.9000
Epoch 171/1000
120/120 [==============================] - 0s 83us/step - loss: 0.3547 - acc: 0.9000
Epoch 172/1000


120/120 [==============================] - 0s 58us/step - loss: 0.2736 - acc: 0.9167
Epoch 244/1000
120/120 [==============================] - 0s 75us/step - loss: 0.2727 - acc: 0.9250
Epoch 245/1000
120/120 [==============================] - 0s 83us/step - loss: 0.2717 - acc: 0.9250
Epoch 246/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2708 - acc: 0.9250
Epoch 247/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2700 - acc: 0.9250
Epoch 248/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2688 - acc: 0.9250
Epoch 249/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2679 - acc: 0.9250
Epoch 250/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2669 - acc: 0.9167
Epoch 251/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2661 - acc: 0.9167
Epoch 252/1000
120/120 [==============================] - 0s 58us/step - loss: 0.2652 - acc: 0.9250
Epoch 253/1000


120/120 [==============================] - 0s 66us/step - loss: 0.2055 - acc: 0.9583
Epoch 325/1000
120/120 [==============================] - 0s 83us/step - loss: 0.2048 - acc: 0.9583
Epoch 326/1000
120/120 [==============================] - 0s 75us/step - loss: 0.2041 - acc: 0.9583
Epoch 327/1000
120/120 [==============================] - 0s 50us/step - loss: 0.2033 - acc: 0.9583
Epoch 328/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2027 - acc: 0.9583
Epoch 329/1000
120/120 [==============================] - 0s 83us/step - loss: 0.2019 - acc: 0.9583
Epoch 330/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2013 - acc: 0.9583
Epoch 331/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2006 - acc: 0.9583
Epoch 332/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1999 - acc: 0.9583
Epoch 333/1000
120/120 [==============================] - 0s 91us/step - loss: 0.1992 - acc: 0.9583
Epoch 334/1000


120/120 [==============================] - 0s 58us/step - loss: 0.1574 - acc: 0.9583
Epoch 406/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1569 - acc: 0.9583
Epoch 407/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1565 - acc: 0.9583
Epoch 408/1000
120/120 [==============================] - 0s 66us/step - loss: 0.1559 - acc: 0.9583
Epoch 409/1000
120/120 [==============================] - 0s 67us/step - loss: 0.1555 - acc: 0.9583
Epoch 410/1000
120/120 [==============================] - 0s 116us/step - loss: 0.1550 - acc: 0.9583
Epoch 411/1000
120/120 [==============================] - 0s 91us/step - loss: 0.1546 - acc: 0.9583
Epoch 412/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1541 - acc: 0.9583
Epoch 413/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1537 - acc: 0.9583
Epoch 414/1000
120/120 [==============================] - 0s 91us/step - loss: 0.1531 - acc: 0.9583
Epoch 415/1000

120/120 [==============================] - 0s 100us/step - loss: 0.1259 - acc: 0.9667
Epoch 488/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1256 - acc: 0.9667
Epoch 489/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1253 - acc: 0.9667
Epoch 490/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1250 - acc: 0.9667
Epoch 491/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1247 - acc: 0.9667
Epoch 492/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1244 - acc: 0.9667
Epoch 493/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1241 - acc: 0.9667
Epoch 494/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1238 - acc: 0.9667
Epoch 495/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1235 - acc: 0.9667
Epoch 496/1000
120/120 [==============================] - 0s 50us/step - loss: 0.1232 - acc: 0.9667
Epoch 497/1000

120/120 [==============================] - 0s 141us/step - loss: 0.1060 - acc: 0.9667
Epoch 569/1000
120/120 [==============================] - 0s 108us/step - loss: 0.1058 - acc: 0.9667
Epoch 570/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1057 - acc: 0.9667
Epoch 571/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1055 - acc: 0.9667
Epoch 572/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1053 - acc: 0.9667
Epoch 573/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1051 - acc: 0.9667
Epoch 574/1000
120/120 [==============================] - 0s 75us/step - loss: 0.1049 - acc: 0.9667
Epoch 575/1000
120/120 [==============================] - 0s 58us/step - loss: 0.1047 - acc: 0.9667
Epoch 576/1000
120/120 [==============================] - ETA: 0s - loss: 0.1054 - acc: 0.968 - 0s 66us/step - loss: 0.1045 - acc: 0.9667
Epoch 577/1000
120/120 [==============================] - 0s 66us/step - lo

120/120 [==============================] - 0s 66us/step - loss: 0.0929 - acc: 0.9667
Epoch 650/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0927 - acc: 0.9667
Epoch 651/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0926 - acc: 0.9667
Epoch 652/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0924 - acc: 0.9667
Epoch 653/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0923 - acc: 0.9667
Epoch 654/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0922 - acc: 0.9667
Epoch 655/1000
120/120 [==============================] - 0s 50us/step - loss: 0.0920 - acc: 0.9667
Epoch 656/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0919 - acc: 0.9667
Epoch 657/1000
120/120 [==============================] - 0s 67us/step - loss: 0.0919 - acc: 0.9667
Epoch 658/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0917 - acc: 0.9667
Epoch 659/1000


120/120 [==============================] - 0s 58us/step - loss: 0.0838 - acc: 0.9667
Epoch 732/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0836 - acc: 0.9667
Epoch 733/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0836 - acc: 0.9667
Epoch 734/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0834 - acc: 0.9667
Epoch 735/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0834 - acc: 0.9667
Epoch 736/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0832 - acc: 0.9667
Epoch 737/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0832 - acc: 0.9667
Epoch 738/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0831 - acc: 0.9667
Epoch 739/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0830 - acc: 0.9667
Epoch 740/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0829 - acc: 0.9667
Epoch 741/1000


120/120 [==============================] - 0s 42us/step - loss: 0.0771 - acc: 0.9667
Epoch 814/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0771 - acc: 0.9667
Epoch 815/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0770 - acc: 0.9667
Epoch 816/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0769 - acc: 0.9667
Epoch 817/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0768 - acc: 0.9667
Epoch 818/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0769 - acc: 0.9667
Epoch 819/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0767 - acc: 0.9667
Epoch 820/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0767 - acc: 0.9667
Epoch 821/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0766 - acc: 0.9667
Epoch 822/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0765 - acc: 0.9667
Epoch 823/1000


Epoch 895/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0722 - acc: 0.9667
Epoch 896/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0722 - acc: 0.9667
Epoch 897/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0723 - acc: 0.9667
Epoch 898/1000
120/120 [==============================] - 0s 50us/step - loss: 0.0721 - acc: 0.9667
Epoch 899/1000
120/120 [==============================] - 0s 50us/step - loss: 0.0720 - acc: 0.9667
Epoch 900/1000
120/120 [==============================] - 0s 75us/step - loss: 0.0720 - acc: 0.9667
Epoch 901/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0720 - acc: 0.9667
Epoch 902/1000
120/120 [==============================] - 0s 67us/step - loss: 0.0719 - acc: 0.9667
Epoch 903/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0718 - acc: 0.9667
Epoch 904/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0718 - acc: 0.9667


120/120 [==============================] - 0s 75us/step - loss: 0.0686 - acc: 0.9667
Epoch 976/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0685 - acc: 0.9667
Epoch 977/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0685 - acc: 0.9667
Epoch 978/1000
120/120 [==============================] - 0s 66us/step - loss: 0.0684 - acc: 0.9667
Epoch 979/1000
120/120 [==============================] - 0s 108us/step - loss: 0.0684 - acc: 0.9667
Epoch 980/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0683 - acc: 0.9667
Epoch 981/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0683 - acc: 0.9667
Epoch 982/1000
120/120 [==============================] - 0s 91us/step - loss: 0.0683 - acc: 0.9667
Epoch 983/1000
120/120 [==============================] - 0s 83us/step - loss: 0.0683 - acc: 0.9667
Epoch 984/1000
120/120 [==============================] - 0s 100us/step - loss: 0.0682 - acc: 0.9667
Epoch 985/10

In [16]:
X_test = scaler.transform(X_test)
p = model.predict(X_test)

In [17]:
p1 = np.argmax(p, 1)
p1

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 0,
       2, 2, 2, 0, 2, 1, 1, 1], dtype=int64)

In [22]:
target = np.argmax(y_test, 1)
target

array([0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 2, 0,
       2, 2, 2, 0, 2, 1, 1, 1], dtype=int64)

In [24]:
pred2 = (p1 == target)
pred2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [26]:
np.sum(pred2) / len(pred2)

1.0