In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf

c:\library\python\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, defaultdict
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synon

In [2]:
tf.enable_eager_execution()

In [3]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

## 데이터 로드
## y의 경우 reshape를 해주어야한다

In [4]:
X = data["data"]
X = np.array(X, dtype="float32")
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [5]:
y = data["target"]
y = np.array(y, dtype="float32")
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [6]:
X.shape

(569, 30)

## 데이터 분할

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## 데이터 표준화

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
X_train = scaler.transform(X_train)
X_train

array([[-1.2419883 , -0.8430437 , -1.2516576 , ..., -0.9673552 ,
        -0.07385019, -0.10366599],
       [-0.3853996 ,  0.4907649 , -0.40848032, ..., -1.0274909 ,
        -1.1345507 , -0.8588474 ],
       [ 1.3769999 , -0.09016222,  1.2918456 , ...,  0.12645894,
        -0.07385019, -1.0499591 ],
       ...,
       [-0.78993124,  0.45590937, -0.8004836 , ..., -0.48144054,
        -0.09307724,  0.27682063],
       [-1.2586788 ,  0.00975732, -1.2701484 , ..., -1.1719098 ,
        -0.53690517, -0.25134325],
       [ 0.3501121 ,  0.80446565,  0.33854535, ...,  0.52840173,
        -0.530496  , -0.88375   ]], dtype=float32)

## weight 값을 초기화 하기 위한 xavier_initializer() 초기화

In [10]:
initializer = tf.contrib.layers.xavier_initializer()


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



## xavier 방식을 통한 weight 값들 초기화

In [11]:
w0 = tf.Variable(initializer([30, 30]))
w0

<tf.Variable 'Variable:0' shape=(30, 30) dtype=float32, numpy=
array([[-0.07945381, -0.25427008, -0.0158101 ,  0.0291903 , -0.1458343 ,
         0.19697866,  0.16021061, -0.28989816, -0.23500858,  0.28895512,
         0.27960065,  0.20342633,  0.2312558 ,  0.13165236, -0.01881707,
         0.31472853,  0.17049557,  0.26115337,  0.06981117, -0.03569821,
         0.18034124,  0.1433278 , -0.27631155,  0.05771139,  0.16935754,
         0.270739  , -0.27178562, -0.02006114,  0.3083531 ,  0.11005324],
       [ 0.17304051, -0.10694396,  0.28690413,  0.20988509,  0.08334854,
        -0.14945588, -0.02948704,  0.10519367, -0.30984908, -0.31571922,
        -0.13212341,  0.09706938, -0.24613696,  0.23456004,  0.18442228,
        -0.2582445 ,  0.31267962,  0.00766951, -0.01651171, -0.00532836,
        -0.04980031, -0.134041  , -0.02061129,  0.28679487, -0.10946561,
         0.01712331,  0.00871417, -0.08643807, -0.27034074,  0.25334695],
       [-0.21862331, -0.02688813, -0.314433  ,  0.0880188 ,

In [12]:
b0 = tf.Variable(initializer([30]))
b0

<tf.Variable 'Variable:0' shape=(30,) dtype=float32, numpy=
array([ 0.12382933,  0.07901117,  0.18715903, -0.09648372, -0.01997188,
       -0.08259219,  0.24359307,  0.1590082 ,  0.18060642,  0.01526508,
       -0.18565258, -0.08274637, -0.00540164, -0.05931267, -0.07525064,
       -0.08939293,  0.3048562 ,  0.14026639,  0.11396825,  0.28877202,
        0.2275072 , -0.11885834,  0.10187429, -0.20368259, -0.04003069,
       -0.07476638,  0.27228728,  0.1625602 ,  0.00644383, -0.042564  ],
      dtype=float32)>

In [13]:
w1 = tf.Variable(initializer([30, 10]))
w1

<tf.Variable 'Variable:0' shape=(30, 10) dtype=float32, numpy=
array([[-0.18572943,  0.30476737,  0.29936677,  0.06646496, -0.2212834 ,
         0.10124883,  0.31700677,  0.2622648 ,  0.21541744, -0.29196697],
       [ 0.3076653 ,  0.10221323,  0.3274567 , -0.32190287,  0.02367705,
         0.08954474, -0.0131287 , -0.1803819 ,  0.20476913,  0.29842478],
       [-0.35775822, -0.34639183, -0.17423478, -0.27732208, -0.33132756,
         0.3435657 , -0.18287301,  0.35317683, -0.08141744,  0.27755737],
       [ 0.22030294,  0.38317752,  0.3396542 ,  0.15324557,  0.09349069,
        -0.131527  , -0.05412209,  0.3350106 ,  0.06462252,  0.24614573],
       [-0.01989225, -0.24250387,  0.10879821, -0.3482893 ,  0.29476124,
         0.1690396 ,  0.09725478, -0.38622472,  0.01245248,  0.2873168 ],
       [ 0.021485  , -0.20588568,  0.11407906, -0.15152721,  0.33347464,
        -0.24889964,  0.28584248,  0.12643874,  0.04715252,  0.11341703],
       [-0.33251992,  0.32263702, -0.3704577 , -0.21286

In [14]:
b1 = tf.Variable(initializer([10]))
b1

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.39916116, -0.37575656, -0.42639816,  0.22062963,  0.04688084,
       -0.14114311, -0.21939114, -0.18652129,  0.4144057 , -0.12350485],
      dtype=float32)>

In [15]:
w2 = tf.Variable(initializer([10, 1]))
w2

<tf.Variable 'Variable:0' shape=(10, 1) dtype=float32, numpy=
array([[ 0.5173914 ],
       [ 0.3605166 ],
       [-0.5656107 ],
       [-0.72406286],
       [ 0.07728636],
       [-0.46490487],
       [ 0.2880512 ],
       [ 0.31703   ],
       [ 0.4694075 ],
       [-0.3153467 ]], dtype=float32)>

In [16]:
b2 = tf.Variable(initializer([1]))
b2

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.75419486], dtype=float32)>

## 학습 수행

In [17]:
lr = 0.01
optimizer = tf.train.AdamOptimizer(lr)
for epoch in range(1001):
    with tf.GradientTape() as tape:
        hypothesis1 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
        hypothesis2 = tf.sigmoid(tf.matmul(hypothesis1, w1) + b1)
        pred = tf.sigmoid(tf.matmul(hypothesis2, w2) + b2)
        
        cost =  -tf.reduce_mean(y_train * tf.log(pred) + (1-y_train) * tf.log(1-pred))
        grads = tape.gradient(cost, [w0, w1, w2, b0, b1, b2])
        
        optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, w2,  b0, b1, b2]))
    
    if epoch % 100 == 0:
        print("=" * 50)
        print(f"step: {epoch}, cost : {cost.numpy()}")

Instructions for updating:
Colocations handled automatically by placer.
step: 0, cost : 0.665410578250885
step: 100, cost : 0.05362467095255852
step: 200, cost : 0.029094940051436424
step: 300, cost : 0.018425986170768738
step: 400, cost : 0.0026923895347863436
step: 500, cost : 0.0014747817767784
step: 600, cost : 0.0009856660617515445
step: 700, cost : 0.0007209399482235312
step: 800, cost : 0.0005564090679399669
step: 900, cost : 0.00044525970588438213
step: 1000, cost : 0.00036578302388079464


## test 값들 전처리

In [18]:
X_test = scaler.transform(X_test)
X_test

array([[ 1.5014713 , -0.11107563,  1.4849713 , ...,  1.4382259 ,
         0.60711294,  0.37932593],
       [-0.47309536,  1.1019005 , -0.3283536 , ...,  1.6719135 ,
         2.3696063 ,  7.178855  ],
       [-0.27224404, -0.25049824, -0.31561565, ..., -0.14306077,
        -1.0448236 , -0.8275744 ],
       ...,
       [-0.6201979 ,  0.33972394, -0.5790057 , ...,  0.0283102 ,
        -0.6763024 ,  0.94223714],
       [-0.8238779 ,  3.3721638 , -0.8699267 , ..., -1.3033981 ,
         0.03830845, -0.6063482 ],
       [-0.1194839 , -0.14360741, -0.13276264, ...,  0.22928153,
        -0.06103185,  0.39206675]], dtype=float32)

## test 값들에 대한 예측

In [28]:
hypothesis0 = tf.sigmoid(tf.matmul(X_test, w0) + b0)
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)
predict

<tf.Tensor: id=107410, shape=(114, 1), dtype=float32, numpy=
array([[3.2851100e-04],
       [3.3813715e-04],
       [9.9989903e-01],
       [9.9583149e-01],
       [9.9992085e-01],
       [9.9986768e-01],
       [9.9991125e-01],
       [3.2842159e-04],
       [9.9985981e-01],
       [3.2970309e-04],
       [9.9988353e-01],
       [3.2877922e-04],
       [3.2940507e-04],
       [9.9990743e-01],
       [9.9862003e-01],
       [9.9992114e-01],
       [9.9991798e-01],
       [3.2848120e-04],
       [9.9955952e-01],
       [9.9991977e-01],
       [9.9988234e-01],
       [9.1009295e-01],
       [9.9990642e-01],
       [3.2860041e-04],
       [9.9991930e-01],
       [9.9991584e-01],
       [9.9992126e-01],
       [9.9985325e-01],
       [9.9992108e-01],
       [9.9980938e-01],
       [9.9991030e-01],
       [3.2868981e-04],
       [9.9991989e-01],
       [3.4922361e-04],
       [3.2866001e-04],
       [9.9880993e-01],
       [9.9991381e-01],
       [3.2877922e-04],
       [1.5123129e-02],
   

In [29]:
pred01 = tf.cast(predict>0.5, dtype="float32")
pred01

<tf.Tensor: id=107414, shape=(114, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
   

In [31]:
ac01 = tf.equal(pred01, y_test)
ac01

<tf.Tensor: id=107417, shape=(114, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]

## 정확도 계산

In [32]:
ac01 = tf.cast(ac01, dtype="float32")
tf.reduce_mean(ac01)

<tf.Tensor: id=107421, shape=(), dtype=float32, numpy=0.99122804>

## train 데이터에 대한 정확도 계산

In [35]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
predict = tf.sigmoid(tf.matmul(hypothesis1, w2) + b2)
pred01 = tf.cast(predict>0.5, dtype="float32")
ac01 = tf.equal(pred01, y_train)
ac01 = tf.cast(ac01, dtype="float32")
tf.reduce_mean(ac01)

<tf.Tensor: id=107491, shape=(), dtype=float32, numpy=1.0>