In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

c:\library\python\lib\site-packages\sklearn\feature_extraction\text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, defaultdict
Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type

## 데이터 로드

In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

## 데이터 X와 y로 나누기

In [3]:
X = data['data']
X = np.array(X, dtype="float32")
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [4]:
y = data['target']
y = np.array(y, dtype="float32")
y = y.reshape(-1, 1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

## 훈련용, 테스트용으로 나누기

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## 훈련용 데이터 표준화

In [6]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train

array([[-0.6191706 ,  0.467197  , -0.60260576, ..., -0.39791787,
        -0.9605857 ,  0.83494985],
       [-0.6247544 , -0.46029684, -0.6548661 , ..., -0.33921114,
         0.34604138, -0.74773073],
       [ 2.546931  ,  1.7015812 ,  2.5034394 , ...,  2.1881902 ,
         0.3493244 ,  0.1497486 ],
       ...,
       [ 0.72656244,  0.16257903,  0.62368846, ..., -0.39987472,
         2.9330323 , -0.41668454],
       [ 1.6199948 ,  0.17621852,  1.5716664 , ...,  0.71299475,
        -0.56006163,  0.3964213 ],
       [-0.17245418, -1.2332077 , -0.1776363 , ...,  0.2945208 ,
         0.5528694 ,  0.49852946]], dtype=float32)

## 모델 정의

In [7]:
model = Sequential()

In [9]:
model.add(Dense(30, input_dim = 30, activation="sigmoid"))

Instructions for updating:
Colocations handled automatically by placer.


In [10]:
model.add(Dense(10, input_dim = 30, activation="sigmoid"))

In [11]:
model.add(Dense(1, input_dim = 10, activation="sigmoid"))

## 모델 확인

In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 30)                930       
_________________________________________________________________
dense_3 (Dense)              (None, 10)                310       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 1,251
Trainable params: 1,251
Non-trainable params: 0
_________________________________________________________________


## 학습률 정의

In [15]:
lr = 0.01

## 학습 파라미터 초기화

In [18]:
model.compile(loss="binary_crossentropy", optimizer = Adam(lr), metrics=['acc'])

## 학습 시작

In [19]:
model.fit(X_train, y_train, epochs=1000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
455/455 [==============================] - 0s 728us/step - loss: 0.5728 - acc: 0.7231
Epoch 2/1000
455/455 [==============================] - 0s 57us/step - loss: 0.3327 - acc: 0.9209
Epoch 3/1000
455/455 [==============================] - 0s 68us/step - loss: 0.1822 - acc: 0.9670
Epoch 4/1000
455/455 [==============================] - 0s 68us/step - loss: 0.1168 - acc: 0.9802
Epoch 5/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0898 - acc: 0.9846
Epoch 6/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0777 - acc: 0.9824
Epoch 7/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0691 - acc: 0.9868
Epoch 8/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0636 - acc: 0.9868
Epoch 9/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0612 - acc: 0.9846
Epoch 10/1000
455/455 [==============================] - 0s 64us/step

455/455 [==============================] - 0s 55us/step - loss: 0.0024 - acc: 1.0000
Epoch 82/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0019 - acc: 1.0000
Epoch 83/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0020 - acc: 1.0000
Epoch 84/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0016 - acc: 1.0000
Epoch 85/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0015 - acc: 1.0000
Epoch 86/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0016 - acc: 1.0000
Epoch 87/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0014 - acc: 1.0000
Epoch 88/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0014 - acc: 1.0000
Epoch 89/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0017 - acc: 1.0000
Epoch 90/1000
455/455 [==============================] - 0s 105us/step - loss: 0.0013 - acc: 1.0000
Epoch 91/1000
455/455 [

455/455 [==============================] - 0s 46us/step - loss: 2.8318e-04 - acc: 1.0000
Epoch 161/1000
455/455 [==============================] - 0s 39us/step - loss: 2.7916e-04 - acc: 1.0000
Epoch 162/1000
455/455 [==============================] - 0s 48us/step - loss: 2.7653e-04 - acc: 1.0000
Epoch 163/1000
455/455 [==============================] - 0s 50us/step - loss: 2.7755e-04 - acc: 1.0000
Epoch 164/1000
455/455 [==============================] - 0s 44us/step - loss: 2.7210e-04 - acc: 1.0000
Epoch 165/1000
455/455 [==============================] - 0s 44us/step - loss: 2.6707e-04 - acc: 1.0000
Epoch 166/1000
455/455 [==============================] - 0s 42us/step - loss: 2.5986e-04 - acc: 1.0000
Epoch 167/1000
455/455 [==============================] - 0s 44us/step - loss: 2.5372e-04 - acc: 1.0000
Epoch 168/1000
455/455 [==============================] - 0s 42us/step - loss: 2.4949e-04 - acc: 1.0000
Epoch 169/1000
455/455 [==============================] - 0s 46us/step - loss: 

455/455 [==============================] - 0s 59us/step - loss: 1.0350e-04 - acc: 1.0000
Epoch 239/1000
455/455 [==============================] - 0s 50us/step - loss: 1.0252e-04 - acc: 1.0000
Epoch 240/1000
455/455 [==============================] - 0s 64us/step - loss: 1.0085e-04 - acc: 1.0000
Epoch 241/1000
455/455 [==============================] - 0s 66us/step - loss: 1.0193e-04 - acc: 1.0000
Epoch 242/1000
455/455 [==============================] - 0s 59us/step - loss: 9.9090e-05 - acc: 1.0000
Epoch 243/1000
455/455 [==============================] - 0s 48us/step - loss: 9.8861e-05 - acc: 1.0000
Epoch 244/1000
455/455 [==============================] - 0s 59us/step - loss: 9.6734e-05 - acc: 1.0000
Epoch 245/1000
455/455 [==============================] - 0s 48us/step - loss: 9.5538e-05 - acc: 1.0000
Epoch 246/1000
455/455 [==============================] - 0s 48us/step - loss: 9.4691e-05 - acc: 1.0000
Epoch 247/1000
455/455 [==============================] - 0s 48us/step - loss: 

455/455 [==============================] - 0s 50us/step - loss: 4.6925e-05 - acc: 1.0000
Epoch 317/1000
455/455 [==============================] - 0s 46us/step - loss: 4.6465e-05 - acc: 1.0000
Epoch 318/1000
455/455 [==============================] - 0s 39us/step - loss: 4.6063e-05 - acc: 1.0000
Epoch 319/1000
455/455 [==============================] - 0s 42us/step - loss: 4.5638e-05 - acc: 1.0000
Epoch 320/1000
455/455 [==============================] - 0s 55us/step - loss: 4.5173e-05 - acc: 1.0000
Epoch 321/1000
455/455 [==============================] - 0s 44us/step - loss: 4.4900e-05 - acc: 1.0000
Epoch 322/1000
455/455 [==============================] - 0s 44us/step - loss: 4.4575e-05 - acc: 1.0000
Epoch 323/1000
455/455 [==============================] - 0s 44us/step - loss: 4.4211e-05 - acc: 1.0000
Epoch 324/1000
455/455 [==============================] - 0s 46us/step - loss: 4.3749e-05 - acc: 1.0000
Epoch 325/1000
455/455 [==============================] - 0s 42us/step - loss: 

455/455 [==============================] - 0s 53us/step - loss: 2.3615e-05 - acc: 1.0000
Epoch 395/1000
455/455 [==============================] - 0s 46us/step - loss: 2.3358e-05 - acc: 1.0000
Epoch 396/1000
455/455 [==============================] - 0s 42us/step - loss: 2.3237e-05 - acc: 1.0000
Epoch 397/1000
455/455 [==============================] - 0s 46us/step - loss: 2.3022e-05 - acc: 1.0000
Epoch 398/1000
455/455 [==============================] - 0s 46us/step - loss: 2.2756e-05 - acc: 1.0000
Epoch 399/1000
455/455 [==============================] - 0s 42us/step - loss: 2.2598e-05 - acc: 1.0000
Epoch 400/1000
455/455 [==============================] - 0s 39us/step - loss: 2.2394e-05 - acc: 1.0000
Epoch 401/1000
455/455 [==============================] - 0s 44us/step - loss: 2.2213e-05 - acc: 1.0000
Epoch 402/1000
455/455 [==============================] - 0s 44us/step - loss: 2.2044e-05 - acc: 1.0000
Epoch 403/1000
455/455 [==============================] - 0s 42us/step - loss: 

455/455 [==============================] - 0s 55us/step - loss: 1.2369e-05 - acc: 1.0000
Epoch 473/1000
455/455 [==============================] - 0s 48us/step - loss: 1.2260e-05 - acc: 1.0000
Epoch 474/1000
455/455 [==============================] - 0s 39us/step - loss: 1.2171e-05 - acc: 1.0000
Epoch 475/1000
455/455 [==============================] - 0s 39us/step - loss: 1.2065e-05 - acc: 1.0000
Epoch 476/1000
455/455 [==============================] - 0s 42us/step - loss: 1.1953e-05 - acc: 1.0000
Epoch 477/1000
455/455 [==============================] - 0s 42us/step - loss: 1.1856e-05 - acc: 1.0000
Epoch 478/1000
455/455 [==============================] - 0s 46us/step - loss: 1.1762e-05 - acc: 1.0000
Epoch 479/1000
455/455 [==============================] - 0s 46us/step - loss: 1.1711e-05 - acc: 1.0000
Epoch 480/1000
455/455 [==============================] - 0s 44us/step - loss: 1.1596e-05 - acc: 1.0000
Epoch 481/1000
455/455 [==============================] - 0s 53us/step - loss: 

455/455 [==============================] - 0s 44us/step - loss: 6.6578e-06 - acc: 1.0000
Epoch 551/1000
455/455 [==============================] - 0s 42us/step - loss: 6.6102e-06 - acc: 1.0000
Epoch 552/1000
455/455 [==============================] - 0s 44us/step - loss: 6.5485e-06 - acc: 1.0000
Epoch 553/1000
455/455 [==============================] - 0s 44us/step - loss: 6.4808e-06 - acc: 1.0000
Epoch 554/1000
455/455 [==============================] - 0s 48us/step - loss: 6.4608e-06 - acc: 1.0000
Epoch 555/1000
455/455 [==============================] - 0s 59us/step - loss: 6.3862e-06 - acc: 1.0000
Epoch 556/1000
455/455 [==============================] - 0s 55us/step - loss: 6.3758e-06 - acc: 1.0000
Epoch 557/1000
455/455 [==============================] - 0s 59us/step - loss: 6.2861e-06 - acc: 1.0000
Epoch 558/1000
455/455 [==============================] - 0s 57us/step - loss: 6.2382e-06 - acc: 1.0000
Epoch 559/1000
455/455 [==============================] - 0s 55us/step - loss: 

455/455 [==============================] - 0s 55us/step - loss: 3.6201e-06 - acc: 1.0000
Epoch 629/1000
455/455 [==============================] - 0s 55us/step - loss: 3.5991e-06 - acc: 1.0000
Epoch 630/1000
455/455 [==============================] - 0s 50us/step - loss: 3.5692e-06 - acc: 1.0000
Epoch 631/1000
455/455 [==============================] - 0s 59us/step - loss: 3.5428e-06 - acc: 1.0000
Epoch 632/1000
455/455 [==============================] - 0s 59us/step - loss: 3.5138e-06 - acc: 1.0000
Epoch 633/1000
455/455 [==============================] - 0s 48us/step - loss: 3.4853e-06 - acc: 1.0000
Epoch 634/1000
455/455 [==============================] - 0s 50us/step - loss: 3.4635e-06 - acc: 1.0000
Epoch 635/1000
455/455 [==============================] - 0s 53us/step - loss: 3.4358e-06 - acc: 1.0000
Epoch 636/1000
455/455 [==============================] - 0s 53us/step - loss: 3.4095e-06 - acc: 1.0000
Epoch 637/1000
455/455 [==============================] - 0s 55us/step - loss: 

455/455 [==============================] - 0s 46us/step - loss: 1.9923e-06 - acc: 1.0000
Epoch 706/1000
455/455 [==============================] - 0s 46us/step - loss: 1.9736e-06 - acc: 1.0000
Epoch 707/1000
455/455 [==============================] - 0s 44us/step - loss: 1.9587e-06 - acc: 1.0000
Epoch 708/1000
455/455 [==============================] - 0s 42us/step - loss: 1.9451e-06 - acc: 1.0000
Epoch 709/1000
455/455 [==============================] - 0s 42us/step - loss: 1.9288e-06 - acc: 1.0000
Epoch 710/1000
455/455 [==============================] - 0s 48us/step - loss: 1.9213e-06 - acc: 1.0000
Epoch 711/1000
455/455 [==============================] - 0s 50us/step - loss: 1.9037e-06 - acc: 1.0000
Epoch 712/1000
455/455 [==============================] - 0s 44us/step - loss: 1.8893e-06 - acc: 1.0000
Epoch 713/1000
455/455 [==============================] - 0s 46us/step - loss: 1.8779e-06 - acc: 1.0000
Epoch 714/1000
455/455 [==============================] - 0s 42us/step - loss: 

455/455 [==============================] - 0s 46us/step - loss: 1.0960e-06 - acc: 1.0000
Epoch 784/1000
455/455 [==============================] - 0s 39us/step - loss: 1.0915e-06 - acc: 1.0000
Epoch 785/1000
455/455 [==============================] - 0s 42us/step - loss: 1.0820e-06 - acc: 1.0000
Epoch 786/1000
455/455 [==============================] - 0s 46us/step - loss: 1.0774e-06 - acc: 1.0000
Epoch 787/1000
455/455 [==============================] - 0s 42us/step - loss: 1.0721e-06 - acc: 1.0000
Epoch 788/1000
455/455 [==============================] - 0s 42us/step - loss: 1.0586e-06 - acc: 1.0000
Epoch 789/1000
455/455 [==============================] - 0s 39us/step - loss: 1.0491e-06 - acc: 1.0000
Epoch 790/1000
455/455 [==============================] - 0s 44us/step - loss: 1.0375e-06 - acc: 1.0000
Epoch 791/1000
455/455 [==============================] - 0s 42us/step - loss: 1.0288e-06 - acc: 1.0000
Epoch 792/1000
455/455 [==============================] - 0s 44us/step - loss: 

455/455 [==============================] - 0s 42us/step - loss: 6.1115e-07 - acc: 1.0000
Epoch 862/1000
455/455 [==============================] - 0s 44us/step - loss: 6.0659e-07 - acc: 1.0000
Epoch 863/1000
455/455 [==============================] - 0s 44us/step - loss: 6.0512e-07 - acc: 1.0000
Epoch 864/1000
455/455 [==============================] - 0s 37us/step - loss: 6.0024e-07 - acc: 1.0000
Epoch 865/1000
455/455 [==============================] - 0s 39us/step - loss: 5.9497e-07 - acc: 1.0000
Epoch 866/1000
455/455 [==============================] - 0s 42us/step - loss: 5.9535e-07 - acc: 1.0000
Epoch 867/1000
455/455 [==============================] - 0s 46us/step - loss: 5.9105e-07 - acc: 1.0000
Epoch 868/1000
455/455 [==============================] - 0s 42us/step - loss: 5.8469e-07 - acc: 1.0000
Epoch 869/1000
455/455 [==============================] - 0s 42us/step - loss: 5.8133e-07 - acc: 1.0000
Epoch 870/1000
455/455 [==============================] - 0s 42us/step - loss: 

455/455 [==============================] - 0s 44us/step - loss: 3.5362e-07 - acc: 1.0000
Epoch 940/1000
455/455 [==============================] - 0s 46us/step - loss: 3.5025e-07 - acc: 1.0000
Epoch 941/1000
455/455 [==============================] - 0s 42us/step - loss: 3.5039e-07 - acc: 1.0000
Epoch 942/1000
455/455 [==============================] - 0s 55us/step - loss: 3.4574e-07 - acc: 1.0000
Epoch 943/1000
455/455 [==============================] - 0s 53us/step - loss: 3.4041e-07 - acc: 1.0000
Epoch 944/1000
455/455 [==============================] - 0s 57us/step - loss: 3.4060e-07 - acc: 1.0000
Epoch 945/1000
455/455 [==============================] - 0s 57us/step - loss: 3.3725e-07 - acc: 1.0000
Epoch 946/1000
455/455 [==============================] - 0s 57us/step - loss: 3.3595e-07 - acc: 1.0000
Epoch 947/1000
455/455 [==============================] - 0s 50us/step - loss: 3.3409e-07 - acc: 1.0000
Epoch 948/1000
455/455 [==============================] - 0s 61us/step - loss: 

## 테스트용 데이터 표준화

In [20]:
X_test = scaler.transform(X_test)
X_test

array([[-0.34276494, -1.4014298 , -0.35993972, ...,  0.02356663,
        -0.83419096,  0.0831094 ],
       [ 0.12349522, -0.03292217,  0.10311098, ..., -0.2708704 ,
        -0.6880982 , -0.50267047],
       [ 0.30776566, -1.4264356 ,  0.24085142, ..., -0.48402107,
        -0.66183436, -0.87724733],
       ...,
       [-0.68897   , -0.29662126, -0.62083626, ...,  0.41645026,
        -0.37785617,  0.46843433],
       [-0.5633311 , -1.3741505 , -0.56209385, ..., -0.6021872 ,
        -0.17923552, -0.18613447],
       [ 1.2291181 , -0.4466569 ,  1.1989572 , ...,  0.78825974,
        -0.6240802 ,  0.5624815 ]], dtype=float32)

## 테스트용 데이터를 활용한 예측

In [21]:
pred = model.predict(X_test)
pred

array([[9.9999988e-01],
       [9.9999881e-01],
       [1.0000000e+00],
       [9.9999988e-01],
       [1.1920929e-07],
       [1.7881393e-07],
       [9.9999940e-01],
       [9.9999994e-01],
       [9.9999988e-01],
       [9.9999988e-01],
       [9.9999994e-01],
       [9.9999988e-01],
       [1.7881393e-07],
       [9.9999988e-01],
       [9.9999988e-01],
       [9.9999994e-01],
       [1.7881393e-07],
       [9.9999988e-01],
       [9.9999988e-01],
       [9.9999988e-01],
       [1.7881393e-07],
       [9.9999994e-01],
       [9.9999988e-01],
       [2.0861626e-07],
       [9.9999988e-01],
       [2.0861626e-07],
       [9.9057591e-01],
       [2.3841858e-07],
       [9.9999976e-01],
       [9.9999988e-01],
       [9.9999630e-01],
       [9.9999976e-01],
       [2.0861626e-07],
       [9.9999994e-01],
       [9.9999994e-01],
       [1.7881393e-07],
       [1.7881393e-07],
       [9.9999988e-01],
       [9.9999994e-01],
       [9.9999994e-01],
       [1.7881393e-07],
       [1.788139

In [33]:
pred01 = np.where(pred>0.5, 1, 0)
pred01

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

## 정확도 측정

In [36]:
pred02 = (pred01==y_test)
acc = np.sum(pred02)/len(pred02)
acc

0.9736842105263158