In [2]:
import tensorflow as tf
import numpy as np

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

In [3]:
tf.enable_eager_execution()

## X가 입력데이터

In [4]:
X = np.array([
    [0, 0], [0, 1], [1, 0], [1, 1]], dtype="float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

## y는 타겟 밸류

In [5]:
y = np.array([[0], [0], [0], [1]], dtype="float32")
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

## W가 Weight 값

In [6]:
W = tf.Variable([[2], [3]], dtype="float32")
W

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.],
       [3.]], dtype=float32)>

In [7]:
tf.matmul(X, W)

<tf.Tensor: id=12, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [3.],
       [2.],
       [5.]], dtype=float32)>

In [8]:
b = tf.Variable([3], dtype="float32")
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [9]:
tf.matmul(X, W) + b

Instructions for updating:
Colocations handled automatically by placer.


<tf.Tensor: id=27, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [6.],
       [5.],
       [8.]], dtype=float32)>

## 임의로 설정한 모델에 값을 입력

In [10]:
tf.sigmoid(tf.matmul(X, W) + b)

<tf.Tensor: id=34, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9975274 ],
       [0.9933072 ],
       [0.99966466]], dtype=float32)>

In [11]:
optimizer = tf.train.AdamOptimizer(0.01)

## 학습 부분 아래 내용은 1번 실행인데 반복 실행으로 변경

In [12]:
with tf.GradientTape() as tape:
    hypothesis = tf.sigmoid(tf.matmul(X, W)+ b) 
    print(f"hypothesis : {hypothesis}")
    cost = -tf.reduce_mean(y*tf.log(hypothesis) +\
                          (1-y)*tf.log(1-hypothesis))
    print(f"cost : {cost}")
    grads = tape.gradient(cost, [W, b])
    print("w: ", W)
    print("b: ", b)
    print("Grads : ", grads)
print("zip(grads, [w, b])", zip(grads, [W, b]))
optimizer.apply_gradients(grads_and_vars= zip(grads, [W, b]))

hypothesis : [[0.95257413]
 [0.9975274 ]
 [0.9933072 ]
 [0.99966466]]
cost : 3.5145339965820312
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.],
       [3.]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>
Grads :  [<tf.Tensor: id=93, shape=(2, 1), dtype=float32, numpy=
array([[0.24824296],
       [0.24929802]], dtype=float32)>, <tf.Tensor: id=91, shape=(1,), dtype=float32, numpy=array([0.7357683], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA5125C8>


## 학습 부분 반복

In [13]:
for epoch in range(5000):
    with tf.GradientTape() as tape:
        hypothesis = tf.sigmoid(tf.matmul(X, W)+ b) 
        print(f"hypothesis : {hypothesis}")
        cost = -tf.reduce_mean(y*tf.log(hypothesis) +\
                              (1-y)*tf.log(1-hypothesis))
        print(f"cost : {cost}")
        grads = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(grads_and_vars= zip(grads, [W, b]))
    if (epoch+1)%100 == 0:
        print("w: ", W)
        print("b: ", b)
        print("Grads : ", grads)
        print("zip(grads, [w, b])", zip(grads, [W, b]))
    

hypothesis : [[0.95212024]
 [0.9974776 ]
 [0.9931728 ]
 [0.9996544 ]]
cost : 3.5021982192993164
hypothesis : [[0.95166236]
 [0.9974267 ]
 [0.99303585]
 [0.9996439 ]]
cost : 3.4898605346679688
hypothesis : [[0.9512003 ]
 [0.9973749 ]
 [0.99289626]
 [0.9996331 ]]
cost : 3.477541208267212
hypothesis : [[0.9507341 ]
 [0.997322  ]
 [0.9927538 ]
 [0.99962187]]
cost : 3.4652183055877686
hypothesis : [[0.9502635]
 [0.9972681]
 [0.9926085]
 [0.9996105]]
cost : 3.452894926071167
hypothesis : [[0.9497888 ]
 [0.99721307]
 [0.9924603 ]
 [0.99959856]]
cost : 3.4405765533447266
hypothesis : [[0.94930977]
 [0.99715686]
 [0.9923092 ]
 [0.9995863 ]]
cost : 3.428253412246704
hypothesis : [[0.9488265 ]
 [0.99709964]
 [0.992155  ]
 [0.99957377]]
cost : 3.415940046310425
hypothesis : [[0.94833887]
 [0.99704117]
 [0.9919979 ]
 [0.9995608 ]]
cost : 3.403625249862671
hypothesis : [[0.9478468 ]
 [0.99698156]
 [0.99183756]
 [0.9995473 ]]
cost : 3.391312599182129
hypothesis : [[0.94735044]
 [0.9969208 ]
 [0.99167

cost : 2.2838664054870605
hypothesis : [[0.8784029 ]
 [0.98111963]
 [0.9504759 ]
 [0.9928088 ]]
cost : 2.272296905517578
hypothesis : [[0.87735486]
 [0.980752  ]
 [0.9495483 ]
 [0.99259573]]
cost : 2.26074481010437
hypothesis : [[0.87629944]
 [0.9803774 ]
 [0.9486049 ]
 [0.9923765 ]]
cost : 2.249207019805908
hypothesis : [[0.87523687]
 [0.9799959 ]
 [0.9476455 ]
 [0.9921509 ]]
cost : 2.2376883029937744
hypothesis : [[0.8741671 ]
 [0.9796072 ]
 [0.9466697 ]
 [0.99191886]]
cost : 2.226184844970703
hypothesis : [[0.87309   ]
 [0.97921133]
 [0.94567746]
 [0.9916801 ]]
cost : 2.2146990299224854
hypothesis : [[0.87200564]
 [0.9788083 ]
 [0.94466835]
 [0.99143445]]
cost : 2.2032315731048584
hypothesis : [[0.870914  ]
 [0.9783976 ]
 [0.9436425 ]
 [0.99118173]]
cost : 2.1917812824249268
hypothesis : [[0.869815 ]
 [0.9779795]
 [0.9425993]
 [0.9909219]]
cost : 2.180349588394165
hypothesis : [[0.8687088 ]
 [0.97755355]
 [0.94153893]
 [0.99065465]]
cost : 2.168935775756836
hypothesis : [[0.8675952 

hypothesis : [[0.74796575]
 [0.8963745 ]
 [0.7687681 ]
 [0.9064594 ]]
cost : 1.3019262552261353
hypothesis : [[0.7463247 ]
 [0.894744  ]
 [0.7658123 ]
 [0.90429205]]
cost : 1.2938238382339478
hypothesis : [[0.7446807 ]
 [0.8930956 ]
 [0.76284164]
 [0.90208775]]
cost : 1.2857829332351685
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.09009679],
       [1.0436287 ]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0617967], dtype=float32)>
Grads :  [<tf.Tensor: id=13955, shape=(2, 1), dtype=float32, numpy=
array([[0.16623235],
       [0.19879583]], dtype=float32)>, <tf.Tensor: id=13953, shape=(1,), dtype=float32, numpy=array([0.5756764], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA57DEC8>
hypothesis : [[0.74303377]
 [0.89142936]
 [0.7598566 ]
 [0.8998467 ]]
cost : 1.277803659439087
hypothesis : [[0.741384  ]
 [0.88974524]
 [0.7568577 ]
 [0.8975686 ]]
cost : 1.2698866128921509
hypothesis : [[0.73973155]


hypothesis : [[0.5904085 ]
 [0.68646646]
 [0.49502087]
 [0.59822613]]
cost : 0.8123670816421509
hypothesis : [[0.58898306]
 [0.6843364 ]
 [0.49309152]
 [0.59540945]]
cost : 0.8100324869155884
hypothesis : [[0.5875629 ]
 [0.6822168 ]
 [0.49118543]
 [0.5926223 ]]
cost : 0.8077318072319031
hypothesis : [[0.58614814]
 [0.68010795]
 [0.4893024 ]
 [0.58986485]]
cost : 0.8054645657539368
hypothesis : [[0.5847386 ]
 [0.6780099 ]
 [0.48744246]
 [0.58713734]]
cost : 0.8032301068305969
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.39407054],
       [ 0.3986208 ]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.33647653], dtype=float32)>
Grads :  [<tf.Tensor: id=20861, shape=(2, 1), dtype=float32, numpy=
array([[0.01864495],
       [0.0662868 ]], dtype=float32)>, <tf.Tensor: id=20859, shape=(1,), dtype=float32, numpy=array([0.33433208], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA57B988>
hypothesis : [[0.58333

 [0.4554801 ]]
cost : 0.6808481812477112
hypothesis : [[0.47898024]
 [0.5406589 ]
 [0.394618  ]
 [0.4549184 ]]
cost : 0.6798655986785889
hypothesis : [[0.47794622]
 [0.53958607]
 [0.39413315]
 [0.45437157]]
cost : 0.6788872480392456
hypothesis : [[0.47691506]
 [0.5385219 ]
 [0.39365646]
 [0.4538395 ]]
cost : 0.6779130697250366
hypothesis : [[0.47588676]
 [0.5374663 ]
 [0.3931878 ]
 [0.45332193]]
cost : 0.6769430041313171
hypothesis : [[0.47486112]
 [0.5364193 ]
 [0.39272693]
 [0.45281872]]
cost : 0.6759768724441528
hypothesis : [[0.47383836]
 [0.5353806 ]
 [0.39227384]
 [0.4523295 ]]
cost : 0.6750147342681885
hypothesis : [[0.47281834]
 [0.53435034]
 [0.39182836]
 [0.45185435]]
cost : 0.674056351184845
hypothesis : [[0.47180107]
 [0.53332835]
 [0.39139038]
 [0.4513929 ]]
cost : 0.6731017827987671
hypothesis : [[0.47078642]
 [0.53231454]
 [0.3909598 ]
 [0.45094496]]
cost : 0.6721508502960205
hypothesis : [[0.46977448]
 [0.5313088 ]
 [0.39053655]
 [0.45051044]]
cost : 0.67120361328125
hy

hypothesis : [[0.3788657 ]
 [0.45959395]
 [0.37034726]
 [0.45057708]]
cost : 0.5878638625144958
hypothesis : [[0.3780375 ]
 [0.4590712 ]
 [0.3702627 ]
 [0.45083785]]
cost : 0.5871108174324036
hypothesis : [[0.37721065]
 [0.45855093]
 [0.370179  ]
 [0.4511012 ]]
cost : 0.5863590836524963
hypothesis : [[0.37638512]
 [0.45803306]
 [0.3700962 ]
 [0.45136735]]
cost : 0.5856086611747742
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-0.02372243],
       [ 0.3380931 ]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.5084331], dtype=float32)>
Grads :  [<tf.Tensor: id=34673, shape=(2, 1), dtype=float32, numpy=
array([[-0.0446341],
       [-0.0226499]], dtype=float32)>, <tf.Tensor: id=34671, shape=(1,), dtype=float32, numpy=array([0.16397044], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA54C908>
hypothesis : [[0.3755609 ]
 [0.45751765]
 [0.37001425]
 [0.45163608]]
cost : 0.5848594307899475
hypothesis : [[0.37473

 [0.47874007]]
cost : 0.5282731652259827
hypothesis : [[0.31223923]
 [0.42139938]
 [0.3644163 ]
 [0.4791105 ]]
cost : 0.5276230573654175
hypothesis : [[0.31151766]
 [0.42101526]
 [0.36434647]
 [0.47948116]]
cost : 0.5269743204116821
hypothesis : [[0.31079724]
 [0.42063224]
 [0.3642764 ]
 [0.4798522 ]]
cost : 0.5263265371322632
hypothesis : [[0.3100781 ]
 [0.42025024]
 [0.36420602]
 [0.4802236 ]]
cost : 0.5256799459457397
hypothesis : [[0.30936015]
 [0.41986915]
 [0.3641354 ]
 [0.4805953 ]]
cost : 0.5250344276428223
hypothesis : [[0.3086434 ]
 [0.4194892 ]
 [0.36406443]
 [0.48096716]]
cost : 0.5243901610374451
hypothesis : [[0.3079279 ]
 [0.41911015]
 [0.36399317]
 [0.48133945]]
cost : 0.5237469673156738
hypothesis : [[0.30721363]
 [0.4187322 ]
 [0.36392164]
 [0.481712  ]]
cost : 0.5231049060821533
hypothesis : [[0.30650052]
 [0.41835514]
 [0.36384982]
 [0.48208472]]
cost : 0.5224639773368835
hypothesis : [[0.3057886 ]
 [0.4179791 ]
 [0.36377767]
 [0.48245776]]
cost : 0.5218242406845093

cost : 0.47861653566360474
hypothesis : [[0.25711176]
 [0.39276636]
 [0.35751307]
 [0.50978905]]
cost : 0.47805461287498474
hypothesis : [[0.25649017]
 [0.39244735]
 [0.3574125 ]
 [0.51015925]]
cost : 0.4774935841560364
hypothesis : [[0.25586984]
 [0.39212903]
 [0.35731152]
 [0.5105292 ]]
cost : 0.47693365812301636
hypothesis : [[0.2552507 ]
 [0.39181128]
 [0.35721013]
 [0.51089895]]
cost : 0.47637462615966797
hypothesis : [[0.25463283]
 [0.39149415]
 [0.35710835]
 [0.5112685 ]]
cost : 0.47581663727760315
hypothesis : [[0.25401616]
 [0.39117768]
 [0.35700616]
 [0.51163775]]
cost : 0.4752596616744995
hypothesis : [[0.25340068]
 [0.39086178]
 [0.35690355]
 [0.5120068 ]]
cost : 0.4747036099433899
hypothesis : [[0.25278646]
 [0.39054653]
 [0.35680062]
 [0.51237565]]
cost : 0.474148690700531
hypothesis : [[0.25217345]
 [0.39023182]
 [0.3566972 ]
 [0.5127442 ]]
cost : 0.47359466552734375
hypothesis : [[0.25156164]
 [0.38991776]
 [0.3565934 ]
 [0.51311255]]
cost : 0.4730415642261505
hypothesi

cost : 0.4237937927246094
hypothesis : [[0.1974342 ]
 [0.36170834]
 [0.34466413]
 [0.5478218 ]]
cost : 0.4233284890651703
hypothesis : [[0.19693987]
 [0.36144364]
 [0.34452665]
 [0.54816055]]
cost : 0.4228639602661133
hypothesis : [[0.19644666]
 [0.36117938]
 [0.34438893]
 [0.5484989 ]]
cost : 0.42240020632743835
hypothesis : [[0.19595458]
 [0.36091548]
 [0.34425092]
 [0.5488369 ]]
cost : 0.4219372868537903
hypothesis : [[0.19546367]
 [0.36065206]
 [0.3441126 ]
 [0.5491746 ]]
cost : 0.4214751720428467
hypothesis : [[0.19497386]
 [0.360389  ]
 [0.3439741 ]
 [0.549512  ]]
cost : 0.42101380228996277
hypothesis : [[0.19448519]
 [0.36012638]
 [0.34383532]
 [0.54984903]]
cost : 0.4205533266067505
hypothesis : [[0.1939976 ]
 [0.35986412]
 [0.34369624]
 [0.5501858 ]]
cost : 0.4200935661792755
hypothesis : [[0.19351119]
 [0.3596023 ]
 [0.34355694]
 [0.55052215]]
cost : 0.4196346402168274
hypothesis : [[0.19302589]
 [0.3593409 ]
 [0.34341735]
 [0.5508583 ]]
cost : 0.41917645931243896
hypothesis 

cost : 0.38815999031066895
hypothesis : [[0.16052225]
 [0.3412638 ]
 [0.33262318]
 [0.5745245 ]]
cost : 0.3877550959587097
hypothesis : [[0.16011551]
 [0.34102887]
 [0.33246827]
 [0.574837  ]]
cost : 0.3873508870601654
hypothesis : [[0.15970974]
 [0.34079424]
 [0.33231324]
 [0.5751492 ]]
cost : 0.386947363615036
hypothesis : [[0.15930498]
 [0.3405599 ]
 [0.33215803]
 [0.57546103]]
cost : 0.38654446601867676
hypothesis : [[0.15890118]
 [0.3403259 ]
 [0.33200267]
 [0.5757726 ]]
cost : 0.3861422538757324
hypothesis : [[0.1584984 ]
 [0.34009218]
 [0.33184713]
 [0.57608384]]
cost : 0.385740727186203
hypothesis : [[0.1580966 ]
 [0.3398588 ]
 [0.33169147]
 [0.5763948 ]]
cost : 0.3853398263454437
hypothesis : [[0.15769579]
 [0.33962572]
 [0.33153567]
 [0.57670546]]
cost : 0.38493961095809937
hypothesis : [[0.15729596]
 [0.33939293]
 [0.33137968]
 [0.57701576]]
cost : 0.38454002141952515
hypothesis : [[0.15689711]
 [0.33916047]
 [0.33122355]
 [0.57732576]]
cost : 0.38414114713668823
hypothesis 

 [0.59914887]]
cost : 0.3567028045654297
hypothesis : [[0.1299798 ]
 [0.32274443]
 [0.31933516]
 [0.5994372 ]]
cost : 0.3563486933708191
hypothesis : [[0.12964937]
 [0.32253233]
 [0.31917095]
 [0.59972507]]
cost : 0.3559951186180115
hypothesis : [[0.12931977]
 [0.3223205 ]
 [0.31900665]
 [0.6000127 ]]
cost : 0.3556421399116516
hypothesis : [[0.12899102]
 [0.3221089 ]
 [0.31884235]
 [0.6003001 ]]
cost : 0.35528966784477234
hypothesis : [[0.1286631 ]
 [0.32189757]
 [0.31867793]
 [0.6005871 ]]
cost : 0.3549377918243408
hypothesis : [[0.12833601]
 [0.32168645]
 [0.31851342]
 [0.60087395]]
cost : 0.3545864224433899
hypothesis : [[0.12800977]
 [0.32147557]
 [0.3183489 ]
 [0.6011605 ]]
cost : 0.35423558950424194
hypothesis : [[0.12768435]
 [0.32126492]
 [0.31818432]
 [0.60144675]]
cost : 0.35388538241386414
hypothesis : [[0.12735976]
 [0.32105452]
 [0.31801963]
 [0.6017327 ]]
cost : 0.3535357117652893
hypothesis : [[0.127036  ]
 [0.32084435]
 [0.31785494]
 [0.6020184 ]]
cost : 0.3531865179538

cost : 0.3256818652153015
hypothesis : [[0.10234918]
 [0.30376416]
 [0.3036995 ]
 [0.62532467]]
cost : 0.3253748118877411
hypothesis : [[0.10208987]
 [0.30357167]
 [0.30353203]
 [0.6255878 ]]
cost : 0.3250681757926941
hypothesis : [[0.10183123]
 [0.30337933]
 [0.30336455]
 [0.62585074]]
cost : 0.3247619569301605
hypothesis : [[0.10157327]
 [0.30318722]
 [0.30319712]
 [0.6261135 ]]
cost : 0.32445627450942993
hypothesis : [[0.10131596]
 [0.30299526]
 [0.30302966]
 [0.62637585]]
cost : 0.3241509795188904
hypothesis : [[0.10105933]
 [0.30280346]
 [0.30286223]
 [0.6266381 ]]
cost : 0.32384610176086426
hypothesis : [[0.10080337]
 [0.30261186]
 [0.30269474]
 [0.6268999 ]]
cost : 0.3235417604446411
hypothesis : [[0.10054806]
 [0.30242044]
 [0.30252722]
 [0.62716156]]
cost : 0.3232377767562866
hypothesis : [[0.10029343]
 [0.30222917]
 [0.3023598 ]
 [0.6274231 ]]
cost : 0.32293426990509033
hypothesis : [[0.10003947]
 [0.30203813]
 [0.30219233]
 [0.62768424]]
cost : 0.32263123989105225
hypothesis

cost : 0.29811641573905945
hypothesis : [[0.08029959]
 [0.28603733]
 [0.28768057]
 [0.649513  ]]
cost : 0.29784828424453735
hypothesis : [[0.08009779]
 [0.28586003]
 [0.28751498]
 [0.64975405]]
cost : 0.2975805103778839
hypothesis : [[0.07989653]
 [0.28568286]
 [0.28734943]
 [0.6499949 ]]
cost : 0.29731306433677673
hypothesis : [[0.07969581]
 [0.28550586]
 [0.28718394]
 [0.65023553]]
cost : 0.2970460057258606
hypothesis : [[0.07949558]
 [0.28532898]
 [0.2870185 ]
 [0.65047604]]
cost : 0.2967792749404907
hypothesis : [[0.07929588]
 [0.28515223]
 [0.28685308]
 [0.6507161 ]]
cost : 0.2965129315853119
hypothesis : [[0.07909672]
 [0.28497565]
 [0.2866877 ]
 [0.65095615]]
cost : 0.2962470054626465
hypothesis : [[0.07889806]
 [0.28479922]
 [0.28652233]
 [0.6511959 ]]
cost : 0.29598137736320496
hypothesis : [[0.07869995]
 [0.28462288]
 [0.28635702]
 [0.65143543]]
cost : 0.2957161068916321
hypothesis : [[0.07850234]
 [0.2844467 ]
 [0.28619176]
 [0.6516748 ]]
cost : 0.29545119404792786
hypothesi

cost : 0.2763121724128723
hypothesis : [[0.06473988]
 [0.2712703 ]
 [0.27361035]
 [0.6694899 ]]
cost : 0.2760727107524872
hypothesis : [[0.06457876]
 [0.271104  ]
 [0.27344912]
 [0.66971356]]
cost : 0.2758336067199707
hypothesis : [[0.06441806]
 [0.27093777]
 [0.2732879 ]
 [0.6699371 ]]
cost : 0.2755947709083557
hypothesis : [[0.06425777]
 [0.27077165]
 [0.27312675]
 [0.67016035]]
cost : 0.2753562331199646
hypothesis : [[0.06409789]
 [0.27060565]
 [0.27296564]
 [0.67038345]]
cost : 0.27511805295944214
hypothesis : [[0.06393845]
 [0.2704398 ]
 [0.27280462]
 [0.6706063 ]]
cost : 0.27488014101982117
hypothesis : [[0.06377941]
 [0.27027407]
 [0.27264366]
 [0.67082906]]
cost : 0.2746425271034241
hypothesis : [[0.06362079]
 [0.27010843]
 [0.27248272]
 [0.6710516 ]]
cost : 0.27440521121025085
hypothesis : [[0.06346259]
 [0.2699429 ]
 [0.27232188]
 [0.671274  ]]
cost : 0.2741681933403015
hypothesis : [[0.0633048 ]
 [0.26977754]
 [0.27216113]
 [0.67149615]]
cost : 0.27393150329589844
hypothesis

cost : 0.25634661316871643
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.8543063],
       [1.8406997]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-2.9020135], dtype=float32)>
Grads :  [<tf.Tensor: id=89921, shape=(2, 1), dtype=float32, numpy=
array([[-0.01297835],
       [-0.01362979]], dtype=float32)>, <tf.Tensor: id=89919, shape=(1,), dtype=float32, numpy=array([0.06437112], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA583408>
hypothesis : [[0.05205412]
 [0.25705847]
 [0.2596656 ]
 [0.68847346]]
cost : 0.2561319172382355
hypothesis : [[0.05192601]
 [0.25690168]
 [0.2595102 ]
 [0.6886814 ]]
cost : 0.25591737031936646
hypothesis : [[0.05179824]
 [0.25674498]
 [0.25935486]
 [0.68888915]]
cost : 0.2557031512260437
hypothesis : [[0.05167079]
 [0.25658843]
 [0.25919962]
 [0.68909675]]
cost : 0.25548920035362244
hypothesis : [[0.05154368]
 [0.25643197]
 [0.2590444 ]
 [0.6893041 ]]
cost : 0.255275458097

cost : 0.23838208615779877
hypothesis : [[0.04195935]
 [0.24363494]
 [0.24627087]
 [0.70614505]]
cost : 0.2381882667541504
hypothesis : [[0.04185731]
 [0.24348654]
 [0.24612202]
 [0.7063389 ]]
cost : 0.23799458146095276
hypothesis : [[0.04175552]
 [0.24333833]
 [0.24597326]
 [0.7065326 ]]
cost : 0.2378011792898178
hypothesis : [[0.041654  ]
 [0.24319012]
 [0.24582455]
 [0.7067261 ]]
cost : 0.23760801553726196
hypothesis : [[0.04155274]
 [0.24304205]
 [0.2456759 ]
 [0.7069195 ]]
cost : 0.23741498589515686
hypothesis : [[0.04145173]
 [0.24289404]
 [0.24552739]
 [0.70711255]]
cost : 0.23722229897975922
hypothesis : [[0.04135099]
 [0.24274616]
 [0.24537891]
 [0.7073057 ]]
cost : 0.23702970147132874
hypothesis : [[0.0412505 ]
 [0.2425984 ]
 [0.24523051]
 [0.70749867]]
cost : 0.23683738708496094
hypothesis : [[0.04115027]
 [0.24245064]
 [0.24508217]
 [0.7076914 ]]
cost : 0.23664525151252747
hypothesis : [[0.04105031]
 [0.24230301]
 [0.24493396]
 [0.707884  ]]
cost : 0.2364533692598343
hypoth

cost : 0.21950127184391022
hypothesis : [[0.03270923]
 [0.22881937]
 [0.23134705]
 [0.7253449 ]]
cost : 0.2193281352519989
hypothesis : [[0.03263081]
 [0.22868003]
 [0.23120624]
 [0.7255241 ]]
cost : 0.21915513277053833
hypothesis : [[0.03255259]
 [0.22854073]
 [0.23106551]
 [0.7257032 ]]
cost : 0.21898233890533447
hypothesis : [[0.03247456]
 [0.2284015 ]
 [0.23092479]
 [0.725882  ]]
cost : 0.21880970895290375
hypothesis : [[0.03239673]
 [0.22826234]
 [0.23078418]
 [0.7260606 ]]
cost : 0.21863728761672974
hypothesis : [[0.0323191 ]
 [0.22812329]
 [0.23064364]
 [0.7262393 ]]
cost : 0.21846500039100647
hypothesis : [[0.03224166]
 [0.22798431]
 [0.2305032 ]
 [0.7264177 ]]
cost : 0.2182929515838623
hypothesis : [[0.03216442]
 [0.2278454 ]
 [0.23036285]
 [0.726596  ]]
cost : 0.21812108159065247
hypothesis : [[0.03208738]
 [0.22770663]
 [0.23022257]
 [0.7267743 ]]
cost : 0.21794936060905457
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.20131  ],
       [2.1870608

cost : 0.20461928844451904
hypothesis : [[0.02638905]
 [0.21660191]
 [0.2189846 ]
 [0.7409456 ]]
cost : 0.20446158945560455
hypothesis : [[0.02632657]
 [0.2164698 ]
 [0.21885075]
 [0.74111325]]
cost : 0.20430395007133484
hypothesis : [[0.02626424]
 [0.21633776]
 [0.21871698]
 [0.7412807 ]]
cost : 0.20414654910564423
hypothesis : [[0.02620207]
 [0.21620584]
 [0.2185833 ]
 [0.74144804]]
cost : 0.20398929715156555
hypothesis : [[0.02614005]
 [0.21607393]
 [0.21844974]
 [0.74161536]]
cost : 0.20383217930793762
hypothesis : [[0.02607819]
 [0.21594208]
 [0.2183162 ]
 [0.7417823 ]]
cost : 0.2036752700805664
hypothesis : [[0.02601649]
 [0.21581036]
 [0.21818274]
 [0.7419494 ]]
cost : 0.20351845026016235
hypothesis : [[0.02595493]
 [0.21567872]
 [0.21804938]
 [0.7421162 ]]
cost : 0.2033618539571762
hypothesis : [[0.02589354]
 [0.21554713]
 [0.21791609]
 [0.74228287]]
cost : 0.2032053917646408
hypothesis : [[0.02583229]
 [0.21541561]
 [0.21778281]
 [0.7424496 ]]
cost : 0.20304900407791138
hypoth

cost : 0.19233998656272888
hypothesis : [[0.02180182]
 [0.20615098]
 [0.20839253]
 [0.7541356 ]]
cost : 0.19219443202018738
hypothesis : [[0.02175078]
 [0.20602506]
 [0.20826489]
 [0.75429374]]
cost : 0.19204899668693542
hypothesis : [[0.02169985]
 [0.20589922]
 [0.20813732]
 [0.7544517 ]]
cost : 0.191903755068779
hypothesis : [[0.02164906]
 [0.20577349]
 [0.20800981]
 [0.75460964]]
cost : 0.19175860285758972
hypothesis : [[0.02159839]
 [0.2056478 ]
 [0.20788239]
 [0.75476736]]
cost : 0.19161364436149597
hypothesis : [[0.02154785]
 [0.20552218]
 [0.20775507]
 [0.75492495]]
cost : 0.19146880507469177
hypothesis : [[0.02149744]
 [0.20539665]
 [0.20762779]
 [0.7550825 ]]
cost : 0.19132408499717712
hypothesis : [[0.02144715]
 [0.20527124]
 [0.20750062]
 [0.75523996]]
cost : 0.1911795437335968
hypothesis : [[0.02139698]
 [0.20514582]
 [0.20737346]
 [0.75539714]]
cost : 0.19103515148162842
hypothesis : [[0.02134693]
 [0.20502052]
 [0.2072464 ]
 [0.75555444]]
cost : 0.1908908486366272
hypothe

cost : 0.1809931993484497
hypothesis : [[0.01805023]
 [0.19619167]
 [0.19829401]
 [0.76658404]]
cost : 0.18085846304893494
hypothesis : [[0.01800843]
 [0.19607165]
 [0.19817238]
 [0.7667332 ]]
cost : 0.1807239055633545
hypothesis : [[0.01796674]
 [0.19595176]
 [0.1980508 ]
 [0.7668824 ]]
cost : 0.1805894672870636
hypothesis : [[0.01792515]
 [0.19583197]
 [0.19792931]
 [0.7670315 ]]
cost : 0.18045519292354584
hypothesis : [[0.01788366]
 [0.19571222]
 [0.19780791]
 [0.76718056]]
cost : 0.18032097816467285
hypothesis : [[0.01784228]
 [0.19559258]
 [0.19768658]
 [0.76732945]]
cost : 0.180186927318573
hypothesis : [[0.01780099]
 [0.19547294]
 [0.19756527]
 [0.76747817]]
cost : 0.1800530105829239
hypothesis : [[0.0177598 ]
 [0.19535337]
 [0.19744405]
 [0.7676267 ]]
cost : 0.17991924285888672
hypothesis : [[0.01771871]
 [0.19523387]
 [0.19732288]
 [0.7677753 ]]
cost : 0.17978551983833313
hypothesis : [[0.01767773]
 [0.1951145 ]
 [0.19720177]
 [0.7679237 ]]
cost : 0.17965197563171387
hypothesi

 [0.77904826]]
cost : 0.16973164677619934
hypothesis : [[0.01477065]
 [0.18601829]
 [0.18797924]
 [0.7791888 ]]
cost : 0.16960735619068146
hypothesis : [[0.01473684]
 [0.18590443]
 [0.1878638 ]
 [0.7793293 ]]
cost : 0.1694832146167755
hypothesis : [[0.01470312]
 [0.18579061]
 [0.18774845]
 [0.77946967]]
cost : 0.16935916244983673
hypothesis : [[0.01466949]
 [0.18567687]
 [0.18763314]
 [0.77961004]]
cost : 0.1692352145910263
hypothesis : [[0.01463593]
 [0.18556325]
 [0.18751793]
 [0.7797503 ]]
cost : 0.16911140084266663
hypothesis : [[0.01460245]
 [0.18544963]
 [0.18740276]
 [0.77989024]]
cost : 0.1689876914024353
hypothesis : [[0.01456905]
 [0.18533607]
 [0.18728761]
 [0.7800303 ]]
cost : 0.16886407136917114
hypothesis : [[0.01453574]
 [0.18522261]
 [0.18717262]
 [0.78017014]]
cost : 0.1687406450510025
hypothesis : [[0.0145025 ]
 [0.18510923]
 [0.18705766]
 [0.7803101 ]]
cost : 0.16861723363399506
hypothesis : [[0.01446935]
 [0.18499592]
 [0.1869428 ]
 [0.7804498 ]]
cost : 0.1684939563

cost : 0.15990442037582397
hypothesis : [[0.01225313]
 [0.1769056 ]
 [0.17874286]
 [0.79039407]]
cost : 0.15978898108005524
hypothesis : [[0.01222539]
 [0.17679723]
 [0.17863303]
 [0.79052687]]
cost : 0.15967358648777008
hypothesis : [[0.01219772]
 [0.17668891]
 [0.17852329]
 [0.7906595 ]]
cost : 0.15955837070941925
hypothesis : [[0.01217011]
 [0.1765807 ]
 [0.17841361]
 [0.79079217]]
cost : 0.159443199634552
hypothesis : [[0.01214258]
 [0.17647257]
 [0.178304  ]
 [0.7909247 ]]
cost : 0.1593281477689743
hypothesis : [[0.01211511]
 [0.17636448]
 [0.1781945 ]
 [0.7910572 ]]
cost : 0.15921320021152496
hypothesis : [[0.0120877 ]
 [0.17625642]
 [0.17808498]
 [0.79118943]]
cost : 0.15909835696220398
hypothesis : [[0.01206036]
 [0.17614844]
 [0.17797557]
 [0.7913217 ]]
cost : 0.15898358821868896
hypothesis : [[0.01203308]
 [0.17604055]
 [0.17786625]
 [0.7914539 ]]
cost : 0.1588689684867859
hypothesis : [[0.01200587]
 [0.17593275]
 [0.17775702]
 [0.79158604]]
cost : 0.15875443816184998
hypothe

 [0.8016148 ]]
cost : 0.15012234449386597
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.9998074],
       [2.9875638]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-4.590166], dtype=float32)>
Grads :  [<tf.Tensor: id=138263, shape=(2, 1), dtype=float32, numpy=
array([[-0.00723692],
       [-0.00766606]], dtype=float32)>, <tf.Tensor: id=138261, shape=(1,), dtype=float32, numpy=array([0.03721124], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA5A00C8>
hypothesis : [[0.01004916]
 [0.16761823]
 [0.16933343]
 [0.80174005]]
cost : 0.1500154435634613
hypothesis : [[0.01002667]
 [0.16751552]
 [0.16922939]
 [0.80186504]]
cost : 0.1499086320400238
hypothesis : [[0.01000424]
 [0.16741286]
 [0.16912545]
 [0.80199   ]]
cost : 0.14980190992355347
hypothesis : [[0.00998186]
 [0.1673103 ]
 [0.16902158]
 [0.8021149 ]]
cost : 0.1496952772140503
hypothesis : [[0.00995953]
 [0.16720776]
 [0.16891773]
 [0.8022398 ]]
cost :

 [0.81160074]]
cost : 0.1416524350643158
hypothesis : [[0.0083708 ]
 [0.15940301]
 [0.16101377]
 [0.811719  ]]
cost : 0.14155276119709015
hypothesis : [[0.00835226]
 [0.15930536]
 [0.16091488]
 [0.8118373 ]]
cost : 0.14145314693450928
hypothesis : [[0.00833377]
 [0.15920776]
 [0.16081607]
 [0.8119555 ]]
cost : 0.14135362207889557
hypothesis : [[0.00831533]
 [0.15911026]
 [0.16071735]
 [0.8120737 ]]
cost : 0.14125418663024902
hypothesis : [[0.00829692]
 [0.15901276]
 [0.16061865]
 [0.8121917 ]]
cost : 0.14115484058856964
hypothesis : [[0.00827856]
 [0.15891536]
 [0.16052006]
 [0.81230974]]
cost : 0.14105555415153503
hypothesis : [[0.00826024]
 [0.15881802]
 [0.16042155]
 [0.8124278 ]]
cost : 0.1409563422203064
hypothesis : [[0.00824197]
 [0.15872072]
 [0.16032305]
 [0.8125456 ]]
cost : 0.1408572494983673
hypothesis : [[0.00822373]
 [0.15862347]
 [0.16022465]
 [0.8126633 ]]
cost : 0.14075824618339539
hypothesis : [[0.00820554]
 [0.15852632]
 [0.16012631]
 [0.8127811 ]]
cost : 0.140659287

cost : 0.13282142579555511
hypothesis : [[0.00683459]
 [0.15066801]
 [0.15217197]
 [0.8222788 ]]
cost : 0.13272911310195923
hypothesis : [[0.00681963]
 [0.1505758 ]
 [0.15207863]
 [0.82238996]]
cost : 0.1326368898153305
hypothesis : [[0.00680471]
 [0.15048361]
 [0.15198532]
 [0.8225012 ]]
cost : 0.13254466652870178
hypothesis : [[0.00678982]
 [0.1503915 ]
 [0.15189208]
 [0.8226123 ]]
cost : 0.1324525624513626
hypothesis : [[0.00677496]
 [0.15029946]
 [0.15179892]
 [0.8227233 ]]
cost : 0.1323605328798294
hypothesis : [[0.00676014]
 [0.15020745]
 [0.15170577]
 [0.82283413]]
cost : 0.13226860761642456
hypothesis : [[0.00674536]
 [0.15011549]
 [0.15161271]
 [0.82294494]]
cost : 0.13217675685882568
hypothesis : [[0.00673061]
 [0.15002364]
 [0.15151975]
 [0.8230558 ]]
cost : 0.13208498060703278
hypothesis : [[0.00671589]
 [0.14993177]
 [0.1514268 ]
 [0.82316655]]
cost : 0.13199323415756226
hypothesis : [[0.00670121]
 [0.14984   ]
 [0.15133394]
 [0.82327724]]
cost : 0.1319015622138977
hypothe

hypothesis : [[0.00544995]
 [0.14137752]
 [0.14277165]
 [0.83345735]]
cost : 0.1235286220908165
hypothesis : [[0.00543817]
 [0.14129111]
 [0.1426842 ]
 [0.8335611 ]]
cost : 0.12344388663768768
hypothesis : [[0.00542643]
 [0.14120468]
 [0.14259681]
 [0.83366483]]
cost : 0.12335919588804245
hypothesis : [[0.00541471]
 [0.14111839]
 [0.14250949]
 [0.83376837]]
cost : 0.12327460944652557
hypothesis : [[0.00540301]
 [0.14103216]
 [0.14242226]
 [0.833872  ]]
cost : 0.12319006770849228
hypothesis : [[0.00539135]
 [0.14094593]
 [0.14233503]
 [0.83397555]]
cost : 0.12310557812452316
hypothesis : [[0.00537971]
 [0.14085978]
 [0.14224789]
 [0.83407897]]
cost : 0.1230211853981018
hypothesis : [[0.00536809]
 [0.14077364]
 [0.14216076]
 [0.8341822 ]]
cost : 0.12293687462806702
hypothesis : [[0.00535651]
 [0.1406876 ]
 [0.1420737 ]
 [0.8342855 ]]
cost : 0.12285257130861282
hypothesis : [[0.00534495]
 [0.1406016 ]
 [0.14198673]
 [0.83438873]]
cost : 0.12276839464902878
hypothesis : [[0.00533341]
 [0.1

 [0.8442737 ]]
cost : 0.11475799977779388
hypothesis : [[0.00431213]
 [0.13226923]
 [0.13355936]
 [0.8443703 ]]
cost : 0.11468027532100677
hypothesis : [[0.00430294]
 [0.13218853]
 [0.13347775]
 [0.8444668 ]]
cost : 0.11460259556770325
hypothesis : [[0.00429377]
 [0.13210788]
 [0.1333962 ]
 [0.8445633 ]]
cost : 0.1145249456167221
hypothesis : [[0.00428462]
 [0.13202727]
 [0.13331467]
 [0.8446596 ]]
cost : 0.11444741487503052
hypothesis : [[0.00427548]
 [0.13194673]
 [0.1332332 ]
 [0.8447558 ]]
cost : 0.1143699586391449
hypothesis : [[0.00426638]
 [0.13186625]
 [0.1331518 ]
 [0.84485215]]
cost : 0.11429249495267868
hypothesis : [[0.00425729]
 [0.13178578]
 [0.13307044]
 [0.8449483 ]]
cost : 0.11421513557434082
hypothesis : [[0.00424822]
 [0.1317054 ]
 [0.13298917]
 [0.8450445 ]]
cost : 0.11413782835006714
hypothesis : [[0.00423917]
 [0.13162504]
 [0.1329079 ]
 [0.8451405 ]]
cost : 0.11406057327985764
hypothesis : [[0.00423014]
 [0.13154475]
 [0.1328267 ]
 [0.8452365 ]]
cost : 0.11398340

cost : 0.10858283936977386
hypothesis : [[0.00362297]
 [0.12581843]
 [0.12703678]
 [0.8520746 ]]
cost : 0.10850995033979416
hypothesis : [[0.00361533]
 [0.12574178]
 [0.1269593 ]
 [0.8521658 ]]
cost : 0.10843716561794281
hypothesis : [[0.0036077 ]
 [0.12566522]
 [0.12688188]
 [0.85225725]]
cost : 0.10836435854434967
hypothesis : [[0.00360008]
 [0.12558873]
 [0.12680455]
 [0.8523485 ]]
cost : 0.10829165577888489
hypothesis : [[0.00359249]
 [0.12551224]
 [0.12672721]
 [0.85243976]]
cost : 0.10821899771690369
hypothesis : [[0.00358491]
 [0.12543583]
 [0.12664996]
 [0.8525309 ]]
cost : 0.10814641416072845
hypothesis : [[0.00357734]
 [0.12535942]
 [0.12657273]
 [0.85262185]]
cost : 0.108073890209198
hypothesis : [[0.0035698 ]
 [0.12528309]
 [0.12649557]
 [0.8527129 ]]
cost : 0.10800141096115112
hypothesis : [[0.00356227]
 [0.1252068 ]
 [0.12641844]
 [0.85280395]]
cost : 0.10792896151542664
hypothesis : [[0.00355476]
 [0.12513056]
 [0.12634136]
 [0.85289484]]
cost : 0.10785655677318573
hypot

hypothesis : [[0.00303004]
 [0.11947626]
 [0.12062553]
 [0.85963076]]
cost : 0.10251745581626892
hypothesis : [[0.00302371]
 [0.11940371]
 [0.1205522 ]
 [0.8597172 ]]
cost : 0.10244926810264587
hypothesis : [[0.00301739]
 [0.11933114]
 [0.12047885]
 [0.85980356]]
cost : 0.102381132543087
hypothesis : [[0.00301108]
 [0.11925866]
 [0.12040558]
 [0.85988986]]
cost : 0.10231305658817291
hypothesis : [[0.00300479]
 [0.1191862 ]
 [0.12033235]
 [0.8599761 ]]
cost : 0.102245032787323
hypothesis : [[0.00299852]
 [0.11911381]
 [0.12025918]
 [0.8600623 ]]
cost : 0.10217705368995667
hypothesis : [[0.00299225]
 [0.11904144]
 [0.12018603]
 [0.86014843]]
cost : 0.1021091490983963
hypothesis : [[0.00298601]
 [0.11896912]
 [0.12011293]
 [0.86023444]]
cost : 0.10204127430915833
hypothesis : [[0.00297977]
 [0.11889684]
 [0.12003986]
 [0.8603204 ]]
cost : 0.10197347402572632
hypothesis : [[0.00297355]
 [0.11882462]
 [0.11996688]
 [0.86040634]]
cost : 0.1019057035446167
hypothesis : [[0.00296734]
 [0.11875

hypothesis : [[0.00243573]
 [0.11210094]
 [0.11317142]
 [0.8683977 ]]
cost : 0.09563624858856201
hypothesis : [[0.0024307 ]
 [0.112033  ]
 [0.11310279]
 [0.86847824]]
cost : 0.0955733209848404
hypothesis : [[0.00242568]
 [0.11196516]
 [0.11303423]
 [0.8685588 ]]
cost : 0.09551045298576355
hypothesis : [[0.00242067]
 [0.11189734]
 [0.11296569]
 [0.8686393 ]]
cost : 0.09544762969017029
hypothesis : [[0.00241568]
 [0.11182957]
 [0.11289722]
 [0.86871976]]
cost : 0.09538483619689941
hypothesis : [[0.00241069]
 [0.11176182]
 [0.11282875]
 [0.8688001 ]]
cost : 0.09532210230827332
hypothesis : [[0.00240572]
 [0.11169416]
 [0.11276034]
 [0.86888045]]
cost : 0.0952594205737114
hypothesis : [[0.00240076]
 [0.11162652]
 [0.11269201]
 [0.86896074]]
cost : 0.09519677609205246
hypothesis : [[0.0023958 ]
 [0.11155892]
 [0.11262371]
 [0.86904097]]
cost : 0.0951341986656189
hypothesis : [[0.00239086]
 [0.11149138]
 [0.11255547]
 [0.8691212 ]]
cost : 0.09507166594266891
hypothesis : [[0.00238593]
 [0.11

cost : 0.09010058641433716
hypothesis : [[0.00201597]
 [0.10603237]
 [0.10703927]
 [0.8755956 ]]
cost : 0.09004181623458862
hypothesis : [[0.00201185]
 [0.10596834]
 [0.10697455]
 [0.87567157]]
cost : 0.08998309075832367
hypothesis : [[0.00200774]
 [0.10590435]
 [0.10690994]
 [0.87574726]]
cost : 0.08992445468902588
hypothesis : [[0.00200364]
 [0.10584038]
 [0.1068453 ]
 [0.8758231 ]]
cost : 0.08986581861972809
hypothesis : [[0.00199954]
 [0.1057765 ]
 [0.10678075]
 [0.8758989 ]]
cost : 0.08980722725391388
hypothesis : [[0.00199546]
 [0.1057126 ]
 [0.10671623]
 [0.87597454]]
cost : 0.08974868059158325
hypothesis : [[0.00199139]
 [0.10564879]
 [0.10665176]
 [0.8760501 ]]
cost : 0.08969023823738098
hypothesis : [[0.00198732]
 [0.10558502]
 [0.10658731]
 [0.8761256 ]]
cost : 0.0896318107843399
hypothesis : [[0.00198326]
 [0.10552125]
 [0.10652293]
 [0.8762013 ]]
cost : 0.08957336097955704
hypothesis : [[0.00197921]
 [0.10545754]
 [0.10645854]
 [0.8762766 ]]
cost : 0.08951503038406372
hypo

cost : 0.08482012152671814
hypothesis : [[0.00166842]
 [0.10025021]
 [0.10119739]
 [0.8824431 ]]
cost : 0.08476528525352478
hypothesis : [[0.00166504]
 [0.10018989]
 [0.10113642]
 [0.8825145 ]]
cost : 0.08471053093671799
hypothesis : [[0.00166168]
 [0.10012959]
 [0.10107554]
 [0.8825857 ]]
cost : 0.08465580642223358
hypothesis : [[0.00165832]
 [0.10006932]
 [0.10101468]
 [0.8826571 ]]
cost : 0.08460107445716858
hypothesis : [[0.00165497]
 [0.10000914]
 [0.10095385]
 [0.8827282 ]]
cost : 0.08454647660255432
hypothesis : [[0.00165162]
 [0.09994894]
 [0.10089307]
 [0.8827994 ]]
cost : 0.08449185639619827
hypothesis : [[0.00164829]
 [0.09988882]
 [0.10083235]
 [0.88287055]]
cost : 0.08443727344274521
hypothesis : [[0.00164495]
 [0.09982873]
 [0.10077162]
 [0.8829418 ]]
cost : 0.08438269793987274
hypothesis : [[0.00164163]
 [0.09976867]
 [0.10071097]
 [0.88301265]]
cost : 0.08432825654745102
hypothesis : [[0.00163831]
 [0.09970864]
 [0.10065036]
 [0.88308376]]
cost : 0.08427377045154572
hyp

 [0.888885  ]]
cost : 0.07984016835689545
hypothesis : [[0.0013807 ]
 [0.09474508]
 [0.09563641]
 [0.8889521 ]]
cost : 0.07978902757167816
hypothesis : [[0.00137793]
 [0.0946883 ]
 [0.09557902]
 [0.88901925]]
cost : 0.07973790168762207
hypothesis : [[0.00137517]
 [0.09463149]
 [0.09552166]
 [0.88908625]]
cost : 0.07968684285879135
hypothesis : [[0.00137242]
 [0.09457475]
 [0.09546436]
 [0.88915324]]
cost : 0.07963578402996063
hypothesis : [[0.00136968]
 [0.09451805]
 [0.09540706]
 [0.8892202 ]]
cost : 0.07958479225635529
hypothesis : [[0.00136694]
 [0.09446142]
 [0.09534984]
 [0.88928723]]
cost : 0.07953381538391113
hypothesis : [[0.0013642 ]
 [0.09440478]
 [0.09529264]
 [0.88935405]]
cost : 0.07948289811611176
hypothesis : [[0.00136147]
 [0.09434821]
 [0.09523551]
 [0.889421  ]]
cost : 0.07943200320005417
hypothesis : [[0.00135875]
 [0.09429168]
 [0.09517838]
 [0.8894878 ]]
cost : 0.07938114553689957
hypothesis : [[0.00135604]
 [0.09423517]
 [0.09512132]
 [0.88955456]]
cost : 0.079330

 [0.89424896]]
cost : 0.0757674127817154
hypothesis : [[0.00117237]
 [0.09020603]
 [0.09105153]
 [0.89431256]]
cost : 0.07571924477815628
hypothesis : [[0.00117005]
 [0.09015215]
 [0.09099713]
 [0.8943763 ]]
cost : 0.07567107677459717
hypothesis : [[0.00116772]
 [0.09009827]
 [0.09094271]
 [0.8944399 ]]
cost : 0.07562296837568283
hypothesis : [[0.00116541]
 [0.09004446]
 [0.09088837]
 [0.89450336]]
cost : 0.07557490468025208
hypothesis : [[0.0011631 ]
 [0.08999067]
 [0.09083405]
 [0.8945669 ]]
cost : 0.07552686333656311
hypothesis : [[0.00116079]
 [0.08993687]
 [0.09077971]
 [0.89463025]]
cost : 0.07547885179519653
hypothesis : [[0.00115849]
 [0.08988315]
 [0.09072546]
 [0.89469373]]
cost : 0.07543087005615234
hypothesis : [[0.00115619]
 [0.08982944]
 [0.09067123]
 [0.894757  ]]
cost : 0.07538296282291412
hypothesis : [[0.0011539 ]
 [0.08977582]
 [0.09061702]
 [0.89482033]]
cost : 0.07533504068851471
hypothesis : [[0.00115161]
 [0.08972218]
 [0.09056285]
 [0.89488363]]
cost : 0.0752871

cost : 0.07143214344978333
hypothesis : [[0.00097555]
 [0.08533814]
 [0.0861351 ]
 [0.9000553 ]]
cost : 0.07138711214065552
hypothesis : [[0.00097363]
 [0.08528735]
 [0.08608379]
 [0.9001152 ]]
cost : 0.07134208083152771
hypothesis : [[0.00097172]
 [0.08523658]
 [0.08603253]
 [0.900175  ]]
cost : 0.07129709422588348
hypothesis : [[0.00096981]
 [0.08518588]
 [0.08598132]
 [0.9002349 ]]
cost : 0.07125212252140045
hypothesis : [[0.0009679 ]
 [0.08513517]
 [0.08593011]
 [0.90029454]]
cost : 0.07120721787214279
hypothesis : [[0.000966  ]
 [0.08508454]
 [0.08587896]
 [0.90035427]]
cost : 0.07116234302520752
hypothesis : [[0.00096411]
 [0.08503392]
 [0.08582785]
 [0.900414  ]]
cost : 0.07111745327711105
hypothesis : [[0.00096221]
 [0.08498332]
 [0.08577675]
 [0.90047365]]
cost : 0.07107263058423996
hypothesis : [[0.00096032]
 [0.08493276]
 [0.08572569]
 [0.90053326]]
cost : 0.07102783024311066
hypothesis : [[0.00095844]
 [0.08488221]
 [0.08567464]
 [0.90059286]]
cost : 0.07098304480314255
hyp

hypothesis : [[8.1955997e-04]
 [8.0942810e-02]
 [8.1696264e-02]
 [9.0523529e-01]]
cost : 0.06750357151031494
hypothesis : [[8.1796438e-04]
 [8.0894835e-02]
 [8.1647813e-02]
 [9.0529174e-01]]
cost : 0.06746134161949158
hypothesis : [[8.1637199e-04]
 [8.0846876e-02]
 [8.1599370e-02]
 [9.0534824e-01]]
cost : 0.06741911172866821
hypothesis : [[8.1478304e-04]
 [8.0798939e-02]
 [8.1551000e-02]
 [9.0540481e-01]]
cost : 0.06737688928842545
hypothesis : [[8.1319729e-04]
 [8.0751039e-02]
 [8.1502624e-02]
 [9.0546107e-01]]
cost : 0.06733475625514984
hypothesis : [[8.116149e-04]
 [8.070320e-02]
 [8.145431e-02]
 [9.055176e-01]]
cost : 0.06729260087013245
hypothesis : [[8.100357e-04]
 [8.065535e-02]
 [8.140601e-02]
 [9.055738e-01]]
cost : 0.06725051999092102
hypothesis : [[8.0845988e-04]
 [8.0607556e-02]
 [8.1357740e-02]
 [9.0563011e-01]]
cost : 0.06720844656229019
hypothesis : [[8.0688705e-04]
 [8.0559790e-02]
 [8.1309497e-02]
 [9.0568632e-01]]
cost : 0.06716642528772354
hypothesis : [[8.0531737e-0

 [9.0996492e-01]]
cost : 0.06397731602191925
hypothesis : [[6.922646e-04]
 [7.688080e-02]
 [7.759451e-02]
 [9.100183e-01]]
cost : 0.06393757462501526
hypothesis : [[6.9092854e-04]
 [7.6835386e-02]
 [7.7548653e-02]
 [9.1007185e-01]]
cost : 0.06389781087636948
hypothesis : [[6.8959541e-04]
 [7.6790050e-02]
 [7.7502854e-02]
 [9.1012514e-01]]
cost : 0.06385813653469086
hypothesis : [[6.8826496e-04]
 [7.6744728e-02]
 [7.7457085e-02]
 [9.1017854e-01]]
cost : 0.06381846964359283
hypothesis : [[6.869370e-04]
 [7.669940e-02]
 [7.741133e-02]
 [9.102319e-01]]
cost : 0.063778817653656
hypothesis : [[6.8561186e-04]
 [7.6654129e-02]
 [7.7365614e-02]
 [9.1028512e-01]]
cost : 0.06373924016952515
hypothesis : [[6.842893e-04]
 [7.660889e-02]
 [7.731991e-02]
 [9.103384e-01]]
cost : 0.0636996254324913
hypothesis : [[6.8296975e-04]
 [7.6563664e-02]
 [7.7274278e-02]
 [9.1039175e-01]]
cost : 0.06366002559661865
hypothesis : [[6.816526e-04]
 [7.651847e-02]
 [7.722866e-02]
 [9.104449e-01]]
cost : 0.06362051516

cost : 0.06073334068059921
hypothesis : [[5.8896624e-04]
 [7.3166795e-02]
 [7.3844314e-02]
 [9.1438854e-01]]
cost : 0.06069585680961609
hypothesis : [[5.8783899e-04]
 [7.3123768e-02]
 [7.3800854e-02]
 [9.1443920e-01]]
cost : 0.06065838038921356
hypothesis : [[5.8671390e-04]
 [7.3080756e-02]
 [7.3757425e-02]
 [9.1448975e-01]]
cost : 0.06062096357345581
hypothesis : [[5.855913e-04]
 [7.303778e-02]
 [7.371404e-02]
 [9.145403e-01]]
cost : 0.06058357283473015
hypothesis : [[5.8447081e-04]
 [7.2994821e-02]
 [7.3670685e-02]
 [9.1459084e-01]]
cost : 0.06054618954658508
hypothesis : [[5.833524e-04]
 [7.295188e-02]
 [7.362732e-02]
 [9.146413e-01]]
cost : 0.060508839786052704
hypothesis : [[5.8223651e-04]
 [7.2909005e-02]
 [7.3584013e-02]
 [9.1469175e-01]]
cost : 0.06047150492668152
hypothesis : [[5.8112264e-04]
 [7.2866119e-02]
 [7.3540732e-02]
 [9.1474211e-01]]
cost : 0.060434240847826004
hypothesis : [[5.800113e-04]
 [7.282329e-02]
 [7.349750e-02]
 [9.147926e-01]]
cost : 0.06039692461490631
hy

hypothesis : [[5.094298e-04]
 [6.997308e-02]
 [7.061963e-02]
 [9.181443e-01]]
cost : 0.05792231857776642
hypothesis : [[5.0846179e-04]
 [6.9932073e-02]
 [7.0578210e-02]
 [9.1819245e-01]]
cost : 0.05788680166006088
hypothesis : [[5.0749577e-04]
 [6.9891110e-02]
 [7.0536837e-02]
 [9.1824067e-01]]
cost : 0.05785126984119415
hypothesis : [[5.0653162e-04]
 [6.9850147e-02]
 [7.0495486e-02]
 [9.1828871e-01]]
cost : 0.05781581997871399
hypothesis : [[5.0556962e-04]
 [6.9809228e-02]
 [7.0454195e-02]
 [9.1833687e-01]]
cost : 0.05778035521507263
hypothesis : [[5.046093e-04]
 [6.976834e-02]
 [7.041289e-02]
 [9.183850e-01]]
cost : 0.05774490535259247
hypothesis : [[5.0365087e-04]
 [6.9727443e-02]
 [7.0371605e-02]
 [9.1843301e-01]]
cost : 0.057709529995918274
hypothesis : [[5.026945e-04]
 [6.968659e-02]
 [7.033038e-02]
 [9.184810e-01]]
cost : 0.057674165815114975
hypothesis : [[5.0173997e-04]
 [6.9645762e-02]
 [7.0289142e-02]
 [9.1852903e-01]]
cost : 0.05763878673315048
hypothesis : [[5.0078722e-04]

cost : 0.05532478541135788
hypothesis : [[4.4109483e-04]
 [6.6929504e-02]
 [6.7546725e-02]
 [9.2172134e-01]]
cost : 0.0552910715341568
hypothesis : [[4.4026258e-04]
 [6.6890411e-02]
 [6.7507267e-02]
 [9.2176729e-01]]
cost : 0.055257342755794525
hypothesis : [[4.3943216e-04]
 [6.6851370e-02]
 [6.7467839e-02]
 [9.2181319e-01]]
cost : 0.05522364750504494
hypothesis : [[4.3860334e-04]
 [6.6812359e-02]
 [6.7428418e-02]
 [9.2185909e-01]]
cost : 0.055189989507198334
hypothesis : [[4.3777609e-04]
 [6.6773325e-02]
 [6.7389034e-02]
 [9.2190486e-01]]
cost : 0.055156342685222626
hypothesis : [[4.3695062e-04]
 [6.6734351e-02]
 [6.7349695e-02]
 [9.2195070e-01]]
cost : 0.0551227331161499
hypothesis : [[4.3612666e-04]
 [6.6695400e-02]
 [6.7310348e-02]
 [9.2199647e-01]]
cost : 0.05508912727236748
hypothesis : [[4.3530428e-04]
 [6.6656470e-02]
 [6.7271024e-02]
 [9.2204219e-01]]
cost : 0.05505555123090744
hypothesis : [[4.3448366e-04]
 [6.6617556e-02]
 [6.7231752e-02]
 [9.2208791e-01]]
cost : 0.055022008

 [9.2578250e-01]]
cost : 0.05231600999832153
hypothesis : [[3.7102168e-04]
 [6.3435487e-02]
 [6.4019099e-02]
 [9.2582583e-01]]
cost : 0.05228433385491371
hypothesis : [[3.7032765e-04]
 [6.3398615e-02]
 [6.3981883e-02]
 [9.2586917e-01]]
cost : 0.052252668887376785
hypothesis : [[3.696349e-04]
 [6.336176e-02]
 [6.394468e-02]
 [9.259125e-01]]
cost : 0.05222102254629135
hypothesis : [[3.6894344e-04]
 [6.3324921e-02]
 [6.3907474e-02]
 [9.2595565e-01]]
cost : 0.05218944698572159
hypothesis : [[3.6825353e-04]
 [6.3288108e-02]
 [6.3870311e-02]
 [9.2599887e-01]]
cost : 0.05215783417224884
hypothesis : [[3.6756488e-04]
 [6.3251317e-02]
 [6.3833177e-02]
 [9.2604208e-01]]
cost : 0.05212627351284027
hypothesis : [[3.6687765e-04]
 [6.3214570e-02]
 [6.3796081e-02]
 [9.2608523e-01]]
cost : 0.052094727754592896
hypothesis : [[3.6619170e-04]
 [6.3177839e-02]
 [6.3758984e-02]
 [9.2612839e-01]]
cost : 0.05206320434808731
hypothesis : [[3.6550706e-04]
 [6.3141108e-02]
 [6.3721903e-02]
 [9.2617154e-01]]
cos

cost : 0.04996899887919426
hypothesis : [[3.2196255e-04]
 [6.0697950e-02]
 [6.1255440e-02]
 [9.2904001e-01]]
cost : 0.04993889853358269
hypothesis : [[3.2136420e-04]
 [6.0662776e-02]
 [6.1219942e-02]
 [9.2908126e-01]]
cost : 0.04990881681442261
hypothesis : [[3.2076702e-04]
 [6.0627617e-02]
 [6.1184432e-02]
 [9.2912245e-01]]
cost : 0.04987877979874611
hypothesis : [[3.2017127e-04]
 [6.0592514e-02]
 [6.1149001e-02]
 [9.2916363e-01]]
cost : 0.0498487763106823
hypothesis : [[3.1957659e-04]
 [6.0557429e-02]
 [6.1113592e-02]
 [9.2920488e-01]]
cost : 0.04981875792145729
hypothesis : [[3.1898302e-04]
 [6.0522366e-02]
 [6.1078195e-02]
 [9.2924607e-01]]
cost : 0.04978877305984497
hypothesis : [[3.1839058e-04]
 [6.0487319e-02]
 [6.1042786e-02]
 [9.2928725e-01]]
cost : 0.04975879192352295
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.3199606],
       [5.3102283]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-8.053773], dtype=fl

 [9.3229961e-01]]
cost : 0.04756833240389824
hypothesis : [[2.7657449e-04]
 [5.7887077e-02]
 [5.8417846e-02]
 [9.3233877e-01]]
cost : 0.04753986746072769
hypothesis : [[2.7606421e-04]
 [5.7853669e-02]
 [5.8384128e-02]
 [9.3237793e-01]]
cost : 0.04751143231987953
hypothesis : [[2.7555512e-04]
 [5.7820305e-02]
 [5.8350448e-02]
 [9.3241709e-01]]
cost : 0.04748300090432167
hypothesis : [[2.7504697e-04]
 [5.7786964e-02]
 [5.8316790e-02]
 [9.3245631e-01]]
cost : 0.04745456576347351
hypothesis : [[2.7453975e-04]
 [5.7753641e-02]
 [5.8283150e-02]
 [9.3249536e-01]]
cost : 0.04742620140314102
hypothesis : [[2.7403349e-04]
 [5.7720330e-02]
 [5.8249529e-02]
 [9.3253446e-01]]
cost : 0.04739783704280853
hypothesis : [[2.7352816e-04]
 [5.7687037e-02]
 [5.8215905e-02]
 [9.3257356e-01]]
cost : 0.047369472682476044
hypothesis : [[2.7302370e-04]
 [5.7653740e-02]
 [5.8182288e-02]
 [9.3261254e-01]]
cost : 0.04734113812446594
hypothesis : [[2.7252047e-04]
 [5.7620510e-02]
 [5.8148745e-02]
 [9.3265158e-01]]


cost : 0.045458342880010605
hypothesis : [[2.4047271e-04]
 [5.5407647e-02]
 [5.5914924e-02]
 [9.3524784e-01]]
cost : 0.04543125629425049
hypothesis : [[2.4003194e-04]
 [5.5375788e-02]
 [5.5882763e-02]
 [9.3528503e-01]]
cost : 0.04540426284074783
hypothesis : [[2.3959202e-04]
 [5.5343941e-02]
 [5.5850618e-02]
 [9.3532234e-01]]
cost : 0.04537723585963249
hypothesis : [[2.3915293e-04]
 [5.5312123e-02]
 [5.5818491e-02]
 [9.3535972e-01]]
cost : 0.045350201427936554
hypothesis : [[2.3871461e-04]
 [5.5280313e-02]
 [5.5786382e-02]
 [9.3539697e-01]]
cost : 0.04532322660088539
hypothesis : [[2.3827735e-04]
 [5.5248566e-02]
 [5.5754345e-02]
 [9.3543428e-01]]
cost : 0.04529626667499542
hypothesis : [[2.3784085e-04]
 [5.5216819e-02]
 [5.5722289e-02]
 [9.3547153e-01]]
cost : 0.04526929557323456
hypothesis : [[2.3740521e-04]
 [5.5185087e-02]
 [5.5690262e-02]
 [9.3550867e-01]]
cost : 0.04524239897727966
hypothesis : [[2.3697030e-04]
 [5.5153366e-02]
 [5.5658247e-02]
 [9.3554580e-01]]
cost : 0.04521549

cost : 0.042992040514945984
hypothesis : [[2.0251989e-04]
 [5.2498832e-02]
 [5.2978639e-02]
 [9.3865883e-01]]
cost : 0.04296661913394928
hypothesis : [[2.0215161e-04]
 [5.2468788e-02]
 [5.2948315e-02]
 [9.3869388e-01]]
cost : 0.04294125735759735
hypothesis : [[2.0178397e-04]
 [5.2438758e-02]
 [5.2918002e-02]
 [9.3872917e-01]]
cost : 0.04291583597660065
hypothesis : [[2.0141702e-04]
 [5.2408747e-02]
 [5.2887700e-02]
 [9.3876439e-01]]
cost : 0.04289044812321663
hypothesis : [[2.0105092e-04]
 [5.2378777e-02]
 [5.2857451e-02]
 [9.3879950e-01]]
cost : 0.04286512732505798
hypothesis : [[2.0068551e-04]
 [5.2348815e-02]
 [5.2827213e-02]
 [9.3883467e-01]]
cost : 0.04283978417515755
hypothesis : [[2.0032075e-04]
 [5.2318882e-02]
 [5.2796997e-02]
 [9.3886977e-01]]
cost : 0.042814478278160095
hypothesis : [[1.9995663e-04]
 [5.2288953e-02]
 [5.2766789e-02]
 [9.3890488e-01]]
cost : 0.04278917238116264
hypothesis : [[1.9959320e-04]
 [5.2259047e-02]
 [5.2736603e-02]
 [9.3893999e-01]]
cost : 0.04276386

hypothesis : [[1.7675036e-04]
 [5.0296664e-02]
 [5.0755747e-02]
 [9.4124037e-01]]
cost : 0.04110705852508545
hypothesis : [[1.7643093e-04]
 [5.0267998e-02]
 [5.0726809e-02]
 [9.4127393e-01]]
cost : 0.04108290746808052
hypothesis : [[1.7611208e-04]
 [5.0239343e-02]
 [5.0697882e-02]
 [9.4130754e-01]]
cost : 0.0410587303340435
hypothesis : [[1.7579383e-04]
 [5.0210707e-02]
 [5.0668970e-02]
 [9.4134110e-01]]
cost : 0.04103458300232887
hypothesis : [[1.7547615e-04]
 [5.0182082e-02]
 [5.0640080e-02]
 [9.4137472e-01]]
cost : 0.041010454297065735
hypothesis : [[1.7515903e-04]
 [5.0153453e-02]
 [5.0611179e-02]
 [9.4140822e-01]]
cost : 0.0409863255918026
hypothesis : [[1.7484248e-04]
 [5.0124835e-02]
 [5.0582297e-02]
 [9.4144160e-01]]
cost : 0.040962230414152145
hypothesis : [[1.7452669e-04]
 [5.0096281e-02]
 [5.0553475e-02]
 [9.4147521e-01]]
cost : 0.040938135236501694
hypothesis : [[1.7421148e-04]
 [5.0067745e-02]
 [5.0524671e-02]
 [9.4150871e-01]]
cost : 0.040914054960012436
hypothesis : [[1.

 [9.4443727e-01]]
cost : 0.03881102055311203
hypothesis : [[1.4786990e-04]
 [4.7541775e-02]
 [4.7974914e-02]
 [9.4446886e-01]]
cost : 0.038788359612226486
hypothesis : [[1.4760478e-04]
 [4.7514815e-02]
 [4.7947697e-02]
 [9.4450057e-01]]
cost : 0.03876565396785736
hypothesis : [[1.4734014e-04]
 [4.7487866e-02]
 [4.7920495e-02]
 [9.4453216e-01]]
cost : 0.03874300420284271
hypothesis : [[1.4707596e-04]
 [4.7460936e-02]
 [4.7893312e-02]
 [9.4456369e-01]]
cost : 0.03872039169073105
hypothesis : [[1.4681225e-04]
 [4.7434017e-02]
 [4.7866143e-02]
 [9.4459528e-01]]
cost : 0.038697779178619385
hypothesis : [[1.4654903e-04]
 [4.7407091e-02]
 [4.7838964e-02]
 [9.4462681e-01]]
cost : 0.03867517039179802
hypothesis : [[1.4628629e-04]
 [4.7380187e-02]
 [4.7811795e-02]
 [9.4465828e-01]]
cost : 0.03865257650613785
hypothesis : [[1.4602400e-04]
 [4.7353290e-02]
 [4.7784649e-02]
 [9.4468975e-01]]
cost : 0.038629982620477676
hypothesis : [[1.4576233e-04]
 [4.7326449e-02]
 [4.7757559e-02]
 [9.4472128e-01]

cost : 0.03710690140724182
hypothesis : [[1.2883342e-04]
 [4.5512080e-02]
 [4.5926236e-02]
 [9.4684690e-01]]
cost : 0.037085309624671936
hypothesis : [[1.2860377e-04]
 [4.5486361e-02]
 [4.5900274e-02]
 [9.4687700e-01]]
cost : 0.037063777446746826
hypothesis : [[1.2837455e-04]
 [4.5460660e-02]
 [4.5874324e-02]
 [9.4690716e-01]]
cost : 0.03704221919178963
hypothesis : [[1.2814571e-04]
 [4.5434963e-02]
 [4.5848392e-02]
 [9.4693732e-01]]
cost : 0.03702067583799362
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.9279237],
       [5.918432 ]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-8.963999], dtype=float32)>
Grads :  [<tf.Tensor: id=290195, shape=(2, 1), dtype=float32, numpy=
array([[-0.00180357],
       [-0.00190693]], dtype=float32)>, <tf.Tensor: id=290193, shape=(1,), dtype=float32, numpy=array([0.00958721], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA5A7C08>
hypothesis : [[1.2791729e-04]
 [4.5409

hypothesis : [[1.13741924e-04]
 [4.37481143e-02]
 [4.41458412e-02]
 [9.48912859e-01]]
cost : 0.03560897335410118
hypothesis : [[1.13540154e-04]
 [4.37234491e-02]
 [4.41209376e-02]
 [9.48941767e-01]]
cost : 0.0355883464217186
hypothesis : [[1.1333884e-04]
 [4.3698832e-02]
 [4.4096086e-02]
 [9.4897062e-01]]
cost : 0.03556778281927109
hypothesis : [[1.13137896e-04]
 [4.36742082e-02]
 [4.40712534e-02]
 [9.48999524e-01]]
cost : 0.0355471707880497
hypothesis : [[1.1293730e-04]
 [4.3649595e-02]
 [4.4046406e-02]
 [9.4902825e-01]]
cost : 0.03552662581205368
hypothesis : [[1.1273705e-04]
 [4.3625001e-02]
 [4.4021577e-02]
 [9.4905716e-01]]
cost : 0.035506028681993484
hypothesis : [[1.1253717e-04]
 [4.3600414e-02]
 [4.3996762e-02]
 [9.4908595e-01]]
cost : 0.03548547998070717
hypothesis : [[1.12337635e-04]
 [4.35758494e-02]
 [4.39719632e-02]
 [9.49114740e-01]]
cost : 0.03546493500471115
hypothesis : [[1.1213846e-04]
 [4.3551270e-02]
 [4.3947168e-02]
 [9.4914347e-01]]
cost : 0.03544440492987633
hypo

 [9.5103037e-01]]
cost : 0.034099020063877106
hypothesis : [[9.9423982e-05]
 [4.1916348e-02]
 [4.2297039e-02]
 [9.5105797e-01]]
cost : 0.034079380333423615
hypothesis : [[9.9248646e-05]
 [4.1892823e-02]
 [4.2273290e-02]
 [9.5108557e-01]]
cost : 0.034059733152389526
hypothesis : [[9.9073623e-05]
 [4.1869301e-02]
 [4.2249549e-02]
 [9.5111305e-01]]
cost : 0.03404013067483902
hypothesis : [[9.8898898e-05]
 [4.1845784e-02]
 [4.2225823e-02]
 [9.5114070e-01]]
cost : 0.03402049466967583
hypothesis : [[9.8724500e-05]
 [4.1822273e-02]
 [4.2202089e-02]
 [9.5116818e-01]]
cost : 0.03400089219212532
hypothesis : [[9.8550394e-05]
 [4.1798778e-02]
 [4.2178370e-02]
 [9.5119560e-01]]
cost : 0.0339813232421875
hypothesis : [[9.8376600e-05]
 [4.1775290e-02]
 [4.2154662e-02]
 [9.5122308e-01]]
cost : 0.03396173566579819
hypothesis : [[9.8203207e-05]
 [4.1751858e-02]
 [4.2131007e-02]
 [9.5125055e-01]]
cost : 0.03394220024347305
hypothesis : [[9.8030119e-05]
 [4.1728415e-02]
 [4.2107362e-02]
 [9.5127797e-01]]

hypothesis : [[8.4120606e-05]
 [3.9742433e-02]
 [4.0102899e-02]
 [9.5360309e-01]]
cost : 0.03226868808269501
hypothesis : [[8.3973209e-05]
 [3.9720204e-02]
 [4.0080462e-02]
 [9.5362914e-01]]
cost : 0.03225020319223404
hypothesis : [[8.3826082e-05]
 [3.9697982e-02]
 [4.0058028e-02]
 [9.5365512e-01]]
cost : 0.03223172202706337
hypothesis : [[8.3679210e-05]
 [3.9675776e-02]
 [4.0035609e-02]
 [9.5368117e-01]]
cost : 0.0322132371366024
hypothesis : [[8.3532672e-05]
 [3.9653599e-02]
 [4.0013239e-02]
 [9.5370704e-01]]
cost : 0.032194819301366806
hypothesis : [[8.3386389e-05]
 [3.9631434e-02]
 [3.9990861e-02]
 [9.5373309e-01]]
cost : 0.03217635303735733
hypothesis : [[8.3240368e-05]
 [3.9609276e-02]
 [3.9968498e-02]
 [9.5375901e-01]]
cost : 0.032157935202121735
hypothesis : [[8.3094601e-05]
 [3.9587140e-02]
 [3.9946146e-02]
 [9.5378494e-01]]
cost : 0.03213951736688614
hypothesis : [[8.2949089e-05]
 [3.9565004e-02]
 [3.9923806e-02]
 [9.5381081e-01]]
cost : 0.03212112933397293
hypothesis : [[8.2

cost : 0.03100244328379631
hypothesis : [[7.429604e-05]
 [3.819728e-02]
 [3.854341e-02]
 [9.554117e-01]]
cost : 0.030984751880168915
hypothesis : [[7.416650e-05]
 [3.817598e-02]
 [3.852191e-02]
 [9.554366e-01]]
cost : 0.030967077240347862
hypothesis : [[7.4037176e-05]
 [3.8154695e-02]
 [3.8500421e-02]
 [9.5546138e-01]]
cost : 0.03094944916665554
hypothesis : [[7.3908093e-05]
 [3.8133405e-02]
 [3.8478948e-02]
 [9.5548630e-01]]
cost : 0.030931776389479637
hypothesis : [[7.3779302e-05]
 [3.8112160e-02]
 [3.8457517e-02]
 [9.5551121e-01]]
cost : 0.03091413341462612
hypothesis : [[7.3650728e-05]
 [3.8090926e-02]
 [3.8436081e-02]
 [9.5553607e-01]]
cost : 0.03089650720357895
hypothesis : [[7.3522388e-05]
 [3.8069703e-02]
 [3.8414657e-02]
 [9.5556098e-01]]
cost : 0.030878879129886627
hypothesis : [[7.3394265e-05]
 [3.8048495e-02]
 [3.8393244e-02]
 [9.5558578e-01]]
cost : 0.030861269682645798
hypothesis : [[7.3266376e-05]
 [3.8027298e-02]
 [3.8371846e-02]
 [9.5561063e-01]]
cost : 0.0308436602354

 [9.5735872e-01]]
cost : 0.029605116695165634
hypothesis : [[6.4528176e-05]
 [3.6513340e-02]
 [3.6843881e-02]
 [9.5738244e-01]]
cost : 0.029588326811790466
hypothesis : [[6.4416279e-05]
 [3.6493044e-02]
 [3.6823411e-02]
 [9.5740616e-01]]
cost : 0.029571520164608955
hypothesis : [[6.4304586e-05]
 [3.6472764e-02]
 [3.6802933e-02]
 [9.5742989e-01]]
cost : 0.029554715380072594
hypothesis : [[6.4193067e-05]
 [3.6452495e-02]
 [3.6782470e-02]
 [9.5745361e-01]]
cost : 0.02953791245818138
hypothesis : [[6.408182e-05]
 [3.643227e-02]
 [3.676205e-02]
 [9.574773e-01]]
cost : 0.029521171003580093
hypothesis : [[6.3970750e-05]
 [3.6412053e-02]
 [3.6741640e-02]
 [9.5750093e-01]]
cost : 0.02950441464781761
hypothesis : [[6.3859887e-05]
 [3.6391824e-02]
 [3.6721248e-02]
 [9.5752460e-01]]
cost : 0.029487673193216324
hypothesis : [[6.3749205e-05]
 [3.6371615e-02]
 [3.6700860e-02]
 [9.5754826e-01]]
cost : 0.029470931738615036
hypothesis : [[6.3638727e-05]
 [3.6351416e-02]
 [3.6680464e-02]
 [9.5757192e-01]

 [9.5900977e-01]]
cost : 0.028437133878469467
hypothesis : [[5.7063713e-05]
 [3.5102941e-02]
 [3.5420440e-02]
 [9.5903248e-01]]
cost : 0.028421049937605858
hypothesis : [[5.6965247e-05]
 [3.5083517e-02]
 [3.5400826e-02]
 [9.5905524e-01]]
cost : 0.028404980897903442
hypothesis : [[5.6866957e-05]
 [3.5064101e-02]
 [3.5381228e-02]
 [9.5907795e-01]]
cost : 0.028388917446136475
hypothesis : [[5.6768837e-05]
 [3.5044700e-02]
 [3.5361640e-02]
 [9.5910066e-01]]
cost : 0.028372865170240402
hypothesis : [[5.6670877e-05]
 [3.5025291e-02]
 [3.5342060e-02]
 [9.5912337e-01]]
cost : 0.028356831520795822
hypothesis : [[5.6573092e-05]
 [3.5005890e-02]
 [3.5322495e-02]
 [9.5914608e-01]]
cost : 0.0283407811075449
hypothesis : [[5.6475477e-05]
 [3.4986500e-02]
 [3.5302918e-02]
 [9.5916879e-01]]
cost : 0.028324762359261513
hypothesis : [[5.6378030e-05]
 [3.4967124e-02]
 [3.5283357e-02]
 [9.5919138e-01]]
cost : 0.028308745473623276
hypothesis : [[5.6280744e-05]
 [3.4947753e-02]
 [3.5263803e-02]
 [9.5921403e

cost : 0.027288801968097687
hypothesis : [[5.0317798e-05]
 [3.3713896e-02]
 [3.4018569e-02]
 [9.6065760e-01]]
cost : 0.027273375540971756
hypothesis : [[5.0231352e-05]
 [3.3695292e-02]
 [3.3999786e-02]
 [9.6067935e-01]]
cost : 0.02725803107023239
hypothesis : [[5.0145060e-05]
 [3.3676680e-02]
 [3.3981010e-02]
 [9.6070105e-01]]
cost : 0.027242686599493027
hypothesis : [[5.0058916e-05]
 [3.3658080e-02]
 [3.3962250e-02]
 [9.6072280e-01]]
cost : 0.027227338403463364
hypothesis : [[4.9972921e-05]
 [3.3639491e-02]
 [3.3943478e-02]
 [9.6074450e-01]]
cost : 0.02721199207007885
hypothesis : [[4.9887072e-05]
 [3.3620909e-02]
 [3.3924725e-02]
 [9.6076620e-01]]
cost : 0.02719666250050068
hypothesis : [[4.9801416e-05]
 [3.3602368e-02]
 [3.3906009e-02]
 [9.6078795e-01]]
cost : 0.027181347832083702
hypothesis : [[4.9715909e-05]
 [3.3583838e-02]
 [3.3887297e-02]
 [9.6080965e-01]]
cost : 0.027166035026311874
hypothesis : [[4.9630547e-05]
 [3.3565305e-02]
 [3.3868603e-02]
 [9.6083134e-01]]
cost : 0.0271

cost : 0.02592783421278
hypothesis : [[4.3048603e-05]
 [3.2064546e-02]
 [3.2354020e-02]
 [9.6258658e-01]]
cost : 0.025913286954164505
hypothesis : [[4.2975062e-05]
 [3.2046910e-02]
 [3.2336213e-02]
 [9.6260720e-01]]
cost : 0.0258987694978714
hypothesis : [[4.2901636e-05]
 [3.2029286e-02]
 [3.2318417e-02]
 [9.6262777e-01]]
cost : 0.025884252041578293
hypothesis : [[4.2828342e-05]
 [3.2011665e-02]
 [3.2300632e-02]
 [9.6264845e-01]]
cost : 0.025869736447930336
hypothesis : [[4.2755175e-05]
 [3.1994045e-02]
 [3.2282859e-02]
 [9.6266896e-01]]
cost : 0.02585521899163723
hypothesis : [[4.2682175e-05]
 [3.1976461e-02]
 [3.2265119e-02]
 [9.6268964e-01]]
cost : 0.025840718299150467
hypothesis : [[4.2609292e-05]
 [3.1958885e-02]
 [3.2247391e-02]
 [9.6271020e-01]]
cost : 0.025826234370470047
hypothesis : [[4.2536540e-05]
 [3.1941324e-02]
 [3.2229658e-02]
 [9.6273077e-01]]
cost : 0.02581176534295082
hypothesis : [[4.2463915e-05]
 [3.1923763e-02]
 [3.2211933e-02]
 [9.6275127e-01]]
cost : 0.025797314

cost : 0.02466827630996704
hypothesis : [[3.6986879e-05]
 [3.0535109e-02]
 [3.0810501e-02]
 [9.6437520e-01]]
cost : 0.024654492735862732
hypothesis : [[3.6924044e-05]
 [3.0518387e-02]
 [3.0793620e-02]
 [9.6439481e-01]]
cost : 0.024640725925564766
hypothesis : [[3.6861311e-05]
 [3.0501673e-02]
 [3.0776745e-02]
 [9.6441436e-01]]
cost : 0.024626972153782845
hypothesis : [[3.6798690e-05]
 [3.0484969e-02]
 [3.0759880e-02]
 [9.6443385e-01]]
cost : 0.02461325004696846
hypothesis : [[3.6736172e-05]
 [3.0468274e-02]
 [3.0743022e-02]
 [9.6445346e-01]]
cost : 0.024599500000476837
hypothesis : [[3.6673766e-05]
 [3.0451572e-02]
 [3.0726176e-02]
 [9.6447301e-01]]
cost : 0.024585777893662453
hypothesis : [[3.6611462e-05]
 [3.0434877e-02]
 [3.0709337e-02]
 [9.6449250e-01]]
cost : 0.024572040885686874
hypothesis : [[3.6549260e-05]
 [3.0418195e-02]
 [3.0692507e-02]
 [9.6451193e-01]]
cost : 0.02455836534500122
hypothesis : [[3.6487167e-05]
 [3.0401519e-02]
 [3.0675674e-02]
 [9.6453142e-01]]
cost : 0.0245

hypothesis : [[3.2074207e-05]
 [2.9163277e-02]
 [2.9426044e-02]
 [9.6597922e-01]]
cost : 0.023527424782514572
hypothesis : [[3.2019954e-05]
 [2.9147336e-02]
 [2.9409966e-02]
 [9.6599782e-01]]
cost : 0.023514337837696075
hypothesis : [[3.1965803e-05]
 [2.9131407e-02]
 [2.9393893e-02]
 [9.6601647e-01]]
cost : 0.023501265794038773
w:  <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[6.8548074],
       [6.845567 ]], dtype=float32)>
b:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-10.352504], dtype=float32)>
Grads :  [<tf.Tensor: id=345443, shape=(2, 1), dtype=float32, numpy=
array([[-0.00114741],
       [-0.00121303]], dtype=float32)>, <tf.Tensor: id=345441, shape=(1,), dtype=float32, numpy=array([0.00614343], dtype=float32)>]
zip(grads, [w, b]) <zip object at 0x00000184CA5AF888>


## 모델을 활용한 예측 값

In [14]:
predict = tf.sigmoid(tf.matmul(X, W) + b)
predict

<tf.Tensor: id=345467, shape=(4, 1), dtype=float32, numpy=
array([[3.1911768e-05],
       [2.9115507e-02],
       [2.9377848e-02],
       [9.6603507e-01]], dtype=float32)>

## 0~1사이의 값을 이진분류 하기 위해 0.5를 기준으로 분류

In [15]:
predict01 = tf.cast(predict >0.5, dtype="float32")
predict01

<tf.Tensor: id=345471, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)>

## equal 함수를 통해 같은지 비교하고(True or False로 나옴)
## 비교된 값을 숫자로 변경(0 또는 1로 변경)
## 평균을 통해 정확도를 계산

In [16]:
accuracy= tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype="float32"))
accuracy

<tf.Tensor: id=345477, shape=(), dtype=float32, numpy=1.0>

In [17]:
arr = np.array([[0.5, 0.3]], dtype="float32")
arr

array([[0.5, 0.3]], dtype=float32)

In [18]:
predict = tf.sigmoid(tf.matmul(arr, W) + b)
predict

<tf.Tensor: id=345484, shape=(1, 1), dtype=float32, numpy=array([[0.00760413]], dtype=float32)>

In [19]:
tf.cast(predict >0.5, dtype="float32")

<tf.Tensor: id=345488, shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>

In [26]:
arr = np.array([[0.75, 0.8]], dtype="float32")
predict = tf.sigmoid(tf.matmul(arr, W) + b)
tf.cast(predict >0.5, dtype="float32")

<tf.Tensor: id=345558, shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>