In [1]:
from math import e

## 선형회귀의 값은 현재 -5 부분에 들어간다
## 해당 식은 시그모이드 함수의 식이다
## 선형회귀된 값을 0~1사이의 값으로 변환시켜주는 함수이다

In [2]:
1/(1+e**-(-5))

0.006692850924284857

## 인공 신경망을 이용한 AND 연산 예시

In [3]:
import numpy as np
import tensorflow as tf

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

## 텐서플로우가 기존 그래프 기반 방식에서 벗어나 그래프 생성 없이 연산을 즉시 실행하는 명령형 프로그래밍 환경을 뜻

## 텐서플로우의 기존 방식은 그래프(텐서의 연산 흐름)을 구성한 후 sess.run() 함수를 통해서 연산이 수행되는 방식인데 이 방식을 제거하고, python과 같은 즉시 실행 방식을 사용하는 것

In [4]:
tf.enable_eager_execution()

In [5]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype="float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [6]:
y = np.array([[0], [0], [0], [1]], dtype="float32")
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [7]:
w = np.array([[1], [2]], dtype="float32")
w

array([[1.],
       [2.]], dtype=float32)

In [8]:
b = np.array([3], dtype="float32")
b

array([3.], dtype=float32)

In [9]:
X.dot(w)

array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)

In [10]:
def sigmoid(h):
    return 1/(1+np.exp(-h))

In [11]:
hypothesis  = sigmoid(X.dot(w) + b)
hypothesis

array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)

In [12]:
hypothesis-y

array([[ 0.95257413],
       [ 0.9933072 ],
       [ 0.98201376],
       [-0.00247258]], dtype=float32)

In [13]:
learning_rate = 0.1
for i in range(100):
    for j in range(2):
        hypothesis = sigmoid(np.dot(X, w) + b)
        print(f'hypothesis = {hypothesis}')
        cost = -1/4 * (y * np.log(hypothesis) + (1 - y)*np.log(hypothesis))
        print(f'cost = {cost}')
        
        X_col_2d = X.T[j].reshape(1, -1)
        w_grad = 1/4 * np.sum(np.dot(X_col_2d, hypothesis-y))
        print(f"w{j}_grad : {w_grad}")
        
        w[j] -= learning_rate*w_grad
        print(f"w{j} : {w[j]}")
        
        
        b_grad = 1/4 * np.sum(hypothesis-y)
        print(f"b{j}_grad : {b_grad}")
        b -= learning_rate * b_grad
        print(f"b{j} : {b}")

hypothesis = [[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]]
cost = [[0.01214684]
 [0.00167883]
 [0.00453749]
 [0.00061891]]
w0_grad : 0.24488529562950134
w0 : [0.9755115]
b0_grad : 0.731355607509613
b0 : [2.9268644]
hypothesis = [[0.94915855]
 [0.9928029 ]
 [0.9802059 ]
 [0.99727446]]
cost = [[0.01304486]
 [0.00180578]
 [0.00499816]
 [0.00068232]]
w1_grad : 0.2475193440914154
w1 : [1.9752481]
b1_grad : 0.7298604249954224
b1 : [2.8538783]
hypothesis = [[0.94551885]
 [0.9920699 ]
 [0.97873896]
 [0.99699557]]
cost = [[0.01400536]
 [0.00199043]
 [0.00537258]
 [0.00075224]]
w0_grad : 0.24393363296985626
w0 : [0.9511181]
b0_grad : 0.7283308506011963
b0 : [2.7810452]
hypothesis = [[0.94164294]
 [0.99147594]
 [0.9766187 ]
 [0.9966897 ]]
cost = [[0.01503228]
 [0.00214015]
 [0.00591474]
 [0.00082895]]
w1_grad : 0.24704140424728394
w1 : [1.950544]
b1_grad : 0.7266068458557129
b1 : [2.7083845]
hypothesis = [[0.93751955]
 [0.9906123 ]
 [0.9749009 ]
 [0.99635243]]
cost = [[0.01612942]
 [0.

 [0.5126466 ]]
cost = [[0.48172435]
 [0.24198417]
 [0.3713778 ]
 [0.16704214]]
w0_grad : -0.06524170190095901
w0 : [0.54723847]
b0_grad : 0.06612460315227509
b0 : [-1.7761549]
hypothesis = [[0.14477858]
 [0.37830955]
 [0.22637114]
 [0.51262456]]
cost = [[0.48313743]
 [0.24301063]
 [0.37139484]
 [0.1670529 ]]
w1_grad : -0.027266472578048706
w1 : [1.282152]
b1_grad : 0.06552095711231232
b1 : [-1.782707]
hypothesis = [[0.14396921]
 [0.3774103 ]
 [0.22522573]
 [0.5116688 ]]
cost = [[0.48453897]
 [0.2436056 ]
 [0.37266302]
 [0.16751944]]
w0_grad : -0.06577636301517487
w0 : [0.5538161]
b0_grad : 0.06456850469112396
b0 : [-1.7891638]
hypothesis = [[0.14317527]
 [0.3758943 ]
 [0.22524683]
 [0.5116989 ]]
cost = [[0.4859214 ]
 [0.24461181]
 [0.37263963]
 [0.16750473]]
w1_grad : -0.02810169756412506
w1 : [1.2849622]
b1_grad : 0.0640038251876831
b1 : [-1.7955642]
hypothesis = [[0.1423919 ]
 [0.3750524 ]
 [0.22413185]
 [0.51080185]]
cost = [[0.48729303]
 [0.24517238]
 [0.3738802 ]
 [0.16794339]]
w0

In [14]:
predict = np.dot(X, w) + b
predict

array([[-2.0687358 ],
       [-0.6896328 ],
       [-1.3285887 ],
       [ 0.05051446]], dtype=float32)

## 위의 것의 값이 잘 안나오는데 그 이유가 sigmoid를 안써서

In [15]:
predict = sigmoid(np.dot(X, w) + b)
predict

array([[0.11217288],
       [0.33411476],
       [0.2093929 ],
       [0.51262593]], dtype=float32)

In [16]:
predict01 = tf.cast(predict > 0.5, dtype=tf.float32)
predict01

<tf.Tensor: id=1, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)>