In [1]:
import numpy as np
import tensorflow as tf

tf.enable_eager_execution()

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

In [2]:
X = np.array([
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 0],
    [0, 1]
], dtype="float32")
X

array([[0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.]], dtype=float32)

In [3]:
y = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0],
    [0, 1, 0]
], dtype="float32")
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [30]:
initializer = tf.contrib.layers.xavier_initializer()

In [31]:
w0 = tf.Variable(initializer([2, 10]), dtype="float32")
w0

<tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[-0.00272793, -0.41669443, -0.32377696,  0.5351493 ,  0.5864703 ,
        -0.65503824,  0.46397227, -0.03348482,  0.06629699, -0.6419944 ],
       [ 0.23707771,  0.16185486,  0.15977585,  0.48515373, -0.21161443,
         0.44529372, -0.42673278,  0.19301385, -0.17093533,  0.27160543]],
      dtype=float32)>

In [32]:
b0 = tf.Variable(initializer([10]), dtype="float32")
b0

<tf.Variable 'Variable:0' shape=(10,) dtype=float32, numpy=
array([ 0.4083612 ,  0.07336432, -0.32162514,  0.20200843, -0.4589213 ,
       -0.2754969 ,  0.30662   , -0.27029392,  0.13666123,  0.25415605],
      dtype=float32)>

In [33]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=1035435, shape=(5, 10), dtype=float32, numpy=
array([[0.60069484, 0.51833284, 0.42027974, 0.55033106, 0.38724178,
        0.43155813, 0.57606   , 0.43283495, 0.5341122 , 0.56319916],
       [0.6000404 , 0.4150008 , 0.34402642, 0.676374  , 0.5318441 ,
        0.28281617, 0.68364894, 0.424634  , 0.5505661 , 0.4042378 ],
       [0.655366  , 0.4547553 , 0.38092446, 0.77247006, 0.478996  ,
        0.38101524, 0.5851277 , 0.47233707, 0.508005  , 0.47097445],
       [0.60069484, 0.51833284, 0.42027974, 0.55033106, 0.38724178,
        0.43155813, 0.57606   , 0.43283495, 0.5341122 , 0.56319916],
       [0.6559819 , 0.55853516, 0.45962578, 0.66533536, 0.3383769 ,
        0.5423475 , 0.47000787, 0.4806896 , 0.4914323 , 0.62849396]],
      dtype=float32)>

In [34]:
w1 = tf.Variable(initializer([10, 3]), dtype="float32")
w1

<tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
array([[ 0.341012  , -0.26197422,  0.15254343],
       [ 0.63387764, -0.6354581 , -0.43001446],
       [ 0.12393194, -0.29741693, -0.26070353],
       [ 0.18418092,  0.6258116 , -0.15785551],
       [ 0.57794297, -0.17227018,  0.2222426 ],
       [ 0.23499477, -0.34115335, -0.1932992 ],
       [-0.09719402,  0.06752354, -0.1587438 ],
       [-0.6122899 , -0.5259203 , -0.06745094],
       [ 0.12978613,  0.28394365, -0.15583682],
       [ 0.17407781,  0.61283636,  0.26188445]], dtype=float32)>

In [35]:
tf.matmul(hypothesis0, w1)

<tf.Tensor: id=1035453, shape=(5, 3), dtype=float32, numpy=
array([[ 0.8584187 , -0.17321025, -0.38144028],
       [ 0.8241066 , -0.06115179, -0.336954  ],
       [ 0.8694389 , -0.07906766, -0.3645932 ],
       [ 0.8584187 , -0.17321025, -0.38144028],
       [ 0.913441  , -0.1867826 , -0.4136232 ]], dtype=float32)>

In [36]:
b1 = tf.Variable(initializer([3]), dtype="float32")
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-0.03354764, -0.8022914 ,  0.65436816], dtype=float32)>

In [37]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=1035474, shape=(5, 3), dtype=float32, numpy=
array([[0.5743604 , 0.09490575, 0.3307338 ],
       [0.5511699 , 0.10542933, 0.34340078],
       [0.5685843 , 0.10209455, 0.32932112],
       [0.5743604 , 0.09490575, 0.3307338 ],
       [0.59452164, 0.09172453, 0.31375384]], dtype=float32)>

## 위의 경우 xavier 방식으로 weight를 정해줬는데, 이전의 경우 상수 값인 (1~20) 정도의 숫자로 weight를 초기화했었다
## 그럴 경우, local minimum 인 곳에 정착하게 되어 정확도가 0.8밖에 안나오는 경우가 발생
## 왠만해선 임의이 값이 아닌 xavier 함수를 통해서 초기화를 해주는 것이 좋다

## Gradient 방식으로 학습하기

In [38]:
optimizer = tf.train.AdamOptimizer(0.1)

In [39]:
for epoch in range(3000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
#         print("hypothesis0 = ", hypothesis0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)
#         print("hypothesis1 = ", hypothesis1)
        
        cost = -tf.reduce_sum(y * (tf.log(hypothesis1))) / len(hypothesis1)
        print("cost : ", cost)
        grads = tape.gradient(cost, [w0, w1, b0, b1])
#         print("grads : ", grads)
        optimizer.apply_gradients(
            grads_and_vars=zip(grads, [w0, w1, b0, b1]))

cost :  tf.Tensor(1.3716797, shape=(), dtype=float32)
cost :  tf.Tensor(1.052744, shape=(), dtype=float32)
cost :  tf.Tensor(1.0724491, shape=(), dtype=float32)
cost :  tf.Tensor(1.1177953, shape=(), dtype=float32)
cost :  tf.Tensor(1.044274, shape=(), dtype=float32)
cost :  tf.Tensor(0.9486295, shape=(), dtype=float32)
cost :  tf.Tensor(0.8926576, shape=(), dtype=float32)
cost :  tf.Tensor(0.8712568, shape=(), dtype=float32)
cost :  tf.Tensor(0.8525171, shape=(), dtype=float32)
cost :  tf.Tensor(0.8193356, shape=(), dtype=float32)
cost :  tf.Tensor(0.77104247, shape=(), dtype=float32)
cost :  tf.Tensor(0.7136866, shape=(), dtype=float32)
cost :  tf.Tensor(0.6549642, shape=(), dtype=float32)
cost :  tf.Tensor(0.60159934, shape=(), dtype=float32)
cost :  tf.Tensor(0.5568762, shape=(), dtype=float32)
cost :  tf.Tensor(0.51933795, shape=(), dtype=float32)
cost :  tf.Tensor(0.48455706, shape=(), dtype=float32)
cost :  tf.Tensor(0.44910312, shape=(), dtype=float32)
cost :  tf.Tensor(0.41293

cost :  tf.Tensor(0.0042416393, shape=(), dtype=float32)
cost :  tf.Tensor(0.0042026504, shape=(), dtype=float32)
cost :  tf.Tensor(0.00416419, shape=(), dtype=float32)
cost :  tf.Tensor(0.004126258, shape=(), dtype=float32)
cost :  tf.Tensor(0.004088891, shape=(), dtype=float32)
cost :  tf.Tensor(0.0040520173, shape=(), dtype=float32)
cost :  tf.Tensor(0.00401572, shape=(), dtype=float32)
cost :  tf.Tensor(0.0039798794, shape=(), dtype=float32)
cost :  tf.Tensor(0.003944603, shape=(), dtype=float32)
cost :  tf.Tensor(0.0039098198, shape=(), dtype=float32)
cost :  tf.Tensor(0.0038754568, shape=(), dtype=float32)
cost :  tf.Tensor(0.0038416344, shape=(), dtype=float32)
cost :  tf.Tensor(0.0038082567, shape=(), dtype=float32)
cost :  tf.Tensor(0.0037752627, shape=(), dtype=float32)
cost :  tf.Tensor(0.0037427857, shape=(), dtype=float32)
cost :  tf.Tensor(0.0037107407, shape=(), dtype=float32)
cost :  tf.Tensor(0.0036791402, shape=(), dtype=float32)
cost :  tf.Tensor(0.003647936, shape=(

cost :  tf.Tensor(0.0015464727, shape=(), dtype=float32)
cost :  tf.Tensor(0.0015384469, shape=(), dtype=float32)
cost :  tf.Tensor(0.0015303975, shape=(), dtype=float32)
cost :  tf.Tensor(0.0015224672, shape=(), dtype=float32)
cost :  tf.Tensor(0.0015145611, shape=(), dtype=float32)
cost :  tf.Tensor(0.0015067745, shape=(), dtype=float32)
cost :  tf.Tensor(0.001499, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014913449, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014836899, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014760827, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014685474, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014611313, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014537154, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014463713, shape=(), dtype=float32)
cost :  tf.Tensor(0.001439051, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014318981, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014246975, shape=(), dtype=float32)
cost :  tf.Tensor(0.0014175683, shap

cost :  tf.Tensor(0.0007051355, shape=(), dtype=float32)
cost :  tf.Tensor(0.00070267776, shape=(), dtype=float32)
cost :  tf.Tensor(0.0007002916, shape=(), dtype=float32)
cost :  tf.Tensor(0.00069794117, shape=(), dtype=float32)
cost :  tf.Tensor(0.00069557887, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006931926, shape=(), dtype=float32)
cost :  tf.Tensor(0.00069086615, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006885277, shape=(), dtype=float32)
cost :  tf.Tensor(0.000686237, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006838986, shape=(), dtype=float32)
cost :  tf.Tensor(0.000681584, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006793172, shape=(), dtype=float32)
cost :  tf.Tensor(0.00067702646, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006747597, shape=(), dtype=float32)
cost :  tf.Tensor(0.00067249296, shape=(), dtype=float32)
cost :  tf.Tensor(0.0006702499, shape=(), dtype=float32)
cost :  tf.Tensor(0.00066806667, shape=(), dtype=float32)
cost :  tf.Tensor(0.000665

cost :  tf.Tensor(0.00039510583, shape=(), dtype=float32)
cost :  tf.Tensor(0.000394104, shape=(), dtype=float32)
cost :  tf.Tensor(0.000393126, shape=(), dtype=float32)
cost :  tf.Tensor(0.00039214804, shape=(), dtype=float32)
cost :  tf.Tensor(0.0003911104, shape=(), dtype=float32)
cost :  tf.Tensor(0.00039018015, shape=(), dtype=float32)
cost :  tf.Tensor(0.0003892022, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038822423, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038724623, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038626828, shape=(), dtype=float32)
cost :  tf.Tensor(0.000385338, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038436003, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038342975, shape=(), dtype=float32)
cost :  tf.Tensor(0.0003824518, shape=(), dtype=float32)
cost :  tf.Tensor(0.0003815454, shape=(), dtype=float32)
cost :  tf.Tensor(0.00038056745, shape=(), dtype=float32)
cost :  tf.Tensor(0.00037963717, shape=(), dtype=float32)
cost :  tf.Tensor(0.0003

cost :  tf.Tensor(0.00027250947, shape=(), dtype=float32)
cost :  tf.Tensor(0.00027191328, shape=(), dtype=float32)
cost :  tf.Tensor(0.00027138856, shape=(), dtype=float32)
cost :  tf.Tensor(0.0002707446, shape=(), dtype=float32)
cost :  tf.Tensor(0.00027021993, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026967138, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026912283, shape=(), dtype=float32)
cost :  tf.Tensor(0.0002685743, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026799, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026744144, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026691676, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026632054, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026579582, shape=(), dtype=float32)
cost :  tf.Tensor(0.0002652831, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026468685, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026416214, shape=(), dtype=float32)
cost :  tf.Tensor(0.00026366132, shape=(), dtype=float32)
cost :  tf.Tensor(0.

cost :  tf.Tensor(0.00020282366, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020248978, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020206053, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020175052, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020136897, shape=(), dtype=float32)
cost :  tf.Tensor(0.0002009874, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020065354, shape=(), dtype=float32)
cost :  tf.Tensor(0.00020024813, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019991426, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019953269, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019919881, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019884112, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019853111, shape=(), dtype=float32)
cost :  tf.Tensor(0.0001981257, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019781567, shape=(), dtype=float32)
cost :  tf.Tensor(0.0001974341, shape=(), dtype=float32)
cost :  tf.Tensor(0.00019710025, shape=(), dtype=float32)
cost :  tf.Tensor

cost :  tf.Tensor(0.00015341274, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015317427, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015291198, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015262581, shape=(), dtype=float32)
cost :  tf.Tensor(0.0001524112, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015217274, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015195811, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015169581, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015145735, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015124274, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015099235, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015075388, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015051542, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015030082, shape=(), dtype=float32)
cost :  tf.Tensor(0.00015003848, shape=(), dtype=float32)
cost :  tf.Tensor(0.00014980005, shape=(), dtype=float32)
cost :  tf.Tensor(0.00014960926, shape=(), dtype=float32)
cost :  tf.Tens

cost :  tf.Tensor(0.00012135205, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012113744, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012099438, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012082745, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012063668, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012046976, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012027901, shape=(), dtype=float32)
cost :  tf.Tensor(0.00012013594, shape=(), dtype=float32)
cost :  tf.Tensor(0.000119969016, shape=(), dtype=float32)
cost :  tf.Tensor(0.000119778255, shape=(), dtype=float32)
cost :  tf.Tensor(0.00011963518, shape=(), dtype=float32)
cost :  tf.Tensor(0.00011946827, shape=(), dtype=float32)
cost :  tf.Tensor(0.000119253666, shape=(), dtype=float32)
cost :  tf.Tensor(0.00011911059, shape=(), dtype=float32)
cost :  tf.Tensor(0.00011896752, shape=(), dtype=float32)
cost :  tf.Tensor(0.000118752905, shape=(), dtype=float32)
cost :  tf.Tensor(0.000118586, shape=(), dtype=float32)
cost :  tf.T

cost :  tf.Tensor(9.341769e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.329846e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.3179246e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.3083865e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.29408e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.282158e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.27262e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.2583134e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.248775e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.2344686e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.2249305e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.213008e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.2010865e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.189164e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.179626e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.165319e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.155782e-05, shape=(), dtype=float32)
cost :  tf.Tensor(9.14386e-

cost :  tf.Tensor(7.293547e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.286394e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.276856e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.272088e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.2577815e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.253012e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.24586e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.236322e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.231553e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.214862e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.212478e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.2029405e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.193403e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.1862494e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.1790964e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.167175e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.1624054e-05, shape=(), dtype=float32)
cost :  tf.Tensor(7.155253e

cost :  tf.Tensor(6.096589e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0870516e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0798986e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0775143e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0703613e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.063208e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0560553e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0489016e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0465176e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0393642e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.027443e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0250582e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0202892e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0083683e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.005983e-05, shape=(), dtype=float32)
cost :  tf.Tensor(6.0012146e-05, shape=(), dtype=float32)
cost :  tf.Tensor(5.994062e-05, shape=(), dtype=float32)
cost :  tf.Tensor(5

cost :  tf.Tensor(5.021249e-05, shape=(), dtype=float32)
cost :  tf.Tensor(5.0093273e-05, shape=(), dtype=float32)
cost :  tf.Tensor(5.0069426e-05, shape=(), dtype=float32)
cost :  tf.Tensor(5.0021743e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.99979e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9950206e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.987868e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.983099e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9783306e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9735623e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9664093e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9616407e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.956872e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.952103e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9497186e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9425656e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9377973e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.9

cost :  tf.Tensor(4.2606505e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2582666e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.255882e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2534975e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2439606e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.239192e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2368076e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2368076e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.232039e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2225012e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.217733e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2153486e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2153486e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.21058e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.2081956e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.201043e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.19389e-05, shape=(), dtype=float32)
cost :  tf.Tensor(4.191

cost :  tf.Tensor(3.6073525e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.6002e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.593047e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5906625e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5906625e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.588278e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.588278e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5811252e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.578741e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5739726e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5692035e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5692035e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5668192e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.562051e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5596666e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.557282e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.554898e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.5501

cost :  tf.Tensor(3.0136662e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.0136662e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.0088977e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.0088977e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.0088977e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.004129e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.004129e-05, shape=(), dtype=float32)
cost :  tf.Tensor(3.0017449e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9969766e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.992208e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9898238e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9874394e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9874394e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9826706e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9826706e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9802864e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.9779021e-05, shape=(), dtype=float32)
cost :  tf.Tensor

cost :  tf.Tensor(2.6631786e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6607944e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6607944e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6584103e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6584103e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6584103e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6560261e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6560261e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6536418e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6488731e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6417203e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6393362e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6393362e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.636952e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.636952e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.636952e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.6345679e-05, shape=(), dtype=float32)
cost :  tf.Tensor

cost :  tf.Tensor(2.2888502e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2840817e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2816976e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2816976e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2816976e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2816976e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.276929e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.276929e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2721606e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2697763e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2697763e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2673921e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.265008e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2626236e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2626236e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2626236e-05, shape=(), dtype=float32)
cost :  tf.Tensor(2.2602393e-05, shape=(), dtype=float32)
cost :  tf.Tensor

In [40]:
hypo0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypo1 = tf.nn.softmax(tf.matmul(hypo0, w1) + b1)
hypo2= tf.argmax(hypo1, axis=1)
hypo2

<tf.Tensor: id=1290574, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 1], dtype=int64)>

In [41]:
target = tf.argmax(y, 1)
target

<tf.Tensor: id=1290578, shape=(5,), dtype=int64, numpy=array([0, 1, 2, 0, 1], dtype=int64)>

In [42]:
tf.reduce_mean(tf.cast(tf.equal(hypo2, target), dtype="float32"))

<tf.Tensor: id=1290583, shape=(), dtype=float32, numpy=1.0>