# PCA

In [1]:
import pandas as pd
import numpy as np

In [24]:
data = {"x1":[10, 20],
       "x2":[20, 5]
       }
df = pd.DataFrame(data)
df

x1  x2
0  10  20
1  20   5

In [25]:
np.cov(df)

array([[ 50. , -75. ],
       [-75. , 112.5]])

In [26]:
df.mean()

x1    15.0
x2    12.5
dtype: float64

In [27]:
df = df-df.mean()
df

x1   x2
0 -5.0  7.5
1  5.0 -7.5

In [35]:
np.cov(df.T)

array([[ 50. , -75. ],
       [-75. , 112.5]])

In [29]:
df.cov()

x1     x2
x1  50.0  -75.0
x2 -75.0  112.5

In [34]:
np.dot(df.T, df)

array([[ 50. , -75. ],
       [-75. , 112.5]])

## PCA 예제

In [11]:
data = {
    "calory":[1.2, 2.8, 5, 3, 4.5, 2.],
    "breakfast":[0, 3, 5, 2, 7, 5],
    "lunch":[4, 5, 7, 6, 7, 3],
    "dinner":[5, 6, 7, 6, 7, 6],
    "weight":[65, 75, 100, 71, 97, 60]
}

In [12]:
df = pd.DataFrame(data)
df

calory  breakfast  lunch  dinner  weight
0     1.2          0      4       5      65
1     2.8          3      5       6      75
2     5.0          5      7       7     100
3     3.0          2      6       6      71
4     4.5          7      7       7      97
5     2.0          5      3       6      60

In [13]:
y = df["weight"]
y

0     65
1     75
2    100
3     71
4     97
5     60
Name: weight, dtype: int64

In [14]:
df = df.drop(["weight"], axis = 1)
df

calory  breakfast  lunch  dinner
0     1.2          0      4       5
1     2.8          3      5       6
2     5.0          5      7       7
3     3.0          2      6       6
4     4.5          7      7       7
5     2.0          5      3       6

In [18]:
X = df
X

calory  breakfast     lunch    dinner
0 -1.883333  -3.666667 -1.333333 -1.166667
1 -0.283333  -0.666667 -0.333333 -0.166667
2  1.916667   1.333333  1.666667  0.833333
3 -0.083333  -1.666667  0.666667 -0.166667
4  1.416667   3.333333  1.666667  0.833333
5 -1.083333   1.333333 -2.333333 -0.166667

In [19]:
X_cen = X - X.mean()
X_cen

calory  breakfast     lunch    dinner
0 -1.883333  -3.666667 -1.333333 -1.166667
1 -0.283333  -0.666667 -0.333333 -0.166667
2  1.916667   1.333333  1.666667  0.833333
3 -0.083333  -1.666667  0.666667 -0.166667
4  1.416667   3.333333  1.666667  0.833333
5 -1.083333   1.333333 -2.333333 -0.166667

In [20]:
X_cen.mean()

calory       0.000000e+00
breakfast   -3.700743e-17
lunch        0.000000e+00
dinner      -4.625929e-18
dtype: float64

In [39]:
X_cov = np.cov(X_cen.T)
X_cov

array([[2.09766667, 2.61333333, 2.12666667, 1.04333333],
       [2.61333333, 6.26666667, 1.73333333, 1.66666667],
       [2.12666667, 1.73333333, 2.66666667, 0.93333333],
       [1.04333333, 1.66666667, 0.93333333, 0.56666667]])

- 고유값 : 축의 길이
- 고유벡터 : 좌표

In [40]:
eigenvalue, eigenvector = np.linalg.eig(X_cov)
print("eigenvalue : ", eigenvalue)
print("eigenvector : \n", eigenvector)

eigenvalue :  [9.14780875e+00 2.36702072e+00 8.08883672e-02 1.94882794e-03]
eigenvector : 
 [[ 0.43937091  0.34911627 -0.7283658  -0.39313393]
 [ 0.77295605 -0.58010996  0.23904478 -0.09417519]
 [ 0.3862551   0.73448569  0.55523568  0.05523686]
 [ 0.24555883  0.04605465 -0.32257433  0.91297625]]


In [41]:
sum(eigenvalue)

11.597666666666676

In [42]:
eigenvalue[0]

9.147808752147373

In [43]:
eigenvalue[0]/sum(eigenvalue)

0.7887628619676975

In [44]:
eigenvector.T

array([[ 0.43937091,  0.77295605,  0.3862551 ,  0.24555883],
       [ 0.34911627, -0.58010996,  0.73448569,  0.04605465],
       [-0.7283658 ,  0.23904478,  0.55523568, -0.32257433],
       [-0.39313393, -0.09417519,  0.05523686,  0.91297625]])

In [45]:
eigenvector.T[0]

array([0.43937091, 0.77295605, 0.3862551 , 0.24555883])

In [46]:
projected_X = X_cov.dot(eigenvector.T[0])
projected_X

array([4.0192811 , 7.07085414, 3.53338781, 2.24632517])