In [1]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import numpy as np

Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing

In [2]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype="float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [3]:
y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype="float32")
y

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

## 모델 초기화

In [15]:
model = Sequential()

## 레이어 1 추가 (2, 2)

In [5]:
model.add(Dense(2, input_dim=2, activation="sigmoid"))

Instructions for updating:
Colocations handled automatically by placer.


## 레이어 2 추가 (2, 1)

In [6]:
model.add(Dense(1, input_dim=2, activation="sigmoid"))

## 레이어 확인

In [7]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers[0].get_weights()

[array([[-1.0054748 ,  0.0892539 ],
        [ 1.158768  , -0.09636497]], dtype=float32),
 array([0., 0.], dtype=float32)]

## 학습방법 초기화

In [9]:
model.compile(loss = "binary_crossentropy", optimizer=Adam(lr=0.01), metrics=['acc'])

## 학습 수행

In [10]:
model.fit(X, y, epochs=500)

Instructions for updating:
Use tf.cast instead.
Epoch 1/500
4/4 [==============================] - 0s 51ms/step - loss: 0.7624 - acc: 0.5000
Epoch 2/500
4/4 [==============================] - 0s 748us/step - loss: 0.7582 - acc: 0.5000
Epoch 3/500
4/4 [==============================] - 0s 498us/step - loss: 0.7547 - acc: 0.5000
Epoch 4/500
4/4 [==============================] - 0s 499us/step - loss: 0.7511 - acc: 0.5000
Epoch 5/500
4/4 [==============================] - 0s 499us/step - loss: 0.7473 - acc: 0.5000
Epoch 6/500
4/4 [==============================] - 0s 498us/step - loss: 0.7439 - acc: 0.5000
Epoch 7/500
4/4 [==============================] - 0s 498us/step - loss: 0.7405 - acc: 0.5000
Epoch 8/500
4/4 [==============================] - 0s 250us/step - loss: 0.7374 - acc: 0.5000
Epoch 9/500
4/4 [==============================] - 0s 997us/step - loss: 0.7344 - acc: 0.5000
Epoch 10/500
4/4 [==============================] - 0s 249us/step - loss: 0.7316 - acc: 0.5000
Epoch 11/500

Epoch 85/500
4/4 [==============================] - 0s 499us/step - loss: 0.6934 - acc: 0.5000
Epoch 86/500
4/4 [==============================] - 0s 499us/step - loss: 0.6934 - acc: 0.5000
Epoch 87/500
4/4 [==============================] - 0s 499us/step - loss: 0.6933 - acc: 0.5000
Epoch 88/500
4/4 [==============================] - 0s 499us/step - loss: 0.6933 - acc: 0.5000
Epoch 89/500
4/4 [==============================] - 0s 249us/step - loss: 0.6932 - acc: 0.5000
Epoch 90/500
4/4 [==============================] - 0s 499us/step - loss: 0.6932 - acc: 0.5000
Epoch 91/500
4/4 [==============================] - 0s 499us/step - loss: 0.6931 - acc: 0.5000
Epoch 92/500
4/4 [==============================] - 0s 249us/step - loss: 0.6931 - acc: 0.5000
Epoch 93/500
4/4 [==============================] - 0s 748us/step - loss: 0.6931 - acc: 0.5000
Epoch 94/500
4/4 [==============================] - 0s 499us/step - loss: 0.6930 - acc: 0.5000
Epoch 95/500
4/4 [==============================] 

Epoch 171/500
4/4 [==============================] - 0s 250us/step - loss: 0.6888 - acc: 0.5000
Epoch 172/500
4/4 [==============================] - 0s 250us/step - loss: 0.6887 - acc: 0.5000
Epoch 173/500
4/4 [==============================] - 0s 499us/step - loss: 0.6886 - acc: 0.5000
Epoch 174/500
4/4 [==============================] - 0s 499us/step - loss: 0.6885 - acc: 0.5000
Epoch 175/500
4/4 [==============================] - 0s 249us/step - loss: 0.6884 - acc: 0.5000
Epoch 176/500
4/4 [==============================] - 0s 499us/step - loss: 0.6882 - acc: 0.5000
Epoch 177/500
4/4 [==============================] - 0s 499us/step - loss: 0.6881 - acc: 0.5000
Epoch 178/500
4/4 [==============================] - 0s 249us/step - loss: 0.6880 - acc: 0.5000
Epoch 179/500
4/4 [==============================] - 0s 499us/step - loss: 0.6878 - acc: 0.5000
Epoch 180/500
4/4 [==============================] - 0s 249us/step - loss: 0.6877 - acc: 0.5000
Epoch 181/500
4/4 [=====================

Epoch 257/500
4/4 [==============================] - 0s 499us/step - loss: 0.6608 - acc: 0.7500
Epoch 258/500
4/4 [==============================] - 0s 249us/step - loss: 0.6602 - acc: 0.7500
Epoch 259/500
4/4 [==============================] - 0s 249us/step - loss: 0.6595 - acc: 0.7500
Epoch 260/500
4/4 [==============================] - 0s 499us/step - loss: 0.6589 - acc: 0.7500
Epoch 261/500
4/4 [==============================] - 0s 249us/step - loss: 0.6582 - acc: 0.7500
Epoch 262/500
4/4 [==============================] - 0s 249us/step - loss: 0.6575 - acc: 0.7500
Epoch 263/500
4/4 [==============================] - 0s 249us/step - loss: 0.6568 - acc: 0.7500
Epoch 264/500
4/4 [==============================] - 0s 250us/step - loss: 0.6561 - acc: 0.7500
Epoch 265/500
4/4 [==============================] - 0s 250us/step - loss: 0.6554 - acc: 0.7500
Epoch 266/500
4/4 [==============================] - 0s 249us/step - loss: 0.6547 - acc: 0.7500
Epoch 267/500
4/4 [=====================

Epoch 343/500
4/4 [==============================] - 0s 496us/step - loss: 0.5193 - acc: 1.0000
Epoch 344/500
4/4 [==============================] - 0s 249us/step - loss: 0.5160 - acc: 1.0000
Epoch 345/500
4/4 [==============================] - 0s 499us/step - loss: 0.5128 - acc: 1.0000
Epoch 346/500
4/4 [==============================] - 0s 249us/step - loss: 0.5096 - acc: 1.0000
Epoch 347/500
4/4 [==============================] - 0s 249us/step - loss: 0.5063 - acc: 1.0000
Epoch 348/500
4/4 [==============================] - 0s 499us/step - loss: 0.5030 - acc: 1.0000
Epoch 349/500
4/4 [==============================] - 0s 499us/step - loss: 0.4997 - acc: 1.0000
Epoch 350/500
4/4 [==============================] - 0s 499us/step - loss: 0.4964 - acc: 1.0000
Epoch 351/500
4/4 [==============================] - 0s 499us/step - loss: 0.4931 - acc: 1.0000
Epoch 352/500
4/4 [==============================] - 0s 748us/step - loss: 0.4898 - acc: 1.0000
Epoch 353/500
4/4 [=====================

Epoch 429/500
4/4 [==============================] - 0s 499us/step - loss: 0.2806 - acc: 1.0000
Epoch 430/500
4/4 [==============================] - 0s 249us/step - loss: 0.2788 - acc: 1.0000
Epoch 431/500
4/4 [==============================] - 0s 249us/step - loss: 0.2769 - acc: 1.0000
Epoch 432/500
4/4 [==============================] - 0s 249us/step - loss: 0.2750 - acc: 1.0000
Epoch 433/500
4/4 [==============================] - 0s 499us/step - loss: 0.2732 - acc: 1.0000
Epoch 434/500
4/4 [==============================] - 0s 249us/step - loss: 0.2714 - acc: 1.0000
Epoch 435/500
4/4 [==============================] - 0s 748us/step - loss: 0.2696 - acc: 1.0000
Epoch 436/500
4/4 [==============================] - 0s 499us/step - loss: 0.2678 - acc: 1.0000
Epoch 437/500
4/4 [==============================] - 0s 249us/step - loss: 0.2661 - acc: 1.0000
Epoch 438/500
4/4 [==============================] - 0s 499us/step - loss: 0.2643 - acc: 1.0000
Epoch 439/500
4/4 [=====================

In [11]:
pred = model.predict(X)
pred

array([[0.16076943],
       [0.82030004],
       [0.8215588 ],
       [0.1490485 ]], dtype=float32)

In [12]:
pred01 = np.where(pred> 0.5, 1, 0)
pred01

array([[0],
       [1],
       [1],
       [0]])

In [13]:
pred02 = (y == pred01)
pred02

array([[ True],
       [ True],
       [ True],
       [ True]])

## 정확도 체크

In [14]:
acc = np,sum(pred02)/len(pred02)
acc

(<module 'numpy' from 'c:\\library\\python\\lib\\site-packages\\numpy\\__init__.py'>,
 array([1.]))