In [1]:
import numpy as np

weight = np.array([88, 76, 56, 73, 77, 57])
weight

array([88, 76, 56, 73, 77, 57])

In [2]:
mean = np.mean(weight)
mean

71.16666666666667

In [4]:
residual = weight-mean
residual

array([ 16.83333333,   4.83333333, -15.16666667,   1.83333333,
         5.83333333, -14.16666667])

In [15]:
residual2 = weight - (mean + 0.1 * residual)
residual2

array([ 15.15,   4.35, -13.65,   1.65,   5.25, -12.75])

In [18]:
residual3 = weight - residual + (0.1*residual + 0.1 * residual2)
residual3

array([74.365, 72.085, 68.285, 71.515, 72.275, 68.475])