In [1]:
import numpy as np

## 1개의 셀로만 이루어져 있는 경우

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
X = np.array([[h]], dtype=np.float32)
X.shape

(1, 1, 4)

In [4]:
W1 = np.array([
    [1],
    [2],
    [3],
    [4],
], dtype="float32")
W1.shape

(4, 1)

In [5]:
b1 = np.array([5], dtype="float32")
b1

array([5.], dtype=float32)

In [6]:
z0 = np.dot(X, W1) + b1
z0.shape

(1, 1, 1)

In [7]:
h0 = np.tanh(z0)
h0

array([[[0.9999877]]], dtype=float32)

## 2개의 셀로 이루어져 있는 경우

In [8]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [9]:
X = np.array([[h], [e]], dtype=np.float32)
X.shape

(2, 1, 4)

In [10]:
W1 = np.array([
    [1],
    [2],
    [3],
    [4],
], dtype="float32")
W1.shape

(4, 1)

In [11]:
b1 = np.array([5], dtype="float32")
b1

array([5.], dtype=float32)

In [12]:
W2 = np.array(
    [.1],
    dtype="float32")
W2.shape

(1,)

In [13]:
z0 = np.dot(X[0], W1) + b1
z0.shape

(1, 1)

In [14]:
h0 = np.tanh(z0)
h0

array([[0.9999877]], dtype=float32)

In [15]:
z1 = np.dot(X[1], W1) + b1
z1.shape

(1, 1)

In [16]:
h1 = z1 + np.dot(h0, W2)
h1 = np.tanh(h1)
h1

array([[0.9999986]], dtype=float32)

## Simple RNN을 활용한 자동 완성

In [17]:
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from keras.optimizers import Adam
import numpy as np

Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing

In [18]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [19]:
X = np.array([h, e, l, l], dtype="float32")

In [20]:
model = Sequential()
model.add(SimpleRNN(units=4, input_shape=(4, 4)))
model.add(Dense(4, activation="softmax"))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 4)                 36        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20        
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(loss = "categorical_crossentropy", optimizer=Adam(lr=0.1), metrics=['acc'])

In [22]:
y = np.array([o], dtype="float32")

In [23]:

model.fit(X.reshape(-1, 4, 4), y, epochs=50)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
1/1 [==============================] - 0s 355ms/step - loss: 1.5047 - acc: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6978 - acc: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 0.3391 - acc: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 2ms/step - loss: 0.1842 - acc: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 0.0992 - acc: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 997us/step - loss: 0.0542 - acc: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 3ms/step - loss: 0.0307 - acc: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 998us/step - loss: 0.0182 - acc: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0112 - acc: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0073 - acc: 1.0000
Epoch 11/50
1/1 [==============

In [30]:
model.layers[0].get_weights()

[array([[ 0.0566489 , -0.8649908 ,  0.534436  , -0.85791147],
        [ 0.8787626 ,  0.19395334, -0.22797477, -1.090163  ],
        [ 0.6243966 , -0.9969999 ,  0.63737565, -0.06835947],
        [ 0.80834264,  0.30945462, -0.8320158 ,  0.555749  ]],
       dtype=float32),
 array([[ 1.3048441 , -0.8814793 , -0.32421663, -0.857098  ],
        [-0.35299706,  1.0903912 , -0.17924868,  1.788398  ],
        [-0.0658704 , -0.73542976, -0.4816955 , -0.5703053 ],
        [-1.6364878 ,  0.45202866, -0.59956676,  0.93426996]],
       dtype=float32),
 array([ 0.8238534 , -0.777692  ,  0.50479645, -0.71269673], dtype=float32)]