In [1]:
import numpy as np

## 1개의 셀로만 이루어져 있는 경우

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [4]:
X = np.array([[h]], dtype=np.float32)
X.shape

(1, 1, 4)

In [8]:
W1 = np.array([
    [1],
    [2],
    [3],
    [4],
], dtype="float32")
W1.shape

(4, 1)

In [6]:
b1 = np.array([5], dtype="float32")
b1

array([5.], dtype=float32)

In [9]:
z0 = np.dot(X, W1) + b1
z0.shape

(1, 1, 1)

In [10]:
h0 = np.tanh(z0)
h0

array([[[0.9999877]]], dtype=float32)

## 2개의 셀로 이루어져 있는 경우

In [11]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [12]:
X = np.array([[h], [e]], dtype=np.float32)
X.shape

(2, 1, 4)

In [16]:
z0 = np.dot(X[0], W1) + b1
z0.shape

(1, 1)

In [17]:
h0 = np.tanh(z0)
h0

array([[0.9999877]], dtype=float32)

In [20]:
z1 = np.dot(X[1], W1) + b1
z1.shape

(1, 1)

In [22]:
h1 = z1 + h0
h1 = np.tanh(h1)
h1

array([[0.99999976]], dtype=float32)

## Simple RNN을 활용한 자동 완성

In [23]:
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from keras.optimizers import Adam
import numpy as np

In [24]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [25]:
X = np.array([h, e, l, l], dtype="float32")

In [26]:
model = Sequential()
model.add(SimpleRNN(units=4, input_shape=(4, 4)))
model.add(Dense(4, activation="softmax"))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 4)                 36        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 20        
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(loss = "categorical_crossentropy", optimizer=Adam(lr=0.1), metrics=['acc'])

In [29]:
y = np.array([o], dtype="float32")

In [33]:

model.fit(X.reshape(-1, 4, 4), y, epochs=50)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
1/1 [==============================] - 0s 328ms/step - loss: 1.3475 - acc: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6469 - acc: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 2ms/step - loss: 0.3337 - acc: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 784us/step - loss: 0.1767 - acc: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0971 - acc: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0549 - acc: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0322 - acc: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 0.0197 - acc: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0126 - acc: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 2ms/step - loss: 0.0083 - acc: 1.0000
Epoch 11/50
1/1 [================