In [1]:
from sklearn.datasets import load_iris
import numpy as np

## 데이터 로드

In [2]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
X = data.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

## y 데이터 원핫 인코딩 수행
## 이유는 모르겠으나 OneHotEncoder를 통해서 transform 할 시에 리턴 값이 scipy의 sparse matrix로 나와서 .toarray() 함수를 사용해줌

In [4]:
y = data.target
y = y.reshape(-1, 1)
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y)
y = enc.transform(y)
y = np.array(y.toarray(), dtype="float32")
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

## 훈련용 데이터와 테스트용 데이터 분햘

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [6]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing

## 훈려용 데이터 스케일러 적용

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
X_train = scaler.transform(X_train)
X_train

array([[-2.47942352e-01, -6.69020738e-01,  7.29287795e-01,
         1.12737548e+00],
       [ 1.73559646e+00, -1.95975772e-01,  1.23417935e+00,
         6.05902242e-01],
       [ 1.98353881e+00, -6.69020738e-01,  1.40247653e+00,
         9.97007173e-01],
       [-6.19855880e-01,  1.45968161e+00, -1.17808028e+00,
        -1.21925410e+00],
       [-9.91769407e-01,  2.77069194e-01, -1.34637747e+00,
        -1.21925410e+00],
       [-9.91769407e-01,  1.22315913e+00, -1.23417935e+00,
        -1.21925410e+00],
       [-1.11574058e+00,  4.05467114e-02, -1.17808028e+00,
        -1.34962241e+00],
       [-9.91769407e-01,  9.86636643e-01, -1.12198122e+00,
        -6.97780861e-01],
       [ 3.71913528e-01, -1.14206570e+00,  1.12198122e+00,
         3.45165621e-01],
       [ 1.61162529e+00, -1.95975772e-01,  1.29027841e+00,
         1.25774379e+00],
       [-1.73559646e+00, -4.32498255e-01, -1.23417935e+00,
        -1.21925410e+00],
       [ 6.19855880e-01, -1.85163315e+00,  4.48792489e-01,
      

## 모델 구성

In [9]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation="sigmoid"))
model.add(Dense(3, activation="softmax"))
model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 51        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


## 학습 방법, cost 함수 및 학습률 0.01로 세팅

In [10]:
optimizers = Adam(0.001)
model.compile(loss="categorical_crossentropy", optimizer=optimizers, metrics=["acc"])

## 학습 수행

In [11]:
model.fit(X_train, y_train, epochs=1000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
105/105 [==============================] - 1s 5ms/step - loss: 1.2516 - acc: 0.3810
Epoch 2/1000
105/105 [==============================] - 0s 86us/step - loss: 1.2339 - acc: 0.3810
Epoch 3/1000
105/105 [==============================] - 0s 104us/step - loss: 1.2171 - acc: 0.3810
Epoch 4/1000
105/105 [==============================] - 0s 67us/step - loss: 1.1983 - acc: 0.3810
Epoch 5/1000
105/105 [==============================] - 0s 95us/step - loss: 1.1829 - acc: 0.3810
Epoch 6/1000
105/105 [==============================] - 0s 105us/step - loss: 1.1659 - acc: 0.3810
Epoch 7/1000
105/105 [==============================] - 0s 95us/step - loss: 1.1504 - acc: 0.3810
Epoch 8/1000
105/105 [==============================] - 0s 57us/step - loss: 1.1367 - acc: 0.3810
Epoch 9/1000
105/105 [==============================] - 0s 114us/step - loss: 1.1222 - acc: 0.3810
Epoch 10/1000
105/105 [==============================] - 0s 123us/st

105/105 [==============================] - 0s 86us/step - loss: 0.6210 - acc: 0.8476
Epoch 82/1000
105/105 [==============================] - 0s 76us/step - loss: 0.6159 - acc: 0.8476
Epoch 83/1000
105/105 [==============================] - 0s 95us/step - loss: 0.6110 - acc: 0.8476
Epoch 84/1000
105/105 [==============================] - 0s 76us/step - loss: 0.6061 - acc: 0.8476
Epoch 85/1000
105/105 [==============================] - 0s 66us/step - loss: 0.6015 - acc: 0.8476
Epoch 86/1000
105/105 [==============================] - 0s 152us/step - loss: 0.5968 - acc: 0.8476
Epoch 87/1000
105/105 [==============================] - 0s 76us/step - loss: 0.5922 - acc: 0.8476
Epoch 88/1000
105/105 [==============================] - 0s 76us/step - loss: 0.5876 - acc: 0.8476
Epoch 89/1000
105/105 [==============================] - 0s 85us/step - loss: 0.5830 - acc: 0.8476
Epoch 90/1000
105/105 [==============================] - 0s 85us/step - loss: 0.5785 - acc: 0.8476
Epoch 91/1000
105/105 [

105/105 [==============================] - 0s 76us/step - loss: 0.3948 - acc: 0.8762
Epoch 163/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3934 - acc: 0.8762
Epoch 164/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3920 - acc: 0.8762
Epoch 165/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3907 - acc: 0.8762
Epoch 166/1000
105/105 [==============================] - 0s 76us/step - loss: 0.3893 - acc: 0.8762
Epoch 167/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3881 - acc: 0.8762
Epoch 168/1000
105/105 [==============================] - 0s 57us/step - loss: 0.3868 - acc: 0.8762
Epoch 169/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3855 - acc: 0.8762
Epoch 170/1000
105/105 [==============================] - 0s 76us/step - loss: 0.3839 - acc: 0.8762
Epoch 171/1000
105/105 [==============================] - 0s 66us/step - loss: 0.3826 - acc: 0.8667
Epoch 172/1000


105/105 [==============================] - 0s 104us/step - loss: 0.3136 - acc: 0.8857
Epoch 243/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3128 - acc: 0.8857
Epoch 244/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3121 - acc: 0.8857
Epoch 245/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3114 - acc: 0.8857
Epoch 246/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3105 - acc: 0.8857
Epoch 247/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3098 - acc: 0.8857
Epoch 248/1000
105/105 [==============================] - 0s 95us/step - loss: 0.3090 - acc: 0.8857
Epoch 249/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3083 - acc: 0.8857
Epoch 250/1000
105/105 [==============================] - 0s 76us/step - loss: 0.3077 - acc: 0.8857
Epoch 251/1000
105/105 [==============================] - 0s 85us/step - loss: 0.3070 - acc: 0.8857
Epoch 252/1000

105/105 [==============================] - 0s 133us/step - loss: 0.2601 - acc: 0.9048
Epoch 324/1000
105/105 [==============================] - 0s 95us/step - loss: 0.2595 - acc: 0.9048
Epoch 325/1000
105/105 [==============================] - 0s 114us/step - loss: 0.2590 - acc: 0.9048
Epoch 326/1000
105/105 [==============================] - 0s 76us/step - loss: 0.2583 - acc: 0.9048
Epoch 327/1000
105/105 [==============================] - 0s 76us/step - loss: 0.2578 - acc: 0.9048
Epoch 328/1000
105/105 [==============================] - 0s 123us/step - loss: 0.2571 - acc: 0.9048
Epoch 329/1000
105/105 [==============================] - 0s 104us/step - loss: 0.2566 - acc: 0.9048
Epoch 330/1000
105/105 [==============================] - 0s 94us/step - loss: 0.2560 - acc: 0.9048
Epoch 331/1000
105/105 [==============================] - 0s 57us/step - loss: 0.2554 - acc: 0.9048
Epoch 332/1000
105/105 [==============================] - 0s 85us/step - loss: 0.2548 - acc: 0.9048
Epoch 333/1

105/105 [==============================] - 0s 104us/step - loss: 0.2151 - acc: 0.9429
Epoch 405/1000
105/105 [==============================] - 0s 76us/step - loss: 0.2145 - acc: 0.9429
Epoch 406/1000
105/105 [==============================] - 0s 76us/step - loss: 0.2142 - acc: 0.9333
Epoch 407/1000
105/105 [==============================] - 0s 85us/step - loss: 0.2135 - acc: 0.9429
Epoch 408/1000
105/105 [==============================] - 0s 66us/step - loss: 0.2130 - acc: 0.9429
Epoch 409/1000
105/105 [==============================] - 0s 95us/step - loss: 0.2125 - acc: 0.9429
Epoch 410/1000
105/105 [==============================] - 0s 104us/step - loss: 0.2119 - acc: 0.9429
Epoch 411/1000
105/105 [==============================] - 0s 85us/step - loss: 0.2114 - acc: 0.9524
Epoch 412/1000
105/105 [==============================] - 0s 57us/step - loss: 0.2109 - acc: 0.9429
Epoch 413/1000
105/105 [==============================] - 0s 86us/step - loss: 0.2104 - acc: 0.9429
Epoch 414/100

105/105 [==============================] - 0s 95us/step - loss: 0.1754 - acc: 0.9714
Epoch 486/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1750 - acc: 0.9714
Epoch 487/1000
105/105 [==============================] - 0s 104us/step - loss: 0.1746 - acc: 0.9714
Epoch 488/1000
105/105 [==============================] - 0s 114us/step - loss: 0.1741 - acc: 0.9714
Epoch 489/1000
105/105 [==============================] - 0s 85us/step - loss: 0.1737 - acc: 0.9714
Epoch 490/1000
105/105 [==============================] - 0s 104us/step - loss: 0.1733 - acc: 0.9714
Epoch 491/1000
105/105 [==============================] - 0s 105us/step - loss: 0.1730 - acc: 0.9714
Epoch 492/1000
105/105 [==============================] - 0s 152us/step - loss: 0.1725 - acc: 0.9714
Epoch 493/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1720 - acc: 0.9714
Epoch 494/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1716 - acc: 0.9714
Epoch 495/

105/105 [==============================] - 0s 67us/step - loss: 0.1439 - acc: 0.9619
Epoch 567/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1436 - acc: 0.9619
Epoch 568/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1432 - acc: 0.9619
Epoch 569/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1429 - acc: 0.9619
Epoch 570/1000
105/105 [==============================] - 0s 85us/step - loss: 0.1425 - acc: 0.9619
Epoch 571/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1422 - acc: 0.9619
Epoch 572/1000
105/105 [==============================] - 0s 86us/step - loss: 0.1418 - acc: 0.9619
Epoch 573/1000
105/105 [==============================] - 0s 66us/step - loss: 0.1414 - acc: 0.9714
Epoch 574/1000
105/105 [==============================] - 0s 85us/step - loss: 0.1412 - acc: 0.9714
Epoch 575/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1408 - acc: 0.9714
Epoch 576/1000


Epoch 648/1000
105/105 [==============================] - 0s 67us/step - loss: 0.1197 - acc: 0.9714
Epoch 649/1000
105/105 [==============================] - 0s 34us/step - loss: 0.1196 - acc: 0.9714
Epoch 650/1000
105/105 [==============================] - 0s 149us/step - loss: 0.1191 - acc: 0.9714
Epoch 651/1000
105/105 [==============================] - 0s 95us/step - loss: 0.1189 - acc: 0.9714
Epoch 652/1000
105/105 [==============================] - 0s 95us/step - loss: 0.1186 - acc: 0.9714
Epoch 653/1000
105/105 [==============================] - 0s 82us/step - loss: 0.1184 - acc: 0.9714
Epoch 654/1000
105/105 [==============================] - 0s 66us/step - loss: 0.1180 - acc: 0.9619
Epoch 655/1000
105/105 [==============================] - 0s 85us/step - loss: 0.1179 - acc: 0.9619
Epoch 656/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1177 - acc: 0.9619
Epoch 657/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1174 - acc: 0.9619

105/105 [==============================] - 0s 133us/step - loss: 0.1022 - acc: 0.9714
Epoch 730/1000
105/105 [==============================] - 0s 85us/step - loss: 0.1022 - acc: 0.9714
Epoch 731/1000
105/105 [==============================] - 0s 111us/step - loss: 0.1020 - acc: 0.9714
Epoch 732/1000
105/105 [==============================] - 0s 0us/step - loss: 0.1018 - acc: 0.9714
Epoch 733/1000
105/105 [==============================] - 0s 133us/step - loss: 0.1016 - acc: 0.9714
Epoch 734/1000
105/105 [==============================] - 0s 76us/step - loss: 0.1015 - acc: 0.9714
Epoch 735/1000
105/105 [==============================] - 0s 225us/step - loss: 0.1014 - acc: 0.9714
Epoch 736/1000
105/105 [==============================] - 0s 95us/step - loss: 0.1009 - acc: 0.9714
Epoch 737/1000
105/105 [==============================] - 0s 0us/step - loss: 0.1007 - acc: 0.9714
Epoch 738/1000
105/105 [==============================] - 0s 322us/step - loss: 0.1006 - acc: 0.9714
Epoch 739/10

105/105 [==============================] - 0s 76us/step - loss: 0.0891 - acc: 0.9714
Epoch 811/1000
105/105 [==============================] - 0s 66us/step - loss: 0.0889 - acc: 0.9714
Epoch 812/1000
105/105 [==============================] - 0s 95us/step - loss: 0.0888 - acc: 0.9714
Epoch 813/1000
105/105 [==============================] - 0s 57us/step - loss: 0.0886 - acc: 0.9714
Epoch 814/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0885 - acc: 0.9714
Epoch 815/1000
105/105 [==============================] - 0s 57us/step - loss: 0.0884 - acc: 0.9714
Epoch 816/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0882 - acc: 0.9714
Epoch 817/1000
105/105 [==============================] - 0s 86us/step - loss: 0.0880 - acc: 0.9619
Epoch 818/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0879 - acc: 0.9619
Epoch 819/1000
105/105 [==============================] - 0s 66us/step - loss: 0.0877 - acc: 0.9619
Epoch 820/1000


105/105 [==============================] - 0s 85us/step - loss: 0.0792 - acc: 0.9619
Epoch 893/1000
105/105 [==============================] - 0s 57us/step - loss: 0.0791 - acc: 0.9619
Epoch 894/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0790 - acc: 0.9619
Epoch 895/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0789 - acc: 0.9619
Epoch 896/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0787 - acc: 0.9619
Epoch 897/1000
105/105 [==============================] - 0s 57us/step - loss: 0.0786 - acc: 0.9619
Epoch 898/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0787 - acc: 0.9714
Epoch 899/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0786 - acc: 0.9714
Epoch 900/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0785 - acc: 0.9714
Epoch 901/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0784 - acc: 0.9714
Epoch 902/1000


105/105 [==============================] - 0s 172us/step - loss: 0.0718 - acc: 0.9714
Epoch 975/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0718 - acc: 0.9619
Epoch 976/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0715 - acc: 0.9619
Epoch 977/1000
105/105 [==============================] - 0s 66us/step - loss: 0.0714 - acc: 0.9619
Epoch 978/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0714 - acc: 0.9619
Epoch 979/1000
105/105 [==============================] - 0s 85us/step - loss: 0.0716 - acc: 0.9619
Epoch 980/1000
105/105 [==============================] - 0s 57us/step - loss: 0.0712 - acc: 0.9619
Epoch 981/1000
105/105 [==============================] - 0s 76us/step - loss: 0.0711 - acc: 0.9619
Epoch 982/1000
105/105 [==============================] - 0s 78us/step - loss: 0.0712 - acc: 0.9619
Epoch 983/1000
105/105 [==============================] - 0s 92us/step - loss: 0.0709 - acc: 0.9619
Epoch 984/1000

## 테스트 데이터 스케일러 적용

In [12]:
X_test = scaler.transform(X_test)
p = model.predict(X_test)
p1 = np.argmax(p, 1)
p1

array([0, 1, 1, 1, 2, 2, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0,
       1, 0, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 2, 2,
       2], dtype=int64)

In [13]:
target = np.argmax(y_test, 1)
target = target.reshape(-1)
target

array([0, 1, 1, 1, 2, 2, 2, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0,
       1, 0, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2,
       2], dtype=int64)

In [14]:
pred2 = (p1 == target)
pred2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True])

## 정확도 계산

In [15]:
acc = np.sum(pred2) / len(pred2)
acc

0.9555555555555556