In [1]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

In [2]:
tf.enable_eager_execution()

## 데이터 로드

In [3]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
X = data.data
X = np.array(X, dtype="float32")
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y = data.target
y = np.array(y, dtype="float32")
y = y.reshape([-1, 1])
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

## 트레인셋과 테스트셋으로 분할

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 이유는 모르겠으나 OneHotEncoder를 통해서 transform 할 시에 리턴 값이 scipy의 sparse matrix로 나와서 .toarray() 함수를 사용해줌

In [7]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder.fit(y_train)
onehot_y_train = encoder.transform(y_train)
onehot_y_train = np.array(onehot_y_train.toarray(), dtype="float32")
onehot_y_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1

In [8]:
print(f"X_train size : {X_train.shape}, y_train size : {onehot_y_train.shape}")
print(f"X_test size : {X_test.shape}, y_test size : {y_test.shape}")

X_train size : (120, 4), y_train size : (120, 3)
X_test size : (30, 4), y_test size : (30, 1)


## 훈련데이터 StandardScaler 적용

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

## weight 값 초기화 객체 생성

In [10]:
from tensorflow.contrib.layers import xavier_initializer
Initializer = xavier_initializer()

## 모델 weight 값 변수 생성 및 초기화

In [11]:
w0 = tf.Variable(Initializer([4, 20]))
w0

<tf.Variable 'Variable:0' shape=(4, 20) dtype=float32, numpy=
array([[ 0.38873863, -0.02970433,  0.07428885, -0.1770593 , -0.42666292,
         0.20104861,  0.24770749, -0.36141098,  0.05330324,  0.36428738,
        -0.33912587,  0.18681848,  0.2989533 , -0.01556098,  0.3457067 ,
        -0.26877153,  0.19411373, -0.28454578, -0.4367783 ,  0.23162591],
       [-0.4747504 , -0.49811482,  0.40386474, -0.15118325,  0.3748108 ,
        -0.27719188,  0.3736117 ,  0.12454367,  0.3383242 ,  0.17934418,
         0.09611762,  0.11630654, -0.49716485,  0.05821061,  0.4420054 ,
         0.05956483,  0.06107926,  0.30872118,  0.44516504,  0.3259833 ],
       [ 0.01581359, -0.31339765,  0.26195478,  0.29025388,  0.19735897,
        -0.343961  ,  0.33178496,  0.07073891,  0.3788092 ,  0.3376466 ,
         0.0880152 , -0.44917214,  0.39400113, -0.47757113, -0.45409584,
         0.44874156,  0.3630122 , -0.13855445,  0.0828166 ,  0.32489085],
       [ 0.13444662,  0.0007683 , -0.16192842,  0.1868912 ,

In [12]:
b0 = tf.Variable(Initializer([ 20]))
b0

<tf.Variable 'Variable:0' shape=(20,) dtype=float32, numpy=
array([-0.06336403,  0.37297684,  0.12235975,  0.16581297, -0.26455888,
        0.30309957, -0.27728128,  0.35386336,  0.25975782,  0.19819689,
       -0.29715246, -0.37208834, -0.33460918, -0.08901843, -0.08727202,
       -0.33232462,  0.13080382, -0.35763127,  0.36428183,  0.06121585],
      dtype=float32)>

In [13]:
w1 = tf.Variable(Initializer([20, 3]))
w1

<tf.Variable 'Variable:0' shape=(20, 3) dtype=float32, numpy=
array([[ 0.49118215, -0.282363  , -0.34753215],
       [ 0.02643406,  0.18814766,  0.45400685],
       [-0.22523165, -0.10517055,  0.4042272 ],
       [-0.08870742, -0.04025981,  0.39334226],
       [-0.26479357, -0.26367155,  0.34356743],
       [-0.05598477, -0.37799138,  0.01614004],
       [-0.49844107,  0.242239  , -0.06752276],
       [-0.47208643, -0.12702006, -0.47772756],
       [-0.4552967 , -0.39051613, -0.46875033],
       [ 0.38383883,  0.31410128,  0.15940726],
       [ 0.2585181 , -0.03324091,  0.48060614],
       [-0.4866779 , -0.32926336, -0.22445679],
       [ 0.44783896,  0.5072132 , -0.02799639],
       [ 0.49486655, -0.5048301 , -0.02263448],
       [-0.24675652,  0.3798085 ,  0.37515384],
       [ 0.00900269,  0.4011988 , -0.21671799],
       [ 0.38493115, -0.29029667,  0.33659303],
       [-0.29255933, -0.48761615,  0.01281601],
       [ 0.06907499,  0.3771497 , -0.23259684],
       [ 0.02029717,  0.32

In [14]:
b1 = tf.Variable(Initializer([3]))
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-0.17357302,  0.12124133, -0.2795856 ], dtype=float32)>

## 훈련 Adam 객체 생성 학습률 0.005로 셋팅

In [15]:
optimizer = tf.train.AdamOptimizer(0.005)

## 훈련 수행

In [16]:
for epochs in range(1000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X_train, w0) + b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0, w1) + b1)

        cost = -tf.reduce_sum(onehot_y_train * tf.log(hypothesis1)) /  hypothesis1.get_shape().as_list()[0]
        grads = tape.gradient(cost, [w0, w1, b0, b1])

        optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))
        if epochs % 100 == 0:
            print("=" * 50)
            print(f"epoch : {epochs}, cost : {cost.numpy()}")

Instructions for updating:
Colocations handled automatically by placer.
epoch : 0, cost : 1.2657421827316284
epoch : 100, cost : 0.34505796432495117
epoch : 200, cost : 0.14536668360233307
epoch : 300, cost : 0.07270608097314835
epoch : 400, cost : 0.050286147743463516
epoch : 500, cost : 0.04057580232620239
epoch : 600, cost : 0.03510776907205582
epoch : 700, cost : 0.031461335718631744
epoch : 800, cost : 0.028749356046319008
epoch : 900, cost : 0.0265839621424675


## 테스트용 X데이터 scaler 적용

In [17]:
X_test = scaler.transform(X_test)
X_test

array([[ 3.1381983e-01, -1.4318129e-01,  6.5270340e-01,  8.0647779e-01],
       [-1.2403356e+00,  8.2894199e-02, -1.2325667e+00, -1.3441298e+00],
       [ 7.9202169e-01, -1.4318129e-01,  1.1668680e+00,  1.3441298e+00],
       [-1.8380878e+00, -1.4318129e-01, -1.5182136e+00, -1.4785428e+00],
       [ 1.7484255e+00, -3.6925679e-01,  1.4525150e+00,  8.0647779e-01],
       [ 1.9426948e-01, -1.9517869e+00,  1.3853879e-01, -2.6882595e-01],
       [-4.4831168e-02, -1.0474844e+00,  1.3853879e-01,  7.5609833e-08],
       [ 1.2702236e+00,  8.2894199e-02,  6.5270340e-01,  4.0323895e-01],
       [-1.1207852e+00,  8.2894199e-02, -1.2896960e+00, -1.4785428e+00],
       [-1.0012349e+00,  5.3504574e-01, -1.3468255e+00, -1.3441298e+00],
       [ 1.2702236e+00,  8.2894199e-02,  7.6696211e-01,  1.4785426e+00],
       [ 7.9202169e-01, -1.4318129e-01,  9.9547970e-01,  8.0647779e-01],
       [ 1.1506733e+00, -1.4318129e-01,  9.9547970e-01,  1.2097167e+00],
       [-1.1207852e+00,  1.2132728e+00, -1.3468255e

## 훈련된 모델을 활용한 예측

In [18]:
hypothesis = tf.sigmoid(tf.matmul(X_test, w0) + b0)
pred = tf.nn.softmax(tf.matmul(hypothesis, w1) + b1)
pred

<tf.Tensor: id=84168, shape=(30, 3), dtype=float32, numpy=
array([[5.7904859e-04, 3.8723287e-01, 6.1218810e-01],
       [9.9837470e-01, 1.6252797e-03, 1.7308238e-08],
       [3.2543645e-07, 3.9432867e-05, 9.9996018e-01],
       [9.9916756e-01, 8.3247089e-04, 1.0148245e-08],
       [8.5961386e-07, 2.4327880e-04, 9.9975592e-01],
       [6.1668703e-05, 9.9990201e-01, 3.6389989e-05],
       [1.9992123e-04, 9.9976879e-01, 3.1343137e-05],
       [1.6637925e-04, 9.9794585e-01, 1.8876710e-03],
       [9.9853289e-01, 1.4670952e-03, 1.5181495e-08],
       [9.9874973e-01, 1.2502022e-03, 1.3169494e-08],
       [1.7313365e-06, 3.7585563e-04, 9.9962234e-01],
       [4.0229515e-05, 1.7581940e-02, 9.8237783e-01],
       [1.5519727e-06, 3.4516185e-04, 9.9965334e-01],
       [9.9924266e-01, 7.5737666e-04, 8.6147809e-09],
       [6.9649764e-07, 2.1408837e-04, 9.9978524e-01],
       [9.9880373e-01, 1.1962246e-03, 1.3371409e-08],
       [9.9780685e-01, 2.1931024e-03, 1.8928109e-08],
       [7.9824490e-04, 

In [19]:
pred02 = tf.argmax(pred, 1)
pred02

<tf.Tensor: id=84171, shape=(30,), dtype=int64, numpy=
array([2, 0, 2, 0, 2, 1, 1, 1, 0, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 2, 2, 0,
       1, 0, 0, 0, 2, 1, 1, 1], dtype=int64)>

## 정확도 측정

In [20]:
acc = tf.reduce_sum(tf.cast(tf.equal(pred02, y_test.reshape(-1)), dtype="float32")) / len(y_test)
acc

<tf.Tensor: id=84179, shape=(), dtype=float32, numpy=0.93333334>