In [1]:
import numpy as np

In [2]:
x = np.array([
    2, 8, 3, 7, 1, 2, 0, 4, 5], dtype="float32")
x

array([2., 8., 3., 7., 1., 2., 0., 4., 5.], dtype=float32)

In [3]:
w = np.array([3, 5, 1, 2], dtype="float32")
w

array([3., 5., 1., 2.], dtype=float32)

In [6]:
for i in range(len(x) - len(w) + 1):
    print(f"x[{i} : {i + len(w)}] = {x[i : i + len(w)]} ")

x[0 : 4] = [2. 8. 3. 7.] 
x[1 : 5] = [8. 3. 7. 1.] 
x[2 : 6] = [3. 7. 1. 2.] 
x[3 : 7] = [7. 1. 2. 0.] 
x[4 : 8] = [1. 2. 0. 4.] 
x[5 : 9] = [2. 0. 4. 5.] 


In [8]:
for i in range(len(x) - len(w) + 1):
    print(f"x[{i} : {i + len(w)}] * w = {np.dot( x[i : i + len(w)], w )} ")

x[0 : 4] * w = 63.0 
x[1 : 5] * w = 48.0 
x[2 : 6] * w = 49.0 
x[3 : 7] * w = 28.0 
x[4 : 8] * w = 21.0 
x[5 : 9] * w = 20.0 


In [9]:
from scipy.signal import correlate
correlate(x, w, mode='valid')

array([63., 48., 49., 28., 21., 20.], dtype=float32)

In [10]:
correlate(x, w, mode='same')

array([18., 24., 63., 48., 49., 28., 21., 20., 25.], dtype=float32)

## 2차원 conv 연산

In [11]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype="float32")
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [12]:
w = np.array([
    [2, 0],
    [0, 0]
], dtype="float32")
w

array([[2., 0.],
       [0., 0.]], dtype=float32)

In [13]:
from scipy.signal import correlate2d

In [15]:
correlate2d(x, w, mode="valid")

array([[ 2.,  4.],
       [ 8., 10.]], dtype=float32)

## 3차원 배열

In [22]:
x = np.array([
    [
        [1, 10, 100],
        [2, 20, 200],
        [3, 30, 300]
    ],[
    [4, 40, 400],
    [5,  50, 500],
    [6, 60, 600]
    ],[
    [7, 70, 700],
    [8, 80, 800],
    [9, 90, 99]]
])
x

array([[[  1,  10, 100],
        [  2,  20, 200],
        [  3,  30, 300]],

       [[  4,  40, 400],
        [  5,  50, 500],
        [  6,  60, 600]],

       [[  7,  70, 700],
        [  8,  80, 800],
        [  9,  90,  99]]])

In [23]:
x.shape

(3, 3, 3)

## 4차원 배열

In [24]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype="float32")
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [26]:
x = x.reshape(1, 3, 3, 1)
x

array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)