In [1]:
import tensorflow as tf
import numpy as np

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

In [2]:
tf.enable_eager_execution()

In [4]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("./mnist/data/", one_hot=True)

Extracting ./mnist/data/train-images-idx3-ubyte.gz
Extracting ./mnist/data/train-labels-idx1-ubyte.gz
Extracting ./mnist/data/t10k-images-idx3-ubyte.gz
Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz


In [5]:
X, y = mnist.train.next_batch(1)

In [6]:
X = X.reshape(-1, 28, 28, 1)
X.shape

(1, 28, 28, 1)

In [7]:
y

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [8]:
initializer = tf.contrib.layers.xavier_initializer()

In [9]:
w1 = tf.Variable(initializer([3, 3, 1, 32]))
w1

<tf.Variable 'Variable:0' shape=(3, 3, 1, 32) dtype=float32, numpy=
array([[[[-0.02994953,  0.10449511, -0.01756781,  0.11795698,
          -0.08124927, -0.01154603,  0.10687542, -0.10760946,
           0.01598965, -0.08747794,  0.03885932, -0.11950687,
          -0.02753939,  0.06603782, -0.04640255, -0.09069131,
          -0.08324961, -0.10379408,  0.08962135,  0.00193852,
           0.05113499,  0.12857725,  0.09597689,  0.06830767,
           0.12562604,  0.12321813,  0.12478803,  0.10747123,
           0.04846165,  0.09258862, -0.13937372, -0.00396632]],

        [[ 0.0410229 , -0.06589153, -0.02375896,  0.1404954 ,
          -0.06686874,  0.0227586 ,  0.06535994,  0.09362324,
           0.09308738, -0.00086105,  0.12994851,  0.04482946,
          -0.00150317, -0.01197413,  0.1263174 , -0.05322072,
          -0.05700865,  0.01236485, -0.13259114,  0.09337237,
           0.1049244 , -0.07505985, -0.06414718, -0.11024657,
           0.04324988, -0.0904238 ,  0.05155128, -0.1319061 ,

In [10]:
conv1 = tf.nn.conv2d(X, w1, strides=[1, 1, 1, 1], padding="SAME")
conv1

<tf.Tensor: id=18, shape=(1, 28, 28, 32), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0.

In [11]:
conv1 = tf.nn.relu(conv1)
conv1

<tf.Tensor: id=20, shape=(1, 28, 28, 32), dtype=float32, numpy=
array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0.

In [ ]:
w2 = tf.Variable(initializer([3, 3, 32, 64]))
w2