In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import tensorflow as tf
import numpy as np

Using TensorFlow backend.
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing

In [2]:
data = datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [3]:
X = data["data"]
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [4]:
y = data["target"]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

## 아래의 작업을 하는 이유

값을 표준화 시켜서 값의 차이를 줄일 것은 줄이고 키울 것은 키우기 위해

값의 차이가 크지만, 중요하지 않은 것이 있을 수 있고

값의 차이가 작지만 중요한 것이 있을 수 있으므로 그것을 인식시키기 위해

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
X_train = scaler.transform(X_train)
X_train

array([[-0.67565533, -0.43635692, -0.70251425, ..., -1.08544804,
         0.45444686, -1.02241702],
       [-2.06394608, -1.37873723, -2.01221854, ..., -1.74021816,
         0.02863427,  0.61698241],
       [ 2.01237916,  0.90820085,  1.87404187, ...,  1.31466614,
        -0.14613955, -0.46738158],
       ...,
       [-1.1040159 , -0.68385074, -1.11689337, ..., -1.37816343,
        -0.37016781, -0.54158105],
       [-0.96602055, -2.26400359, -0.97294239, ..., -1.04028623,
        -1.3091799 , -0.3663067 ],
       [-0.93439661, -1.63575004, -0.95754879, ..., -1.2545387 ,
        -1.22497069, -0.98327241]])

## 표준화 직접 해보는 예제

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame({
    "price" : [95000, 100000, 120000],
    "year" : [25, 10, 5]
})
df

price  year
0   95000    25
1  100000    10
2  120000     5

In [10]:
df.mean()

price    105000.000000
year         13.333333
dtype: float64

In [11]:
df.std()

price    13228.756555
year        10.408330
dtype: float64

In [12]:
(df-df.mean())/df.std()

price      year
0 -0.755929  1.120897
1 -0.377964 -0.320256
2  1.133893 -0.800641

## 딥러닝 모델 초기화

In [13]:
model = Sequential()

## Dense 레이어 추가

In [14]:
model.add(Dense(1, input_dim=30, activation="sigmoid"))

Instructions for updating:
Colocations handled automatically by placer.


## 모델 구성 확인

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


## 모델 학습 방법 및 loss 계산 설정

In [16]:
model.compile(loss="binary_crossentropy", optimizer=Adam(lr=0.001), metrics=['acc'])

## 모델 학습 시작

In [17]:
model.fit(X_train, y_train, epochs=1000)

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
455/455 [==============================] - 0s 392us/step - loss: 1.2633 - acc: 0.2549
Epoch 2/1000
455/455 [==============================] - 0s 37us/step - loss: 1.1375 - acc: 0.3143
Epoch 3/1000
455/455 [==============================] - 0s 31us/step - loss: 1.0249 - acc: 0.3824
Epoch 4/1000
455/455 [==============================] - 0s 31us/step - loss: 0.9292 - acc: 0.4374
Epoch 5/1000
455/455 [==============================] - 0s 33us/step - loss: 0.8471 - acc: 0.5033
Epoch 6/1000
455/455 [==============================] - 0s 28us/step - loss: 0.7750 - acc: 0.5385
Epoch 7/1000
455/455 [==============================] - 0s 44us/step - loss: 0.7139 - acc: 0.5846
Epoch 8/1000
455/455 [==============================] - 0s 37us/step - loss: 0.6605 - acc: 0.6462
Epoch 9/1000
455/455 [==============================] - 0s 39us/step - loss: 0.6133 - acc: 0.6659
Epoch 10/1000
455/455 [==============================] - 0s 31us/step

455/455 [==============================] - 0s 37us/step - loss: 0.1224 - acc: 0.9648
Epoch 81/1000
455/455 [==============================] - 0s 35us/step - loss: 0.1214 - acc: 0.9670
Epoch 82/1000
455/455 [==============================] - 0s 28us/step - loss: 0.1205 - acc: 0.9670
Epoch 83/1000
455/455 [==============================] - 0s 35us/step - loss: 0.1196 - acc: 0.9670
Epoch 84/1000
455/455 [==============================] - 0s 33us/step - loss: 0.1187 - acc: 0.9670
Epoch 85/1000
455/455 [==============================] - 0s 35us/step - loss: 0.1176 - acc: 0.9692
Epoch 86/1000
455/455 [==============================] - 0s 44us/step - loss: 0.1167 - acc: 0.9692
Epoch 87/1000
455/455 [==============================] - 0s 33us/step - loss: 0.1159 - acc: 0.9692
Epoch 88/1000
455/455 [==============================] - 0s 44us/step - loss: 0.1151 - acc: 0.9714
Epoch 89/1000
455/455 [==============================] - 0s 37us/step - loss: 0.1142 - acc: 0.9714
Epoch 90/1000
455/455 [=

455/455 [==============================] - 0s 42us/step - loss: 0.0834 - acc: 0.9846
Epoch 162/1000
455/455 [==============================] - 0s 35us/step - loss: 0.0832 - acc: 0.9846
Epoch 163/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0829 - acc: 0.9846
Epoch 164/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0827 - acc: 0.9846
Epoch 165/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0825 - acc: 0.9846
Epoch 166/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0822 - acc: 0.9846
Epoch 167/1000
455/455 [==============================] - 0s 35us/step - loss: 0.0820 - acc: 0.9846
Epoch 168/1000
455/455 [==============================] - 0s 33us/step - loss: 0.0818 - acc: 0.9846
Epoch 169/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0816 - acc: 0.9846
Epoch 170/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0813 - acc: 0.9846
Epoch 171/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0702 - acc: 0.9846
Epoch 244/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0700 - acc: 0.9846
Epoch 245/1000
455/455 [==============================] - 0s 61us/step - loss: 0.0700 - acc: 0.9846
Epoch 246/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0699 - acc: 0.9846
Epoch 247/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0697 - acc: 0.9846
Epoch 248/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0696 - acc: 0.9846
Epoch 249/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0695 - acc: 0.9846
Epoch 250/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0694 - acc: 0.9846
Epoch 251/1000
455/455 [==============================] - 0s 57us/step - loss: 0.0693 - acc: 0.9846
Epoch 252/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0692 - acc: 0.9846
Epoch 253/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0634 - acc: 0.9868
Epoch 326/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0633 - acc: 0.9868
Epoch 327/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0633 - acc: 0.9868
Epoch 328/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0633 - acc: 0.9868
Epoch 329/1000
455/455 [==============================] - 0s 85us/step - loss: 0.0632 - acc: 0.9868
Epoch 330/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0632 - acc: 0.9868
Epoch 331/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0631 - acc: 0.9868
Epoch 332/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0630 - acc: 0.9868
Epoch 333/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0629 - acc: 0.9868
Epoch 334/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0629 - acc: 0.9868
Epoch 335/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0593 - acc: 0.9868
Epoch 408/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0593 - acc: 0.9868
Epoch 409/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0593 - acc: 0.9868
Epoch 410/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0593 - acc: 0.9868
Epoch 411/1000
455/455 [==============================] - 0s 70us/step - loss: 0.0592 - acc: 0.9868
Epoch 412/1000
455/455 [==============================] - 0s 61us/step - loss: 0.0592 - acc: 0.9868
Epoch 413/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0591 - acc: 0.9868
Epoch 414/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0591 - acc: 0.9868
Epoch 415/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0590 - acc: 0.9868
Epoch 416/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0590 - acc: 0.9868
Epoch 417/1000


455/455 [==============================] - 0s 48us/step - loss: 0.0566 - acc: 0.9868
Epoch 489/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0566 - acc: 0.9868
Epoch 490/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0566 - acc: 0.9868
Epoch 491/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0565 - acc: 0.9868
Epoch 492/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0565 - acc: 0.9868
Epoch 493/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0565 - acc: 0.9868
Epoch 494/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0565 - acc: 0.9868
Epoch 495/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0564 - acc: 0.9868
Epoch 496/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0564 - acc: 0.9868
Epoch 497/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0564 - acc: 0.9868
Epoch 498/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0546 - acc: 0.9890
Epoch 571/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0546 - acc: 0.9890
Epoch 572/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0546 - acc: 0.9890
Epoch 573/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0546 - acc: 0.9890
Epoch 574/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0545 - acc: 0.9890
Epoch 575/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0546 - acc: 0.9890
Epoch 576/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0545 - acc: 0.9890
Epoch 577/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0545 - acc: 0.9890
Epoch 578/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0545 - acc: 0.9890
Epoch 579/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0545 - acc: 0.9890
Epoch 580/1000


455/455 [==============================] - 0s 39us/step - loss: 0.0531 - acc: 0.9890
Epoch 653/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0531 - acc: 0.9890
Epoch 654/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0530 - acc: 0.9890
Epoch 655/1000
455/455 [==============================] - 0s 37us/step - loss: 0.0531 - acc: 0.9890
Epoch 656/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0530 - acc: 0.9890
Epoch 657/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0530 - acc: 0.9890
Epoch 658/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0530 - acc: 0.9890
Epoch 659/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0530 - acc: 0.9890
Epoch 660/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0529 - acc: 0.9890
Epoch 661/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0529 - acc: 0.9890
Epoch 662/1000


455/455 [==============================] - 0s 53us/step - loss: 0.0519 - acc: 0.9890
Epoch 735/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0518 - acc: 0.9890
Epoch 736/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0519 - acc: 0.9890
Epoch 737/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0518 - acc: 0.9890
Epoch 738/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0518 - acc: 0.9890
Epoch 739/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0518 - acc: 0.9890
Epoch 740/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0518 - acc: 0.9890
Epoch 741/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0518 - acc: 0.9890
Epoch 742/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0518 - acc: 0.9890
Epoch 743/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0518 - acc: 0.9890
Epoch 744/1000


455/455 [==============================] - 0s 46us/step - loss: 0.0509 - acc: 0.9890
Epoch 817/1000
455/455 [==============================] - 0s 112us/step - loss: 0.0509 - acc: 0.9890
Epoch 818/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0509 - acc: 0.9890
Epoch 819/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0509 - acc: 0.9890
Epoch 820/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0508 - acc: 0.9890
Epoch 821/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0508 - acc: 0.9890
Epoch 822/1000
455/455 [==============================] - 0s 66us/step - loss: 0.0509 - acc: 0.9890
Epoch 823/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0508 - acc: 0.9890
Epoch 824/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0508 - acc: 0.9890
Epoch 825/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0508 - acc: 0.9890
Epoch 826/1000

455/455 [==============================] - 0s 61us/step - loss: 0.0500 - acc: 0.9890
Epoch 898/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0500 - acc: 0.9890
Epoch 899/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0500 - acc: 0.9890
Epoch 900/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0500 - acc: 0.9890
Epoch 901/1000
455/455 [==============================] - 0s 50us/step - loss: 0.0500 - acc: 0.9890
Epoch 902/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0500 - acc: 0.9890
Epoch 903/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0500 - acc: 0.9890
Epoch 904/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0499 - acc: 0.9890
Epoch 905/1000
455/455 [==============================] - 0s 48us/step - loss: 0.0499 - acc: 0.9890
Epoch 906/1000
455/455 [==============================] - 0s 64us/step - loss: 0.0500 - acc: 0.9890
Epoch 907/1000


455/455 [==============================] - 0s 42us/step - loss: 0.0492 - acc: 0.9890
Epoch 980/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0492 - acc: 0.9890
Epoch 981/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0492 - acc: 0.9890
Epoch 982/1000
455/455 [==============================] - 0s 55us/step - loss: 0.0492 - acc: 0.9890
Epoch 983/1000
455/455 [==============================] - 0s 44us/step - loss: 0.0492 - acc: 0.9890
Epoch 984/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0492 - acc: 0.9890
Epoch 985/1000
455/455 [==============================] - 0s 53us/step - loss: 0.0492 - acc: 0.9890
Epoch 986/1000
455/455 [==============================] - 0s 42us/step - loss: 0.0491 - acc: 0.9890
Epoch 987/1000
455/455 [==============================] - 0s 46us/step - loss: 0.0491 - acc: 0.9890
Epoch 988/1000
455/455 [==============================] - 0s 39us/step - loss: 0.0491 - acc: 0.9890
Epoch 989/1000


In [18]:
X_test = scaler.transform(X_test)
X_test

array([[ 0.53467892,  0.95579582,  0.43869251, ..., -0.22342021,
         0.05405592,  0.07363192],
       [ 0.27018783, -0.67433174,  0.308887  , ...,  0.42359486,
        -0.51475343, -0.31956687],
       [-0.75327771, -1.13838266, -0.72830893, ..., -0.68826746,
        -0.92944404, -0.11215889],
       ...,
       [ 1.62139233,  0.55599811,  1.5620094 , ...,  1.02727284,
         0.24789598, -0.0414649 ],
       [ 0.26443802,  1.55073288,  0.24315216, ...,  0.5802166 ,
        -0.41306684,  0.64970029],
       [ 0.07469441, -0.63863552,  0.08297549, ...,  0.40990946,
         0.22088548,  0.25591724]])

In [19]:
pred = model.predict(X_test)
pred

array([[1.6803414e-02],
       [9.6584868e-01],
       [9.9999803e-01],
       [9.9989551e-01],
       [9.9999923e-01],
       [9.9999177e-01],
       [9.9864709e-01],
       [9.9990523e-01],
       [9.9397093e-01],
       [9.4839025e-01],
       [9.9617124e-01],
       [9.8644257e-01],
       [0.0000000e+00],
       [9.8538291e-01],
       [9.9946332e-01],
       [0.0000000e+00],
       [9.9986839e-01],
       [1.1622286e-01],
       [0.0000000e+00],
       [1.0987192e-02],
       [0.0000000e+00],
       [9.9999940e-01],
       [5.3644180e-07],
       [2.9802322e-07],
       [4.0759146e-03],
       [9.8943710e-06],
       [7.3164701e-05],
       [9.6522033e-01],
       [2.3543835e-06],
       [9.9997431e-01],
       [1.8428206e-02],
       [3.2484531e-06],
       [9.9999976e-01],
       [8.5718179e-01],
       [9.9992782e-01],
       [9.9993730e-01],
       [9.9967277e-01],
       [9.9999928e-01],
       [5.0544739e-05],
       [9.9867928e-01],
       [9.9999976e-01],
       [1.545846

In [21]:
pred01 = np.where(pred>0.5, 1, 0)
pred01

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
    

In [22]:
pred02 = pred01.flatten()
pred02

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1])

In [24]:
pred03 = (pred02 == y_test)
pred03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [26]:
acc = np.sum(pred03) / len(pred03)
acc

0.9912280701754386