In [1]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\library\python\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a

In [2]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype="float32")
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
X.shape

(4, 2)

In [5]:
y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype="float32")
y

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [25]:
w0 = tf.Variable([
    [1, 2],
    [3, 4]
], dtype="float32")
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [26]:
b0 = tf.Variable([
    [0, 0]
], dtype="float32")
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [27]:
w1 = tf.Variable([
    [5],
    [6]
], dtype="float32")
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.],
       [6.]], dtype=float32)>

In [28]:
b1 = tf.Variable([
    [0]
], dtype="float32")
b1

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>

## arr라는 하나의 행의 예제에 대해서 순전파 계산

In [9]:
arr = np.array([
    [0, 1]
], dtype="float32")
arr

array([[0., 1.]], dtype=float32)

In [13]:
hypothesis0 = tf.sigmoid(tf.matmul(arr, w0) + b0)
hypothesis0

<tf.Tensor: id=28, shape=(1, 2), dtype=float32, numpy=array([[0.95257413, 0.98201376]], dtype=float32)>

In [18]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=61, shape=(1, 1), dtype=float32, numpy=array([[0.9999764]], dtype=float32)>

## 입력 X에 대해서 순전파 계산

In [21]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
hypothesis0

<tf.Tensor: id=86, shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [22]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
hypothesis1

<tf.Tensor: id=92, shape=(4, 1), dtype=float32, numpy=
array([[0.9959299],
       [0.9999764],
       [0.999869 ],
       [0.9999814]], dtype=float32)>

In [23]:
optimizer = tf.train.AdamOptimizer(0.1)

## 입력 데이터를 통한 모델 학습

In [29]:
for step in range(5000):
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
        hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
        
        cost = -tf.reduce_mean(y * tf.log(hypothesis1) + (1-y) * tf.log(1-hypothesis1))
        
        grads = tape.gradient(cost, [w0, w1, b0, b1])
        
        optimizer.apply_gradients(grads_and_vars=zip(grads, [w0, w1, b0, b1]))
        
        if step % 100 == 0:
            print(f"cost : {cost}, w0 : {w0}, w1:{w1}")

cost : 4.0991926193237305, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
cost : 0.5574862957000732, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0565376, -4.4126096],
       [ 1.2810544,  3.060032 ]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.685531 ],
       [3.8502126]], dtype=float32)>
cost : 0.5103297233581543, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.5863264, -6.2746277],
       [ 1.5904136,  4.8805466]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.3543894],
       [4.4116955]], dtype=float32)>
cost : 0.49529534578323364, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8877606, -7.37706

       [ 12.661127]], dtype=float32)>
cost : 0.00204339437186718, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.08532 , -12.427614],
       [  8.57395 ,  12.44262 ]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-12.558693],
       [ 13.109066]], dtype=float32)>
cost : 0.001675998792052269, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.184334, -12.440248],
       [  8.684057,  12.500909]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-12.950265],
       [ 13.491261]], dtype=float32)>
cost : 0.0014093072386458516, w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -8.26962 , -12.452357],
       [  8.777926,  12.54883 ]], dtype=float32)>, w1:<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-13.292456],
       [ 13.826859]], dtype=float32)>
cost : 0.0012071061646565795, w0 : <tf.Variable 'Variabl

## 학습된 모델을 통한 예측 및 정확도 평가

In [35]:
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)
pred = tf.sigmoid(tf.matmul(hypothesis0, w1)+b1)
pred01 = tf.cast(pred>0.5, dtype="float32")
tf.reduce_mean(tf.cast(tf.equal(pred01, y), dtype="float32"))

<tf.Tensor: id=435587, shape=(), dtype=float32, numpy=1.0>